# Generated by Django 2.1.2 on 2019-11-13 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("approval_flows", "0002_auto_20191113_0931")]

    operations = [
        migrations.AlterField(
            model_name="approvalstep",
            name="responsible_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
