# Generated by Django 2.1.2 on 2019-11-18 22:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0003_auto_20191113_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvaltransition",
            name="button",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="approvaltransition",
            name="order",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="historicalapprovaltransition",
            name="button",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalapprovaltransition",
            name="order",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
