# Generated by Django 2.1.2 on 2019-12-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0004_auto_20191118_1921"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="responsible_created_by",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalapprovalstep",
            name="responsible_created_by",
            field=models.BooleanField(default=False),
        ),
    ]
