# Generated by Django 2.1.2 on 2020-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0005_auto_20191205_1815"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="auto_execute_transition",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalapprovalstep",
            name="auto_execute_transition",
            field=models.BooleanField(default=False),
        ),
    ]
