# Generated by Django 2.1.2 on 2020-04-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0006_auto_20200129_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="responsible_supervisor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalapprovalstep",
            name="responsible_supervisor",
            field=models.BooleanField(default=False),
        ),
    ]
