# Generated by Django 2.1.2 on 2020-05-26 19:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0007_auto_20200430_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="responsible_json_logic",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalapprovalstep",
            name="responsible_json_logic",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
