# Generated by Django 2.1.2 on 2020-11-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("approval_flows", "0008_auto_20200526_1650")]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="responsible_firm_entity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalapprovalstep",
            name="responsible_firm_entity",
            field=models.BooleanField(default=False),
        ),
    ]
