# Generated by Django 2.2.23 on 2021-10-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("approval_flows", "0009_auto_20201105_0351")]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="responsible_firm_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalapprovalstep",
            name="responsible_firm_manager",
            field=models.BooleanField(default=False),
        ),
    ]
