# Generated by Django 2.2.23 on 2022-03-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_dos", "0003_auto_20220326_1757"),
        ("approval_flows", "0010_auto_20210930_2111"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_steps",
                to="to_dos.ToDoAction",
            ),
        ),
        migrations.AddField(
            model_name="historicalapprovalstep",
            name="action",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="to_dos.ToDoAction",
            ),
        ),
    ]
