# Generated by Django 2.2.23 on 2022-03-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0011_auto_20220326_1839"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalapprovalstep",
            name="action",
        ),
        migrations.RemoveField(
            model_name="approvalstep",
            name="action",
        ),
    ]
