# Generated by Django 2.2.23 on 2022-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0012_auto_20220327_1124"),
        ("to_dos", "0004_historicaltodoactionstep_todoactionstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="action",
            field=models.ManyToManyField(
                related_name="approval_steps",
                through="to_dos.ToDoActionStep",
                to="to_dos.ToDoAction",
            ),
        ),
    ]
