# Generated by Django 2.2.23 on 2022-08-29 14:18

from django.db import migrations

import helpers.fields


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0013_approvalstep_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalstep",
            name="color",
            field=helpers.fields.ColorField(default="#FF0000", max_length=18),
        ),
        migrations.AddField(
            model_name="historicalapprovalstep",
            name="color",
            field=helpers.fields.ColorField(default="#FF0000", max_length=18),
        ),
    ]
