# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0014_auto_20220829_1118"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalapprovalflow",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical approval flow",
                "verbose_name_plural": "historical approval flows",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalapprovalstep",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical approval step",
                "verbose_name_plural": "historical approval steps",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalapprovaltransition",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical approval transition",
                "verbose_name_plural": "historical approval transitions",
            },
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="field_options",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="responsible_json_logic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="approvaltransition",
            name="button",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="approvaltransition",
            name="callback",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="approvaltransition",
            name="condition",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalapprovalflow",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalapprovalstep",
            name="field_options",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalapprovalstep",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalapprovalstep",
            name="responsible_json_logic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalapprovaltransition",
            name="button",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalapprovaltransition",
            name="callback",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalapprovaltransition",
            name="condition",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalapprovaltransition",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
