# Generated by Django 2.1.1 on 2018-09-21 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0003_auto_20180921_1017"),
        ("occurrence_records", "0002_auto_20180921_1017"),
        ("service_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="serviceorderaction",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_responsibles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="serviceorderaction",
            name="service_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="service_orders.ServiceOrder",
            ),
        ),
        migrations.AddField(
            model_name="serviceorderaction",
            name="service_order_action_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_status",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="companies.Company"
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="occurrence_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_order",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="procedureresource",
            name="procedure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedure_resources",
                to="service_orders.Procedure",
            ),
        ),
        migrations.AddField(
            model_name="procedureresource",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_procedures",
                to="resources.Resource",
            ),
        ),
        migrations.AddField(
            model_name="procedurefile",
            name="procedure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedure_files",
                to="service_orders.Procedure",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="action",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedures",
                to="service_orders.ServiceOrderAction",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="firm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.Firm",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="occurrence_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="occurrence_records.OccurrenceType",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="procedure_previous",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procedure_next",
                to="service_orders.Procedure",
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="resources",
            field=models.ManyToManyField(
                through="service_orders.ProcedureResource", to="resources.Resource"
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="service_order_action_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceorderactionstatus",
            unique_together={("order", "company")},
        ),
    ]
