# Generated by Django 2.1.1 on 2018-09-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0002_auto_20180921_1017"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderactionstatus",
            name="type",
            field=models.CharField(
                choices=[
                    ("OCCURRENCE_RECORD_STATUS", "OCCURRENCE_RECORD_STATUS"),
                    ("SERVICE_ORDER_STATUS", "SERVICE_ORDER_STATUS"),
                    ("ACTION_STATUS", "ACTION_STATUS"),
                ],
                default="ACTION_STATUS",
                max_length=30,
            ),
        ),
    ]
