# Generated by Django 2.1.1 on 2018-09-24 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_auto_20180921_1017"),
        ("service_orders", "0003_serviceorderactionstatus_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderaction",
            name="firm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.Firm",
            ),
        ),
    ]
