# Generated by Django 2.1.1 on 2018-09-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0004_serviceorderaction_firm"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderaction",
            name="first_action",
            field=models.BooleanField(default=False),
        ),
    ]
