# Generated by Django 2.1.1 on 2018-10-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0004_serviceorderaction_firm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceorderactionstatus",
            old_name="type",
            new_name="kind",
        ),
    ]
