# Generated by Django 2.1.1 on 2018-10-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0005_serviceorderaction_first_action"),
        ("service_orders", "0005_auto_20181004_1318"),
    ]

    operations = []
