# Generated by Django 2.1.2 on 2018-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0006_merge_20181004_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedureresource",
            name="total_price",
            field=models.FloatField(default=0),
        ),
    ]
