# Generated by Django 2.1.2 on 2018-10-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0007_procedureresource_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedureresource",
            name="unit_price",
            field=models.FloatField(default=0),
        ),
    ]
