# Generated by Django 2.1.2 on 2018-11-06 12:01

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0003_occurrencerecord_editable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0008_procedureresource_unit_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalDocument",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(blank=True, default="", max_length=60)),
                ("occurrence_kind", models.CharField(blank=True, max_length=60)),
                (
                    "form_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additinal_documents",
                        to="service_orders.ServiceOrderAction",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="procedure",
            name="aditional_documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedures_mentioned",
                to="service_orders.AdditionalDocument",
            ),
        ),
    ]
