# Generated by Django 2.1.2 on 2018-10-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0008_procedureresource_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorder",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
