# Generated by Django 2.1.2 on 2018-11-06 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0009_auto_20181106_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionaldocument",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_documents",
                to="service_orders.ServiceOrderAction",
            ),
        ),
        migrations.AlterField(
            model_name="additionaldocument",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
