# Generated by Django 2.1.2 on 2018-11-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0010_auto_20181106_1006"),
        ("service_orders", "0009_auto_20181031_1149"),
    ]

    operations = []
