# Generated by Django 2.1.2 on 2018-11-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0011_merge_20181108_1105"),
    ]

    operations = [
        migrations.RenameField(
            model_name="procedure",
            old_name="aditional_documents",
            new_name="additional_documents",
        ),
    ]
