# Generated by Django 2.1.2 on 2018-11-29 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0003_auto_20180921_1017"),
        ("service_orders", "0012_auto_20181109_2013"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedureresource",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="procedureresource",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                    ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                    ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                ],
                default="WAITING_APPROVAL",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="procedureresource",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resource_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="procedureresource",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.Firm",
            ),
        ),
    ]
