# Generated by Django 2.1.2 on 2018-12-11 16:03

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_resource_isextra"),
        ("companies", "0003_auto_20180921_1017"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0013_auto_20181129_0938"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionResource",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                ("unit_price", models.FloatField(default=0)),
                ("remaining_amount", models.FloatField(default=0)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_resources",
                        to="service_orders.ServiceOrderAction",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_resource_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.Firm",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_actions",
                        to="resources.Resource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="procedureresource",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="procedureresource",
            name="action_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actionresource_procedures",
                to="service_orders.ActionResource",
            ),
        ),
    ]
