# Generated by Django 2.1.2 on 2018-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0014_auto_20181211_1403"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedureresource",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="procedureresource",
            name="unit_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
