# Generated by Django 2.1.2 on 2018-12-31 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0015_auto_20181213_1540"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedureresource",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_procedures",
                to="resources.Resource",
            ),
        ),
    ]
