# Generated by Django 2.1.2 on 2019-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0016_auto_20181231_1520"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionaldocument",
            name="number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="additionaldocument",
            name="occurrence_kind",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="occurrence_kind",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="procedureresource",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                    ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                    ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                ],
                default="WAITING_APPROVAL",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="serviceorderaction",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="serviceorderactionstatus",
            name="kind",
            field=models.CharField(
                choices=[
                    ("OCCURRENCE_RECORD_STATUS", "OCCURRENCE_RECORD_STATUS"),
                    ("SERVICE_ORDER_STATUS", "SERVICE_ORDER_STATUS"),
                    ("ACTION_STATUS", "ACTION_STATUS"),
                ],
                default="ACTION_STATUS",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderactionstatus",
            name="name",
            field=models.TextField(),
        ),
    ]
