# Generated by Django 2.1.2 on 2019-01-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0016_auto_20181231_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionresource",
            name="additional_control",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="actionresource",
            name="provider",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="actionresource",
            name="resource_kind",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
