# Generated by Django 2.1.2 on 2019-01-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0017_auto_20190108_1258"),
        ("service_orders", "0017_auto_20190108_1120"),
    ]

    operations = []
