# Generated by Django 2.1.2 on 2019-01-09 12:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_auto_20190108_1258"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0018_merge_20190109_0948"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementBulletin",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("measurement_date", models.DateTimeField()),
                ("total_price", models.FloatField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_bulletins",
                        to="service_orders.ServiceOrderAction",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.Firm",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="procedureresource",
            name="measurement_bulletin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletin_resources",
                to="service_orders.MeasurementBulletin",
            ),
        ),
    ]
