# Generated by Django 2.1.2 on 2019-01-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0019_auto_20190109_1006"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurementbulletin",
            name="measurement_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
