# Generated by Django 2.1.2 on 2019-01-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0020_auto_20190109_1238"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementbulletin",
            name="number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
