# Generated by Django 2.1.2 on 2019-01-19 18:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_auto_20190108_1258"),
        ("resources", "0006_merge_20190109_0947"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0021_measurementbulletin_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceOrderResource",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                ("unit_price", models.FloatField(default=0)),
                ("remaining_amount", models.FloatField(default=0)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("resource_kind", models.CharField(blank=True, max_length=60)),
                ("provider", models.CharField(blank=True, max_length=60)),
                ("additional_control", models.CharField(blank=True, max_length=60)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_order_resource_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.Firm",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_service_orders",
                        to="resources.Resource",
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_order_resources",
                        to="service_orders.ServiceOrder",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="actionresource",
            name="action",
        ),
        migrations.RemoveField(
            model_name="actionresource",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="actionresource",
            name="firm",
        ),
        migrations.RemoveField(
            model_name="actionresource",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="measurementbulletin",
            name="action",
        ),
        migrations.RemoveField(
            model_name="procedureresource",
            name="action_resource",
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="service_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_order_bulletins",
                to="service_orders.ServiceOrder",
            ),
        ),
        migrations.DeleteModel(
            name="ActionResource",
        ),
        migrations.AddField(
            model_name="procedureresource",
            name="service_order_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="serviceorderresource_procedures",
                to="service_orders.ServiceOrderResource",
            ),
        ),
    ]
