# Generated by Django 2.1.2 on 2019-01-20 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0022_auto_20190119_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderresource",
            name="used_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="occurrence_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="occurrence_records.OccurrenceType",
            ),
        ),
    ]
