# Generated by Django 2.1.2 on 2019-01-21 14:37

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_auto_20190108_1258"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0023_auto_20190120_1613"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeInformation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("contract_start", models.DateTimeField(null=True)),
                ("contract_end", models.DateTimeField(null=True)),
                (
                    "extra_info",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.Firm",
                    ),
                ),
                (
                    "service_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_order_administrative_information",
                        to="service_orders.ServiceOrder",
                    ),
                ),
            ],
        ),
    ]
