# Generated by Django 2.1.2 on 2019-01-22 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0024_administrativeinformation"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementbulletin",
            name="administrative_information",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administrative_information_bulletins",
                to="service_orders.AdministrativeInformation",
            ),
        ),
    ]
