# Generated by Django 2.1.2 on 2019-01-22 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0025_measurementbulletin_administrative_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementbulletin",
            name="firm_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="measurementbulletin",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_measurement_bulletins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
