# Generated by Django 2.1.2 on 2019-01-23 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0026_auto_20190122_0002"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurefile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
