# Generated by Django 2.1.2 on 2019-02-04 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0027_procedurefile_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_order_closed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="closed_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="firm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procedure_firm",
                to="companies.Firm",
            ),
        ),
    ]
