# Generated by Django 2.1.2 on 2019-02-06 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0028_auto_20190204_1252"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderresource",
            name="effective_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
