# Generated by Django 2.1.2 on 2019-02-21 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0030_procedureresource_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderaction",
            name="service_order_action_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_status",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
    ]
