# Generated by Django 2.1.2 on 2019-02-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_historicalcompany_historicalfirm_historicaluserincompany"),
        (
            "service_orders",
            "0031_historicaladditionaldocument_historicaladministrativeinformation_historicalmeasurementbulletin_histo",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorderactionstatus",
            name="companies",
            field=models.ManyToManyField(
                related_name="status_companies", to="companies.Company"
            ),
        ),
    ]
