# Generated by Django 2.1.2 on 2019-02-25 21:56

from django.db import migrations, models


def make_many_companies(apps, schema_editor):
    ServiceOrderActionStatus = apps.get_model(
        "service_orders", "ServiceOrderActionStatus"
    )
    for status in ServiceOrderActionStatus.objects.all():
        status.companies.add(status.company)


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0032_serviceorderactionstatus_companies"),
    ]

    operations = [migrations.RunPython(make_many_companies)]
