# Generated by Django 2.1.2 on 2019-02-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0033_auto_20190225_1856"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalserviceorderactionstatus",
            name="company",
        ),
        migrations.AlterUniqueTogether(
            name="serviceorderactionstatus",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="serviceorderactionstatus",
            name="company",
        ),
    ]
