# Generated by Django 2.1.2 on 2019-02-26 18:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0034_auto_20190225_1908"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalserviceorder",
            name="priority",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="priority",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
