# Generated by Django 2.1.2 on 2019-02-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0035_auto_20190226_1511"),
        ("service_orders", "0031_auto_20190221_1411"),
    ]

    operations = []
