# Generated by Django 2.1.2 on 2019-04-04 19:45

from __future__ import unicode_literals

from django.db import migrations, models


def put_through_in_m2m(apps, schema_editor):
    ServiceOrderActionStatusSpecs = apps.get_model(
        "service_orders", "ServiceOrderActionStatusSpecs"
    )
    ServiceOrderActionStatus = apps.get_model(
        "service_orders", "ServiceOrderActionStatus"
    )

    for status in ServiceOrderActionStatus.objects.all():
        for company in status.companies.all():
            ServiceOrderActionStatusSpecs.objects.create(
                status=status, company=company, color="#FF0000"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0038_auto_20190404_1644"),
    ]

    operations = [
        migrations.RunPython(put_through_in_m2m),
    ]
