# Generated by Django 2.1.2 on 2019-04-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0039_auto_20190404_1645"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceorderactionstatus",
            name="companies",
        ),
    ]
