# Generated by Django 2.1.2 on 2019-04-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0040_remove_serviceorderactionstatus_companies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceorderactionstatus",
            old_name="company",
            new_name="companies",
        ),
    ]
