# Generated by Django 2.1.2 on 2019-06-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0041_auto_20190404_1647")]

    operations = [
        migrations.AlterField(
            model_name="measurementbulletin",
            name="firm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firm_measurement_bulletins",
                to="companies.Firm",
            ),
        )
    ]
