# Generated by Django 2.1.2 on 2019-06-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0022_auto_20190514_2005"),
        ("service_orders", "0042_auto_20190610_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalserviceorderactionstatusspecs",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="serviceorderactionstatusspecs",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
