# Generated by Django 2.1.2 on 2019-06-24 20:14

from __future__ import unicode_literals

from django.db import migrations


def move_order_to_specs(apps, schema_editor):
    ServiceOrderActionStatusSpecs = apps.get_model(
        "service_orders", "ServiceOrderActionStatusSpecs"
    )
    ServiceOrderActionStatus = apps.get_model(
        "service_orders", "ServiceOrderActionStatus"
    )

    for status in ServiceOrderActionStatus.objects.all():
        for company in status.companies.all():
            specs = ServiceOrderActionStatusSpecs.objects.filter(
                status=status, company=company
            ).first()
            if specs:
                specs.order = status.order
                specs.save()


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0043_auto_20190624_1714")]

    operations = [migrations.RunPython(move_order_to_specs)]
