# Generated by Django 2.1.2 on 2019-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0044_auto_20190624_1714")]

    operations = [
        migrations.RemoveField(
            model_name="historicalserviceorderactionstatus", name="order"
        ),
        migrations.RemoveField(model_name="serviceorderactionstatus", name="order"),
        migrations.AlterField(
            model_name="historicalserviceorderactionstatusspecs",
            name="order",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="serviceorderactionstatusspecs",
            name="order",
            field=models.IntegerField(),
        ),
    ]
