# Generated by Django 2.1.2 on 2019-06-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0022_auto_20190514_2005"),
        ("service_orders", "0045_auto_20190624_1722"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="serviceorderactionstatusspecs",
            unique_together={("status", "company")},
        )
    ]
