# Generated by Django 2.1.2 on 2019-06-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0046_auto_20190624_1731")]

    operations = [
        migrations.AlterModelOptions(
            name="serviceorderactionstatus",
            options={
                "get_latest_by": ["kind"],
                "verbose_name_plural": "Service Order Statuses",
            },
        )
    ]
