# Generated by Django 2.1.2 on 2019-07-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0023_populate_firm_os_status"),
        ("service_orders", "0047_auto_20190625_1201"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalserviceorder", name="occurrence_record"
        ),
        migrations.RemoveField(model_name="serviceorder", name="occurrence_record"),
    ]
