# Generated by Django 2.1.2 on 2019-07-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0048_auto_20190722_1618"),
        ("resources", "0008_contract_historicalcontract"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativeinformation",
            name="contract",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="administrative_informations",
                to="resources.Contract",
            ),
        ),
        migrations.AddField(
            model_name="administrativeinformation",
            name="responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administrative_informations_responsible",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="administrativeinformation",
            name="spend_limit",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="historicaladministrativeinformation",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resources.Contract",
            ),
        ),
        migrations.AddField(
            model_name="historicaladministrativeinformation",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaladministrativeinformation",
            name="spend_limit",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="historicalmeasurementbulletin",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resources.Contract",
            ),
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletins",
                to="resources.Contract",
            ),
        ),
    ]
