# Generated by Django 2.1.2 on 2019-07-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    AdministrativeInformation = apps.get_model(
        "service_orders", "AdministrativeInformation"
    )
    Contract = apps.get_model("resources", "Contract")
    MeasurementBulletin = apps.get_model("service_orders", "MeasurementBulletin")

    db_alias = schema_editor.connection.alias

    for admin_info in AdministrativeInformation.objects.using(db_alias).all():
        contract = Contract(
            name="{} - {}".format(
                admin_info.firm.name, admin_info.service_order.company.name
            ),
            created_at=admin_info.creation_date,
            contract_start=admin_info.contract_start,
            contract_end=admin_info.contract_end,
            created_by=admin_info.created_by,
            firm=admin_info.firm,
            extra_info=admin_info.extra_info,
        )
        contract.save()

        admin_info.contract = contract
        admin_info.save()

    for bulletin in MeasurementBulletin.objects.using(db_alias).all():
        if bulletin.administrative_information:
            bulletin.contract = bulletin.administrative_information.contract
            bulletin.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0049_auto_20190718_1836"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)
    ]
