# Generated by Django 2.1.2 on 2019-07-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0050_create_contracts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="administrativeinformation",
            old_name="creation_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="historicaladministrativeinformation",
            old_name="creation_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="administrativeinformation", name="contract_end"
        ),
        migrations.RemoveField(
            model_name="administrativeinformation", name="contract_start"
        ),
        migrations.RemoveField(
            model_name="administrativeinformation", name="extra_info"
        ),
        migrations.RemoveField(model_name="administrativeinformation", name="firm"),
        migrations.RemoveField(
            model_name="historicaladministrativeinformation",
            name="contract_end",
        ),
        migrations.RemoveField(
            model_name="historicaladministrativeinformation",
            name="contract_start",
        ),
        migrations.RemoveField(
            model_name="historicaladministrativeinformation", name="extra_info"
        ),
        migrations.RemoveField(
            model_name="historicaladministrativeinformation", name="firm"
        ),
        migrations.RemoveField(
            model_name="historicalmeasurementbulletin",
            name="administrative_information",
        ),
        migrations.RemoveField(
            model_name="measurementbulletin", name="administrative_information"
        ),
        migrations.AlterField(
            model_name="administrativeinformation",
            name="service_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="administrative_informations",
                to="service_orders.ServiceOrder",
            ),
        ),
    ]
