# Generated by Django 2.1.2 on 2019-07-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ServiceOrder = apps.get_model("service_orders", "ServiceOrder")

    db_alias = schema_editor.connection.alias

    delete = ServiceOrder.objects.using(db_alias).filter(number__exact="").delete()

    print("Deleting closed ServiceOrders: ", delete)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0051_auto_20190718_1836"),
        ("files", "0003_copy_first_action_files"),
        ("occurrence_records", "0027_occurrence_record_history"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)
    ]
