# Generated by Django 2.1.2 on 2019-07-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ServiceOrderAction = apps.get_model("service_orders", "ServiceOrderAction")

    db_alias = schema_editor.connection.alias

    delete = (
        ServiceOrderAction.objects.using(db_alias).filter(first_action=True).delete()
    )

    print("Deleting first actions: ", delete)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0052_remove_uncreated_service_orders"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)
    ]
