# Generated by Django 2.1.2 on 2019-07-22 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0053_remove_first_actions")]

    operations = [
        migrations.RemoveField(
            model_name="historicalserviceorderaction", name="first_action"
        ),
        migrations.RemoveField(model_name="serviceorderaction", name="first_action"),
        migrations.AddField(
            model_name="historicalserviceorderaction",
            name="parent_record",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="serviceorderaction",
            name="parent_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="record_actions",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
    ]
