# Generated by Django 2.1.2 on 2019-07-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0008_contract_historicalcontract"),
        ("service_orders", "0054_auto_20190722_1955"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalserviceorderresource",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resources.Contract",
            ),
        ),
        migrations.AddField(
            model_name="serviceorderresource",
            name="contract",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="resources.Contract",
            ),
        ),
    ]
