# Generated by Django 2.1.2 on 2019-07-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ServiceOrderResource = apps.get_model("service_orders", "ServiceOrderResource")
    Contract = apps.get_model("resources", "Contract")

    db_alias = schema_editor.connection.alias

    for resource in ServiceOrderResource.objects.using(db_alias).all():
        try:
            contract = Contract.objects.using(db_alias).get(
                firm=resource.firm, service_orders__in=[resource.service_order]
            )
            resource.contract = contract
            resource.save()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0055_auto_20190723_1406"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)
    ]
