# Generated by Django 2.1.2 on 2019-07-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0056_link_service_order_resource_to_contract")]

    operations = [
        migrations.RemoveField(
            model_name="historicalserviceorderresource", name="firm"
        ),
        migrations.RemoveField(
            model_name="historicalserviceorderresource", name="service_order"
        ),
        migrations.RemoveField(model_name="serviceorderresource", name="firm"),
        migrations.RemoveField(model_name="serviceorderresource", name="service_order"),
    ]
