# Generated by Django 2.1.2 on 2019-07-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0057_auto_20190723_1405"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalserviceorder",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
