# Generated by Django 2.1.2 on 2019-07-31 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0058_auto_20190730_2313"),
        ("occurrence_records", "0028_copy_additional_documents"),
    ]

    operations = [
        migrations.RemoveField(model_name="additionaldocument", name="action"),
        migrations.RemoveField(model_name="additionaldocument", name="created_by"),
        migrations.RemoveField(model_name="additionaldocument", name="occurrence_type"),
        migrations.RemoveField(
            model_name="historicaladditionaldocument", name="action"
        ),
        migrations.RemoveField(
            model_name="historicaladditionaldocument", name="created_by"
        ),
        migrations.RemoveField(
            model_name="historicaladditionaldocument", name="history_user"
        ),
        migrations.RemoveField(
            model_name="historicaladditionaldocument", name="occurrence_type"
        ),
        migrations.RemoveField(model_name="procedure", name="additional_documents"),
        migrations.DeleteModel(name="AdditionalDocument"),
        migrations.DeleteModel(name="HistoricalAdditionalDocument"),
    ]
