# Generated by Django 2.1.2 on 2019-07-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0059_auto_20190731_1839")]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="additional_documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedures_mentioned",
                to="occurrence_records.OccurrenceRecord",
            ),
        )
    ]
