# Generated by Django 2.1.2 on 2019-08-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0060_procedure_additional_documents")]

    operations = [
        migrations.AddField(
            model_name="historicalserviceorderactionstatus",
            name="is_final",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceorderactionstatus",
            name="is_final",
            field=models.BooleanField(default=False),
        ),
    ]
