# Generated by Django 2.1.2 on 2019-08-13 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0061_auto_20190827_1249")]

    operations = [
        migrations.AddField(
            model_name="historicalprocedureresource",
            name="service_order",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.ServiceOrder",
            ),
        ),
        migrations.AddField(
            model_name="procedureresource",
            name="service_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources_service_order",
                to="service_orders.ServiceOrder",
            ),
        ),
        migrations.AlterField(
            model_name="procedureresource",
            name="procedure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedure_resources",
                to="service_orders.Procedure",
            ),
        ),
    ]
