# Generated by Django 2.1.2 on 2019-07-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ProcedureResource = apps.get_model("service_orders", "ProcedureResource")

    db_alias = schema_editor.connection.alias

    for resource in (
        ProcedureResource.objects.using(db_alias)
        .all()
        .prefetch_related("procedure__action__service_order")
    ):
        try:
            service_order = resource.procedure.action.service_order
            resource.service_order = service_order
            resource.save()
        except Exception as e:
            print("couldn't find service_order to fill procedure_resource", str(e))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0062_auto_20190813_1613"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)
    ]
