# Generated by Django 2.1.2 on 2019-08-13 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0063_link_procedure_resource_to_service_order")]

    operations = [
        migrations.RemoveField(
            model_name="historicalmeasurementbulletin", name="service_order"
        ),
        migrations.RemoveField(model_name="measurementbulletin", name="service_order"),
    ]
