# Generated by Django 2.1.2 on 2019-10-11 03:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0064_auto_20190813_1613"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmeasurementbulletin",
            name="extra_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="extra_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
    ]
