# Generated by Django 2.1.2 on 2019-11-29 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0065_auto_20191011_0047")]

    operations = [
        migrations.AlterField(
            model_name="procedureresource",
            name="service_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources_service_order",
                to="service_orders.ServiceOrder",
            ),
        )
    ]
