# Generated by Django 2.1.2 on 2019-12-10 19:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0067_auto_20191209_2001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalserviceorder",
            name="canvas_layout",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="canvas_layout",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
    ]
