# Generated by Django 2.1.2 on 2020-01-14 18:14

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def copy_field(apps, schema_editor):
    ProcedureFile = apps.get_model("service_orders", "ProcedureFile")
    ProcedureFile.objects.all().update(datetime=F("uploaded_at"))
    HistoricalProcedureFile = apps.get_model(
        "service_orders", "HistoricalProcedureFile"
    )
    HistoricalProcedureFile.objects.all().update(datetime=F("uploaded_at"))


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0068_auto_20191210_1600")]

    operations = [
        migrations.AddField(
            model_name="historicalprocedurefile",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="procedurefile",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(copy_field, reverse_code=migrations.RunPython.noop),
    ]
