# Generated by Django 2.1.2 on 2020-01-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0068_auto_20191210_1600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderresource",
            name="resource",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_service_orders",
                to="resources.Resource",
            ),
        ),
    ]
