# Generated by Django 2.1.2 on 2020-01-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0069_auto_20200114_1514"),
        ("service_orders", "0069_auto_20200107_0928"),
    ]

    operations = []
