# Generated by Django 2.1.2 on 2020-01-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0070_merge_20200116_1132"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurefile",
            name="procedures",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedure_files_m2m",
                to="service_orders.Procedure",
            ),
        ),
    ]
