# Generated by Django 2.1.2 on 2020-01-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0072_migrate_procedurefile_m2m"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprocedurefile",
            name="procedure",
        ),
        migrations.RemoveField(
            model_name="procedurefile",
            name="procedure",
        ),
    ]
