# Generated by Django 2.1.2 on 2020-01-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0073_auto_20200117_1617"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedurefile",
            name="procedures",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedure_files",
                to="service_orders.Procedure",
            ),
        ),
    ]
