# Generated by Django 2.1.2 on 2020-02-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0074_auto_20200127_1754"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalserviceorderactionstatus",
            name="kind",
            field=models.CharField(
                choices=[
                    ("OCCURRENCE_RECORD_STATUS", "OCCURRENCE_RECORD_STATUS"),
                    ("SERVICE_ORDER_STATUS", "SERVICE_ORDER_STATUS"),
                    ("ACTION_STATUS", "ACTION_STATUS"),
                    ("REPORTING_STATUS", "REPORTING_STATUS"),
                    ("CONTRACT_STATUS", "CONTRACT_STATUS"),
                ],
                default="ACTION_STATUS",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderactionstatus",
            name="kind",
            field=models.CharField(
                choices=[
                    ("OCCURRENCE_RECORD_STATUS", "OCCURRENCE_RECORD_STATUS"),
                    ("SERVICE_ORDER_STATUS", "SERVICE_ORDER_STATUS"),
                    ("ACTION_STATUS", "ACTION_STATUS"),
                    ("REPORTING_STATUS", "REPORTING_STATUS"),
                    ("CONTRACT_STATUS", "CONTRACT_STATUS"),
                ],
                default="ACTION_STATUS",
                max_length=100,
            ),
        ),
    ]
