# Generated by Django 2.1.2 on 2020-03-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0075_auto_20200207_1604")]

    operations = [
        migrations.AddField(
            model_name="historicalmeasurementbulletin",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
