# Generated by Django 2.1.2 on 2020-04-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0076_auto_20200317_2355")]

    operations = [
        migrations.AddField(
            model_name="historicalprocedurefile",
            name="md5",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="procedurefile",
            name="md5",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalprocedurefile",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
