# Generated by Django 2.1.2 on 2019-07-18 21:36

from django.conf import settings
from django.db import migrations
from tqdm import tqdm


def forwards_func(apps, schema_editor):
    ProcedureFile = apps.get_model("service_orders", "ProcedureFile")

    db_alias = schema_editor.connection.alias

    existing_files = ProcedureFile.objects.using(db_alias).all()

    for file in tqdm(existing_files):
        md5 = file.upload.storage.e_tag(file.upload.name).strip('"')
        file.md5 = md5
        file.changeReason = (
            "Auto-adding md5 from AWS S3 in apps.service_orders.migrations.0078"
        )
        file.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0077_auto_20200406_1840"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)
    ]
