# Generated by Django 2.1.2 on 2020-04-15 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0018_fill_md5_from_aws_s3"),
        ("service_orders", "0078_fill_md5_from_aws_s3"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprocedureresource",
            name="reporting",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="reportings.Reporting",
            ),
        ),
        migrations.AddField(
            model_name="procedureresource",
            name="reporting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reporting_resources",
                to="reportings.Reporting",
            ),
        ),
    ]
