# Generated by Django 2.1.2 on 2020-04-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0006_auto_20200129_1453"),
        (
            "service_orders",
            "0079_historicalserviceorderwatcher_serviceorderwatcher",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmeasurementbulletin",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="approval_flows.ApprovalStep",
            ),
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_bulletins",
                to="approval_flows.ApprovalStep",
            ),
        ),
    ]
