# Generated by Django 2.1.2 on 2020-04-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0079_auto_20200415_0901"),
        ("service_orders", "0080_auto_20200406_1511"),
    ]

    operations = []
