# Generated by Django 2.1.2 on 2020-06-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0081_merge_20200428_0025"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmeasurementbulletin",
            name="editable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="editable",
            field=models.BooleanField(default=True),
        ),
    ]
