# Generated by Django 2.1.2 on 2020-06-10 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0082_auto_20200610_0914"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="responsibles",
            field=models.ManyToManyField(
                blank=True,
                related_name="responsibles_service_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
