# Generated by Django 2.1.2 on 2020-07-17 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0083_serviceorder_responsibles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedureresource",
            name="reporting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reporting_resources",
                to="reportings.Reporting",
            ),
        ),
    ]
