# Generated by Django 2.1.2 on 2020-11-05 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0036_auto_20201105_0037"),
        ("service_orders", "0084_auto_20200717_1327"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalserviceorder",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.Entity",
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_orders",
                to="companies.Entity",
            ),
        ),
    ]
