# Generated by Django 2.1.2 on 2020-11-17 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0009_auto_20190809_1341"),
        ("service_orders", "0085_auto_20201105_0206"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalserviceorder",
            name="other_reference",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalserviceorder",
            name="place_on_dam",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="historicalserviceorder",
            name="uf_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="city",
            field=models.ManyToManyField(
                blank=True,
                related_name="city_service_orders",
                to="locations.City",
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="location",
            field=models.ManyToManyField(
                blank=True,
                related_name="location_service_orders",
                to="locations.Location",
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="other_reference",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="place_on_dam",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="river",
            field=models.ManyToManyField(
                blank=True,
                related_name="river_service_orders",
                to="locations.River",
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="uf_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
