# Generated by Django 2.1.2 on 2020-11-24 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0037_auto_20201105_1738"),
        ("service_orders", "0086_auto_20201117_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalserviceorderresource",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.Entity",
            ),
        ),
        migrations.AddField(
            model_name="serviceorderresource",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_order_resources",
                to="companies.Entity",
            ),
        ),
    ]
