# Generated by Django 2.1.2 on 2019-07-18 21:36

from django.db import migrations
from fnc.mappings import get
from fnc.sequences import find
from tqdm import tqdm


def forwards_func(apps, schema_editor):
    ServiceOrderResource = apps.get_model("service_orders", "ServiceOrderResource")
    Entity = apps.get_model("companies", "Entity")

    db_alias = schema_editor.connection.alias

    existing_resources = (
        ServiceOrderResource.objects.using(db_alias)
        .all()
        .prefetch_related("contract__firm__company")
    )

    for resource in tqdm(existing_resources):
        company = (
            resource.contract.firm.company
            if resource.contract and resource.contract.firm
            else None
        )
        if not company or resource.provider == "":
            continue

        provider_options = get(
            "serviceOrderResource.fields.provider.selectOptions.options",
            company.custom_options,
        )
        provider_object = find(
            lambda x: x["value"] == resource.provider, provider_options
        )
        provider_name = provider_object["name"]

        entity = Entity.objects.filter(
            company=company, name__icontains=provider_name
        ).first()
        if not entity:
            entity = Entity.objects.create(company=company, name=provider_name)

        resource.entity = entity
        resource.save()


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0087_auto_20201123_2244")]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)
    ]
