# Generated by Django 2.1.2 on 2020-11-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0088_fill_service_order_resource_entity")]

    operations = [
        migrations.RemoveField(
            model_name="historicalserviceorderresource", name="provider"
        ),
        migrations.RemoveField(model_name="serviceorderresource", name="provider"),
    ]
