# Generated by Django 2.1.2 on 2020-11-24 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0089_auto_20201123_2259"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managers_service_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
