# Generated by Django 2.1.2 on 2021-02-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0090_serviceorder_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalserviceorder",
            name="kind",
            field=models.CharField(
                choices=[("ENVIRONMENT", "ENVIRONMENT"), ("LAND", "LAND")],
                default="ENVIRONMENT",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalserviceorder",
            name="process_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="historicalserviceorder",
            name="shape_file_property",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="kind",
            field=models.CharField(
                choices=[("ENVIRONMENT", "ENVIRONMENT"), ("LAND", "LAND")],
                default="ENVIRONMENT",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="process_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="shape_file_property",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
