# Generated by Django 2.1.2 on 2021-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0091_auto_20210211_0816"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalserviceorderaction",
            name="estimated_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceorderaction",
            name="estimated_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
