# Generated by Django 2.1.2 on 2021-06-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0092_auto_20210219_1548"),
    ]

    operations = [
        migrations.RenameField(
            model_name="procedure",
            old_name="additional_documents",
            new_name="occurrence_records",
        ),
    ]
