# Generated by Django 2.2.23 on 2022-02-17 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0093_auto_20210601_1514")]

    operations = [
        migrations.AlterField(
            model_name="historicalprocedureresource",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="procedureresource",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
