# Generated by Django 2.2.23 on 2022-02-18 16:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps import service_orders
from helpers.strings import get_obj_from_path

""""
fill the "AdditionalControl" model with the data from the filed
"additional_control" from the "ServiceOrderResource" model
"""


def fill_additional_control_model(apps, schema_editor):
    order_resource_model = apps.get_model("service_orders", "ServiceOrderResource")
    additional_control_model = apps.get_model("service_orders", "AdditionalControl")
    companies_model = apps.get_model("companies", "Company")

    for company in companies_model.objects.all():
        custom_options = company.custom_options
        additional_control_options = get_obj_from_path(
            custom_options,
            "serviceorderresource__fields__additionalcontrol__selectoptions__options",
        )

        for option in additional_control_options:
            additional_control_obj = additional_control_model.objects.create(
                name=option["name"],
                company=company,
            )
            order_resource_model.objects.filter(
                contract__firm__company=company, additional_control=option["value"]
            ).update(additional_control_model=additional_control_obj)


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0053_merge_20220210_0019"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0093_auto_20210601_1514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalserviceorderresource",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resources.Resource",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderresource",
            name="resource",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_service_orders",
                to="resources.Resource",
            ),
        ),
        migrations.CreateModel(
            name="AdditionalControl",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(default=None, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_controls",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="additional_controls_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historicalserviceorderresource",
            name="additional_control_model",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.AdditionalControl",
            ),
        ),
        migrations.AddField(
            model_name="serviceorderresource",
            name="additional_control_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="additional_controls",
                to="service_orders.AdditionalControl",
            ),
        ),
        migrations.RunPython(fill_additional_control_model),
    ]
