# Generated by Django 2.2.23 on 2022-02-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0093_auto_20210601_1514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalserviceorderactionstatus",
            name="kind",
            field=models.CharField(
                choices=[
                    ("OCCURRENCE_RECORD_STATUS", "OCCURRENCE_RECORD_STATUS"),
                    ("SERVICE_ORDER_STATUS", "SERVICE_ORDER_STATUS"),
                    ("ACTION_STATUS", "ACTION_STATUS"),
                    ("REPORTING_STATUS", "REPORTING_STATUS"),
                    ("CONTRACT_STATUS", "CONTRACT_STATUS"),
                    ("MONITORING_STATUS", "MONITORING_STATUS"),
                ],
                default="ACTION_STATUS",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderactionstatus",
            name="kind",
            field=models.CharField(
                choices=[
                    ("OCCURRENCE_RECORD_STATUS", "OCCURRENCE_RECORD_STATUS"),
                    ("SERVICE_ORDER_STATUS", "SERVICE_ORDER_STATUS"),
                    ("ACTION_STATUS", "ACTION_STATUS"),
                    ("REPORTING_STATUS", "REPORTING_STATUS"),
                    ("CONTRACT_STATUS", "CONTRACT_STATUS"),
                    ("MONITORING_STATUS", "MONITORING_STATUS"),
                ],
                default="ACTION_STATUS",
                max_length=100,
            ),
        ),
    ]
