# Generated by Django 2.2.23 on 2022-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0094_auto_20220217_1007")]

    operations = [
        migrations.AddField(
            model_name="historicalmeasurementbulletin",
            name="period_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmeasurementbulletin",
            name="period_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmeasurementbulletin",
            name="work_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="period_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="period_starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="work_day",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
