# Generated by Django 2.2.23 on 2022-04-01 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0094_auto_20220217_1007")]

    operations = [
        migrations.AddField(
            model_name="historicalprocedureresource",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                default="00000db3-a561-4387-ac47-d48fca2d6c24",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="history_procedure_resources",
                to="service_orders.ProcedureResource",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalprocedureresource",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
