# Generated by Django 2.2.23 on 2022-05-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0094_auto_20220202_1631"),
        ("service_orders", "0094_auto_20220217_1007"),
    ]

    operations = []
