# Generated by Django 2.2.23 on 2022-04-01 10:28

from django.db import migrations
from django.db.models import F


def copy_value_to_related_name_procedure_resource(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    HistoricalProcedureResource = apps.get_model(
        "service_orders", "HistoricalProcedureResource"
    )

    HistoricalProcedureResource.objects.using(db_alias).all().update(
        history_relation=F("uuid")
    )


class Migration(migrations.Migration):

    dependencies = [("service_orders", "0095_auto_20220401_0719")]

    operations = [
        migrations.RunPython(
            copy_value_to_related_name_procedure_resource,
            migrations.RunPython.noop,
        )
    ]
