# Generated by Django 2.2.23 on 2022-04-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0095_auto_20220308_1513"),
        ("service_orders", "0094_auto_20220218_1334"),
    ]

    operations = []
