# Generated by Django 2.2.23 on 2022-04-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0096_merge_20220405_1342"),
        ("service_orders", "0096_auto_20220401_0728"),
    ]

    operations = []
