# Generated by Django 2.2.23 on 2022-04-08 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0097_merge_20220414_0513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceorderresource",
            name="additional_control_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_order_resources",
                to="service_orders.AdditionalControl",
            ),
        ),
    ]
