# Generated by Django 2.2.23 on 2022-07-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0095_merge_20220521_1739"),
        ("service_orders", "0098_auto_20220408_1343"),
    ]

    operations = []
