# Generated by Django 2.2.28 on 2023-11-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service_orders",
            "0100_historicalpendingproceduresexport_pendingproceduresexport",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalserviceorderactionstatus",
            name="kind",
            field=models.CharField(
                choices=[
                    ("OCCURRENCE_RECORD_STATUS", "OCCURRENCE_RECORD_STATUS"),
                    ("SERVICE_ORDER_STATUS", "SERVICE_ORDER_STATUS"),
                    ("ACTION_STATUS", "ACTION_STATUS"),
                    ("REPORTING_STATUS", "REPORTING_STATUS"),
                    ("CONTRACT_STATUS", "CONTRACT_STATUS"),
                    ("MONITORING_STATUS", "MONITORING_STATUS"),
                    ("LAND_SERVICE_PROGRESS", "LAND_SERVICE_PROGRESS"),
                    ("LAND_SERVICE_CONCLUSION", "LAND_SERVICE_CONCLUSION"),
                    (
                        "ENVIRONMENTAL_SERVICE_PROGRESS",
                        "ENVIRONMENTAL_SERVICE_PROGRESS",
                    ),
                    (
                        "ENVIRONMENTAL_SERVICE_CONCLUSION",
                        "ENVIRONMENTAL_SERVICE_CONCLUSION",
                    ),
                ],
                default="ACTION_STATUS",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="serviceorderactionstatus",
            name="kind",
            field=models.CharField(
                choices=[
                    ("OCCURRENCE_RECORD_STATUS", "OCCURRENCE_RECORD_STATUS"),
                    ("SERVICE_ORDER_STATUS", "SERVICE_ORDER_STATUS"),
                    ("ACTION_STATUS", "ACTION_STATUS"),
                    ("REPORTING_STATUS", "REPORTING_STATUS"),
                    ("CONTRACT_STATUS", "CONTRACT_STATUS"),
                    ("MONITORING_STATUS", "MONITORING_STATUS"),
                    ("LAND_SERVICE_PROGRESS", "LAND_SERVICE_PROGRESS"),
                    ("LAND_SERVICE_CONCLUSION", "LAND_SERVICE_CONCLUSION"),
                    (
                        "ENVIRONMENTAL_SERVICE_PROGRESS",
                        "ENVIRONMENTAL_SERVICE_PROGRESS",
                    ),
                    (
                        "ENVIRONMENTAL_SERVICE_CONCLUSION",
                        "ENVIRONMENTAL_SERVICE_CONCLUSION",
                    ),
                ],
                default="ACTION_STATUS",
                max_length=100,
            ),
        ),
    ]
