# Generated by Django 2.2.28 on 2023-11-08 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0101_auto_20231107_1550"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalserviceorder",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_service_order",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
    ]
