# Generated by Django 2.2.28 on 2024-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0102_auto_20231108_1249"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprocedure",
            name="forward_to_judiciary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalserviceorder",
            name="identificador",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalserviceorder",
            name="obra",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalserviceorder",
            name="offender_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalserviceorder",
            name="sequencial",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalserviceorderaction",
            name="allow_forwarding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="procedure",
            name="forward_to_judiciary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="identificador",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="obra",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="offender_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="serviceorder",
            name="sequencial",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="serviceorderaction",
            name="allow_forwarding",
            field=models.BooleanField(default=False),
        ),
    ]
