# Generated by Django 2.2.28 on 2024-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0104_sync_new_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalPendingProceduresExport",
        ),
    ]
