# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0105_delete_historicalpendingproceduresexport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaladministrativeinformation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical administrative information",
                "verbose_name_plural": "historical administrative informations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmeasurementbulletin",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical measurement bulletin",
                "verbose_name_plural": "historical measurement bulletins",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprocedure",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical procedure",
                "verbose_name_plural": "historical procedures",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprocedurefile",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical procedure file",
                "verbose_name_plural": "historical procedure files",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprocedureresource",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical procedure resource",
                "verbose_name_plural": "historical procedure resources",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalserviceorder",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical service order",
                "verbose_name_plural": "historical service orders",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalserviceorderaction",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical service order action",
                "verbose_name_plural": "historical service order actions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalserviceorderactionstatus",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical service order action status",
                "verbose_name_plural": "historical Service Order Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalserviceorderactionstatusspecs",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical service order action status specs",
                "verbose_name_plural": "historical service order action status specss",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalserviceorderresource",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical service order resource",
                "verbose_name_plural": "historical service order resources",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalserviceorderwatcher",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical service order watcher",
                "verbose_name_plural": "historical service order watchers",
            },
        ),
        migrations.AlterField(
            model_name="historicaladministrativeinformation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmeasurementbulletin",
            name="extra_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalmeasurementbulletin",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprocedure",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalprocedure",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprocedurefile",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprocedureresource",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalserviceorder",
            name="canvas_layout",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicalserviceorder",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalserviceorder",
            name="priority",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalserviceorderaction",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalserviceorderactionstatus",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalserviceorderactionstatus",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalserviceorderactionstatusspecs",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalserviceorderresource",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalserviceorderwatcher",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="measurementbulletin",
            name="extra_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="pendingproceduresexport",
            name="filters",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="canvas_layout",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="priority",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="serviceorderactionstatus",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
