# Generated by Django 3.2.25 on 2025-05-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0106_auto_20250227_1243"),
        ("service_orders", "0106_recalculate_total_price_based_on_work_day"),
    ]

    operations = []
