# Generated by Django 3.2.25 on 2025-11-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0107_merge_20250507_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmeasurementbulletin",
            name="identification_bulletin",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="identification_bulletin",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
