# Generated by Django 3.2.25 on 2025-11-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0075_merge_0074_auto_20250604_1735_0074_auto_20250909_1951"),
        ("service_orders", "0107_merge_20250507_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmeasurementbulletin",
            name="is_processing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="is_processing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="measurementbulletin",
            name="related_firms",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_bulletins_from_firm",
                to="companies.Firm",
            ),
        ),
    ]
