# Generated by Django 3.2.25 on 2025-11-05 17:13

from django.db import migrations
from django.db.models import Q
from tqdm import tqdm


def populate_related_firms_field(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Company = apps.get_model("companies", "Company")
    MeasurementBulletin = apps.get_model("service_orders", "MeasurementBulletin")
    Firm = apps.get_model("companies", "Firm")
    company_qs = Company.objects.using(db_alias).all()

    for company in tqdm(company_qs):
        bulletins_instances = (
            MeasurementBulletin.objects.filter(
                Q(contract__firm__company=company)
                | Q(contract__subcompany__company=company)
            )
            .prefetch_related(
                "bulletin_resources",
                "bulletin_workers",
                "bulletin_vehicles",
                "bulletin_equipments",
            )
            .distinct()
        )
        for bulletin_instance in bulletins_instances:
            reporting_firms = list(
                bulletin_instance.bulletin_resources.values_list(
                    "reporting__firm_id", flat=True
                )
            )

            workers_firms = list(
                bulletin_instance.bulletin_workers.values_list(
                    "multiple_daily_reports__firm_id", flat=True
                )
            )
            vehicles_firms = list(
                bulletin_instance.bulletin_vehicles.values_list(
                    "multiple_daily_reports__firm_id", flat=True
                )
            )
            equipments_firms = list(
                bulletin_instance.bulletin_equipments.values_list(
                    "multiple_daily_reports__firm_id", flat=True
                )
            )

            firm_list = list(
                filter(
                    None,
                    set(
                        reporting_firms
                        + workers_firms
                        + equipments_firms
                        + vehicles_firms
                    ),
                )
            )
            ordered_firms = (
                Firm.objects.using(db_alias).filter(uuid__in=firm_list).order_by("name")
            )

            bulletin_instance.related_firms.set(ordered_firms)


def reverse_populate_related_firms_field(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Company = apps.get_model("companies", "Company")
    MeasurementBulletin = apps.get_model("service_orders", "MeasurementBulletin")
    company_qs = Company.objects.using(db_alias).all()

    for company in tqdm(company_qs):
        bulletins_instances = MeasurementBulletin.objects.filter(
            Q(contract__firm__company=company)
            | Q(contract__subcompany__company=company)
        ).distinct()
        for bulletin_instance in bulletins_instances:
            bulletin_instance.related_firms.set([])


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0108_auto_20251105_1011"),
    ]

    operations = [
        migrations.RunPython(
            populate_related_firms_field,
            reverse_code=reverse_populate_related_firms_field,
        )
    ]
