# Generated by Django 3.2.25 on 2025-11-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0108_auto_20251105_1153"),
        ("service_orders", "0109_auto_20251105_1413"),
    ]

    operations = []
