# Generated by Django 2.1.2 on 2021-05-13 12:16

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0040_auto_20210314_2321"),
    ]

    operations = [
        migrations.CreateModel(
            name="Construction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("location", models.TextField()),
                ("km", models.FloatField()),
                ("end_km", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scheduling_start_date", models.DateTimeField()),
                ("scheduling_end_date", models.DateTimeField()),
                ("analysis_start_date", models.DateTimeField()),
                ("analysis_end_date", models.DateTimeField()),
                ("execution_start_date", models.DateTimeField()),
                ("execution_end_date", models.DateTimeField()),
                ("spend_schedule_start_date", models.DateTimeField()),
                ("spend_schedule_end_date", models.DateTimeField()),
                (
                    "phases",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "spend_schedule",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_constructions",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_constructions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["company"]},
        ),
        migrations.CreateModel(
            name="HistoricalConstruction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("location", models.TextField()),
                ("km", models.FloatField()),
                ("end_km", models.FloatField()),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                ("scheduling_start_date", models.DateTimeField()),
                ("scheduling_end_date", models.DateTimeField()),
                ("analysis_start_date", models.DateTimeField()),
                ("analysis_end_date", models.DateTimeField()),
                ("execution_start_date", models.DateTimeField()),
                ("execution_end_date", models.DateTimeField()),
                ("spend_schedule_start_date", models.DateTimeField()),
                ("spend_schedule_end_date", models.DateTimeField()),
                (
                    "phases",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "spend_schedule",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical construction",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
