# Generated by Django 2.1.2 on 2021-05-13 19:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("constructions", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="construction",
            name="phases",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalconstruction",
            name="phases",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
    ]
