# Generated by Django 2.2.23 on 2021-07-07 13:27

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reportings", "0041_auto_20210702_1042"),
        ("constructions", "0002_auto_20210513_1632"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionProgress",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "progress_details",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "construction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="construction_progresses",
                        to="constructions.Construction",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_construction_progresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reportings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reporting_construction_progresses",
                        to="reportings.Reporting",
                    ),
                ),
            ],
            options={"ordering": ["construction__company"]},
        )
    ]
