# Generated by Django 2.2.23 on 2021-07-07 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("constructions", "0003_constructionprogress")]

    operations = [
        migrations.AlterField(
            model_name="construction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="historicalconstruction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
