# Generated by Django 2.2.23 on 2022-01-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constructions", "0004_auto_20210707_1137"),
    ]

    operations = [
        migrations.AddField(
            model_name="construction",
            name="construction_item",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="construction",
            name="intervention_type",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalconstruction",
            name="construction_item",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalconstruction",
            name="intervention_type",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
