# Generated by Django 2.2.23 on 2022-09-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constructions", "0005_auto_20220113_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="construction",
            name="origin",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="historicalconstruction",
            name="origin",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
