# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constructions", "0006_auto_20220902_0133"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalconstruction",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical construction",
                "verbose_name_plural": "historical constructions",
            },
        ),
        migrations.AlterField(
            model_name="construction",
            name="phases",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="construction",
            name="spend_schedule",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="constructionprogress",
            name="progress_details",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicalconstruction",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalconstruction",
            name="phases",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicalconstruction",
            name="spend_schedule",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
