EXECUTOR = "EXECUTOR"
INSPECTION = "INSPECTION"

OCCURRENCE_ORIGIN_CHOICES = [(EXECUTOR, EXECUTOR), (INSPECTION, INSPECTION)]

TRANSLATE_OCCURRENCE_ORIGIN_CHOICES = [
    {"name": "Executora", "value": EXECUTOR},
    {"name": "Fiscalização", "value": INSPECTION},
]
