WAITING_APPROVAL = "WAITING_APPROVAL"
APPROVED_APPROVAL = "APPROVED_APPROVAL"
DENIED_APPROVAL = "DENIED_APPROVAL"


APPROVAL_STATUS_CHOICES = [
    (WAITING_APPROVAL, WAITING_APPROVAL),
    (APPROVED_APPROVAL, APPROVED_APPROVAL),
    (DENIED_APPROVAL, DENIED_APPROVAL),
]
