OCCURRENCE_RECORD_STATUS = "OCCURRENCE_RECORD_STATUS"
SERVICE_ORDER_STATUS = "SERVICE_ORDER_STATUS"
ACTION_STATUS = "ACTION_STATUS"
REPORTING_STATUS = "REPORTING_STATUS"
CONTRACT_STATUS = "CONTRACT_STATUS"
MONITORING_STATUS = "MONITORING_STATUS"
LAND_SERVICE_PROGRESS = "LAND_SERVICE_PROGRESS"
LAND_SERVICE_CONCLUSION = "LAND_SERVICE_CONCLUSION"
ENVIRONMENTAL_SERVICE_PROGRESS = "ENVIRONMENTAL_SERVICE_PROGRESS"
ENVIRONMENTAL_SERVICE_CONCLUSION = "ENVIRONMENTAL_SERVICE_CONCLUSION"

STATUS_TYPE_CHOICES = [
    (OCCURRENCE_RECORD_STATUS, OCCURRENCE_RECORD_STATUS),
    (SERVICE_ORDER_STATUS, SERVICE_ORDER_STATUS),
    (ACTION_STATUS, ACTION_STATUS),
    (REPORTING_STATUS, REPORTING_STATUS),
    (CONTRACT_STATUS, CONTRACT_STATUS),
    (MONITORING_STATUS, MONITORING_STATUS),
    (LAND_SERVICE_PROGRESS, LAND_SERVICE_PROGRESS),
    (LAND_SERVICE_CONCLUSION, LAND_SERVICE_CONCLUSION),
    (ENVIRONMENTAL_SERVICE_PROGRESS, ENVIRONMENTAL_SERVICE_PROGRESS),
    (ENVIRONMENTAL_SERVICE_CONCLUSION, ENVIRONMENTAL_SERVICE_CONCLUSION),
]
