# Generated by Django 2.1.2 on 2019-10-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltilelayer",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="tilelayer",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
