# Generated by Django 2.1.2 on 2019-10-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_auto_20191023_1622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalshapefile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="shapefile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
