# Generated by Django 2.1.2 on 2019-11-06 13:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_auto_20191023_1953"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltilelayer",
            name="url",
        ),
        migrations.RemoveField(
            model_name="tilelayer",
            name="url",
        ),
        migrations.AddField(
            model_name="historicaltilelayer",
            name="provider_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="tilelayer",
            name="provider_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
    ]
