# Generated by Django 2.1.2 on 2019-11-21 21:04

import datetime

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0005_auto_20191106_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalshapefile",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="historicalshapefile",
            name="synced_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="shapefile",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="shapefile",
            name="synced_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
