# Generated by Django 2.1.2 on 2020-03-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0006_auto_20191121_1804"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalshapefile",
            name="enable_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shapefile",
            name="enable_default",
            field=models.BooleanField(default=False),
        ),
    ]
