# Generated by Django 2.1.2 on 2020-04-07 13:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0007_auto_20200311_0918"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltilelayer",
            name="mapbox_styles",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="tilelayer",
            name="mapbox_styles",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
    ]
