# Generated by Django 2.1.2 on 2020-04-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0008_auto_20200407_1009"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalshapefile",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalshapefile",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalshapefile",
            name="parent",
        ),
        migrations.DeleteModel(
            name="HistoricalShapeFile",
        ),
    ]
