# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0009_auto_20200430_0820"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaltilelayer",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical tile layer",
                "verbose_name_plural": "historical tile layers",
            },
        ),
        migrations.AlterField(
            model_name="historicaltilelayer",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltilelayer",
            name="mapbox_styles",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicaltilelayer",
            name="provider_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="shapefile",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="shapefile",
            name="properties",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="tilelayer",
            name="mapbox_styles",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="tilelayer",
            name="provider_info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
