# Meant to debug tests without poluting the terminal every time with coverage fluff
# Usage `pytest -c pytest-clean.ini <file>`
[pytest]
DJANGO_SETTINGS_MODULE=RoadLabsAPI.settings.testing_local
addopts = --durations=10 -v --nomigrations -p no:warnings --json-report --json-report-file=report-test.json