SERIES_KIND = "SERIES"
LOGIC_KIND = "LOGIC"
SIH_KIND = "SIH"
SIH_LAST_VALUE_KIND = "SIH_LAST_VALUE"

DATA_SERIES_KINDS = [
    (SERIES_KIND, SERIES_KIND),
    (LOGIC_KIND, LOGIC_KIND),
    (SIH_KIND, SIH_KIND),
    (SIH_LAST_VALUE_KIND, SIH_LAST_VALUE_KIND),
]
