# Generated by Django 2.1.1 on 2018-09-21 13:17

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import helpers.validators.brazilian_documents
import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("active", models.BooleanField(default=None)),
                (
                    "cnpj",
                    models.CharField(
                        max_length=30,
                        validators=[
                            helpers.validators.brazilian_documents.validate_CNPJ
                        ],
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                        upload_to="companies-logos/",
                    ),
                ),
                (
                    "custom_options",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "metadata",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Firm",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                (
                    "cnpj",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[
                            helpers.validators.brazilian_documents.validate_CNPJ
                        ],
                    ),
                ),
                ("is_company_team", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                        upload_to="companies-logos/",
                    ),
                ),
                (
                    "custom_options",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "metadata",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["company"],
            },
        ),
        migrations.CreateModel(
            name="UserInCompany",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                ("level", models.IntegerField(default=2)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.Company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Users in companies",
                "ordering": ["company"],
            },
        ),
    ]
