# Generated by Django 2.1.1 on 2018-09-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userincompany",
            name="permissions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="permissions.UserPermission",
            ),
        ),
    ]
