# Generated by Django 2.1.2 on 2019-01-08 14:58

from django.db import migrations, models

import helpers.validators.brazilian_documents


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_auto_20180921_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="cnpj",
            field=models.CharField(
                max_length=50,
                validators=[helpers.validators.brazilian_documents.validate_CNPJ],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="firm",
            name="cnpj",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[helpers.validators.brazilian_documents.validate_CNPJ],
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="name",
            field=models.CharField(default="", max_length=300),
        ),
    ]
