# Generated by Django 2.1.2 on 2019-01-22 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_auto_20190108_1258"),
        ("companies", "0004_auto_20190108_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="city",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.City",
            ),
        ),
        migrations.AddField(
            model_name="firm",
            name="street_address",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
