# Generated by Django 2.1.2 on 2019-01-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_auto_20190122_0016"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="street_address",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
