# Generated by Django 2.1.2 on 2019-01-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_auto_20190122_0016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userincompany",
            name="permissions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permission_memberships",
                to="permissions.UserPermission",
            ),
        ),
    ]
