# Generated by Django 2.1.2 on 2019-02-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_auto_20190124_1223"),
        ("companies", "0006_company_street_address"),
    ]

    operations = []
