# Generated by Django 2.1.2 on 2019-03-07 14:36

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0009_historicalcompany_historicalfirm_historicaluserincompany"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipments",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(default="", max_length=300)),
                ("plate", models.CharField(blank=True, max_length=50)),
                ("is_rented", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "picture",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                        upload_to="equipments-pictures/",
                    ),
                ),
                (
                    "custom_options",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "metadata",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                ("contract", models.CharField(blank=True, default="", max_length=300)),
                (
                    "company",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_equipment",
                        to="companies.Company",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_equipments_manager",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="user_equipments", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["company"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEquipments",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("description", models.CharField(default="", max_length=300)),
                ("plate", models.CharField(blank=True, max_length=50)),
                ("is_rented", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "picture",
                    models.TextField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "custom_options",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "metadata",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                ("contract", models.CharField(blank=True, default="", max_length=300)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical equipments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name="equipments",
            unique_together={("company", "plate")},
        ),
    ]
