# Generated by Django 2.1.2 on 2019-03-07 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0010_auto_20190307_1136"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Equipments",
            new_name="Equipment",
        ),
        migrations.RenameModel(
            old_name="HistoricalEquipments",
            new_name="HistoricalEquipment",
        ),
        migrations.AlterModelOptions(
            name="historicalequipment",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical equipment",
            },
        ),
    ]
