# Generated by Django 2.1.2 on 2019-03-12 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_auto_20190307_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="company",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_equipment",
                to="companies.Company",
            ),
        ),
    ]
