# Generated by Django 2.1.2 on 2019-04-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_auto_20190312_1938"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="members_amount",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="historicalfirm",
            name="members_amount",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
