# Generated by Django 2.1.2 on 2019-04-29 17:13

from __future__ import unicode_literals

from django.db import migrations


def put_through_in_m2m(apps, schema_editor):
    UserInFirm = apps.get_model("companies", "UserInFirm")
    Firm = apps.get_model("companies", "Firm")

    for firm in Firm.objects.all():
        for user in firm.users.all():
            UserInFirm.objects.create(firm=firm, user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0014_auto_20190429_1412"),
    ]

    operations = [
        migrations.RunPython(put_through_in_m2m),
    ]
