# Generated by Django 2.1.2 on 2019-04-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0015_auto_20190429_1413"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firm",
            name="users",
        ),
    ]
