# Generated by Django 2.1.2 on 2019-04-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0016_remove_firm_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="firm",
            old_name="users_new",
            new_name="users",
        ),
    ]
