# Generated by Django 2.1.2 on 2019-04-29 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0017_auto_20190429_1458"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firm",
            name="users",
            field=models.ManyToManyField(
                related_name="user_firms",
                through="companies.UserInFirm",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
