# Generated by Django 2.1.2 on 2019-05-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0019_auto_20190429_2011"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="amount",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="amount",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
