# Generated by Django 2.1.2 on 2019-05-09 00:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0020_auto_20190502_1705"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userinfirm", unique_together={("user", "firm")}
        )
    ]
