# Generated by Django 2.1.2 on 2019-05-14 23:05

from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [("companies", "0021_auto_20190508_2116")]

    operations = [
        migrations.AddField(
            model_name="company",
            name="provider_logo",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                upload_to="companies-logos/",
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="provider_logo",
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
