# Generated by Django 2.1.2 on 2019-10-23 18:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0022_auto_20190514_2005"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="bounding_box",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="bounding_box",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
