# Generated by Django 2.1.2 on 2019-10-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0023_auto_20191023_1553"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="bounding_box",
            new_name="shape",
        ),
        migrations.RenameField(
            model_name="historicalcompany",
            old_name="bounding_box",
            new_name="shape",
        ),
    ]
