# Generated by Django 2.1.2 on 2019-11-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0024_auto_20191027_1611"),
        ("companies", "0024_accessrequest_historicalaccessrequest"),
    ]

    operations = []
