# Generated by Django 2.1.2 on 2019-11-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0003_auto_20191113_1432"),
        ("companies", "0025_merge_20191113_0929"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_requests",
                to="approval_flows.ApprovalStep",
            ),
        ),
        migrations.AddField(
            model_name="historicalaccessrequest",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="approval_flows.ApprovalStep",
            ),
        ),
    ]
