# Generated by Django 2.1.2 on 2019-11-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0026_auto_20191113_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalaccessrequest",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
