# Generated by Django 2.1.2 on 2019-12-17 12:40

from django.conf import settings
from django.db import migrations


def unique_together(apps, schema_editor):
    UserInCompany = apps.get_model("companies", "UserInCompany")
    db_alias = schema_editor.connection.alias

    users_in_company = UserInCompany.objects.using(db_alias).all()
    delete_ids = []
    for obj in users_in_company:
        a = users_in_company.filter(company=obj.company, user=obj.user).exclude(
            pk=obj.pk
        )
        if a.exists():
            if obj.pk not in delete_ids:
                delete_ids.append(a[0].pk)

    users_in_company.filter(pk__in=delete_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0027_auto_20191120_1831"),
    ]

    operations = [
        migrations.RunPython(unique_together, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="userincompany", unique_together={("user", "company")}
        ),
    ]
