# Generated by Django 2.1.2 on 2020-01-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0028_auto_20191217_0940"),
    ]

    operations = [
        migrations.AddField(
            model_name="companygroup",
            name="saml_idp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcompanygroup",
            name="saml_idp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
