# Generated by Django 2.1.2 on 2020-03-25 17:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0030_trigram"),
    ]

    operations = [
        migrations.AddField(
            model_name="companygroup",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcompanygroup",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
