# Generated by Django 2.1.2 on 2020-03-25 17:38

from django.db import migrations

disclaimer = "Disclaimer: Esse documento é protegido pela legislação \
sobre propriedade intelectual, sendo vedada a reprodução, distribuição \
ou comercialização não autorizadas de qualquer material ou conteúdo dele \
obtidos, sem a prévia e expressa autorização por escrito da ENGIE. \
A utilização não autorizada da informação contida neste documento \
estará sujeita às medidas legais cabíveis."


def add_disclaimer(apps, schema_editor):
    CompanyGroup = apps.get_model("companies", "CompanyGroup")
    db_alias = schema_editor.connection.alias

    groups = (
        CompanyGroup.objects.using(db_alias).filter(name__icontains="engie").distinct()
    )
    for group in groups:
        group.metadata["disclaimer"] = disclaimer
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0031_auto_20200325_1430"),
    ]

    operations = [
        migrations.RunPython(add_disclaimer, migrations.RunPython.noop),
    ]
