# Generated by Django 2.1.2 on 2020-05-21 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companies", "0032_auto_20200325_1438")]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_requests",
                to="approval_flows.ApprovalStep",
            ),
        )
    ]
