# Generated by Django 2.1.2 on 2020-07-01 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0033_auto_20200521_0005"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="key_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="key_users_company",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
