# Generated by Django 2.1.2 on 2020-09-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0034_company_key_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="companygroup",
            name="mobile_app",
            field=models.CharField(
                choices=[
                    ("energy", "energy"),
                    ("road", "road"),
                    ("undefined", "undefined"),
                ],
                default="undefined",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalcompanygroup",
            name="mobile_app",
            field=models.CharField(
                choices=[
                    ("energy", "energy"),
                    ("road", "road"),
                    ("undefined", "undefined"),
                ],
                default="undefined",
                max_length=100,
            ),
        ),
    ]
