# Generated by Django 2.1.2 on 2020-11-05 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companies", "0036_auto_20201105_0037")]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="companies.Company",
            ),
        )
    ]
