# Generated by Django 2.1.2 on 2021-01-15 10:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0037_auto_20201105_1738"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserincompany",
            name="added_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=36),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="userincompany",
            name="added_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=36),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
