# Generated by Django 2.1.2 on 2021-02-18 20:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0038_auto_20210115_0731"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserincompany",
            name="added_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="userincompany",
            name="added_permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, null=True, size=None
            ),
        ),
    ]
