# Generated by Django 2.1.2 on 2021-03-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0039_auto_20210218_1701"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="can_use_ecm_integration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalfirm",
            name="can_use_ecm_integration",
            field=models.BooleanField(default=False),
        ),
    ]
