# Generated by Django 2.2.23 on 2021-11-10 23:30

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import helpers.validators.brazilian_documents
import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0042_populate_firm_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCompany",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subcompany_type",
                    models.CharField(
                        choices=[("HIRING", "HIRING"), ("HIRED", "HIRED")],
                        max_length=6,
                    ),
                ),
                ("name", models.CharField(default="", max_length=300)),
                (
                    "cnpj",
                    models.CharField(
                        max_length=50,
                        validators=[
                            helpers.validators.brazilian_documents.validate_CNPJ
                        ],
                    ),
                ),
                (
                    "contract",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("contract_start_date", models.DateField()),
                ("contract_end_date", models.DateField()),
                ("office", models.TextField()),
                ("construction_name", models.TextField()),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                        upload_to="subcompanies-logos/",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_subcompanies",
                        to="companies.Company",
                    ),
                ),
                (
                    "hired_by_subcompany",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcompany_hired_subcompanies",
                        to="companies.SubCompany",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_leader_subcompanies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalSubCompany",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "subcompany_type",
                    models.CharField(
                        choices=[("HIRING", "HIRING"), ("HIRED", "HIRED")],
                        max_length=6,
                    ),
                ),
                ("name", models.CharField(default="", max_length=300)),
                (
                    "cnpj",
                    models.CharField(
                        max_length=50,
                        validators=[
                            helpers.validators.brazilian_documents.validate_CNPJ
                        ],
                    ),
                ),
                (
                    "contract",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("contract_start_date", models.DateField()),
                ("contract_end_date", models.DateField()),
                ("office", models.TextField()),
                ("construction_name", models.TextField()),
                (
                    "logo",
                    models.TextField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "hired_by_subcompany",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.SubCompany",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sub company",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
