# Generated by Django 2.2.23 on 2021-11-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0042_populate_firm_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalentity",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
