# Generated by Django 2.2.23 on 2021-11-11 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0043_historicalsubcompany_subcompany"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="firm_type",
            field=models.CharField(
                blank=True,
                choices=[("INTERNAL", "INTERNAL"), ("EXTERNAL", "EXTERNAL")],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="firm",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_responsible_firms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="firm",
            name="subcompany",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcompany_firms",
                to="companies.SubCompany",
            ),
        ),
        migrations.AddField(
            model_name="historicalfirm",
            name="firm_type",
            field=models.CharField(
                blank=True,
                choices=[("INTERNAL", "INTERNAL"), ("EXTERNAL", "EXTERNAL")],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalfirm",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalfirm",
            name="subcompany",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.SubCompany",
            ),
        ),
    ]
