# Generated by Django 2.2.23 on 2021-11-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companies", "0044_auto_20211110_2101")]

    operations = [
        migrations.AlterField(
            model_name="firm",
            name="firm_type",
            field=models.CharField(
                blank=True,
                choices=[("INTERNAL", "INTERNAL"), ("EXTERNAL", "EXTERNAL")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfirm",
            name="firm_type",
            field=models.CharField(
                blank=True,
                choices=[("INTERNAL", "INTERNAL"), ("EXTERNAL", "EXTERNAL")],
                max_length=8,
                null=True,
            ),
        ),
    ]
