# Generated by Django 2.2.23 on 2021-11-11 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("companies", "0045_auto_20211110_2142")]

    operations = [
        migrations.AlterModelOptions(
            name="subcompany", options={"verbose_name_plural": "Sub companies"}
        )
    ]
