# Generated by Django 2.2.23 on 2021-11-11 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companies", "0046_auto_20211110_2156")]

    operations = [
        migrations.AlterField(
            model_name="historicalsubcompany",
            name="hired_by_subcompany",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.SubCompany",
            ),
        ),
        migrations.AlterField(
            model_name="subcompany",
            name="hired_by_subcompany",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcompany_hired_subcompanies",
                to="companies.SubCompany",
            ),
        ),
    ]
