# Generated by Django 2.2.23 on 2021-11-11 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companies", "0047_auto_20211110_2200")]

    operations = [
        migrations.AlterField(
            model_name="firm",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_responsible_firms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="firm",
            name="subcompany",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcompany_firms",
                to="companies.SubCompany",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfirm",
            name="subcompany",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.SubCompany",
            ),
        ),
    ]
