# Generated by Django 2.2.23 on 2021-11-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("companies", "0048_auto_20211110_2327")]

    operations = [
        migrations.RenameField(
            model_name="historicalsubcompany",
            old_name="leader",
            new_name="responsible",
        ),
        migrations.RenameField(
            model_name="subcompany", old_name="leader", new_name="responsible"
        ),
        migrations.RemoveField(model_name="firm", name="firm_type"),
        migrations.RemoveField(model_name="firm", name="responsible"),
        migrations.RemoveField(model_name="historicalfirm", name="firm_type"),
        migrations.RemoveField(model_name="historicalfirm", name="responsible"),
    ]
