# Generated by Django 2.2.23 on 2021-12-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0048_auto_20211110_2327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubcompany",
            name="construction_name",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalsubcompany",
            name="contract_end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="historicalsubcompany",
            name="contract_start_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="subcompany",
            name="construction_name",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="subcompany",
            name="contract_end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="subcompany",
            name="contract_start_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
