# Generated by Django 2.2.23 on 2021-11-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("companies", "0049_auto_20211126_0841")]

    operations = [
        migrations.AlterField(
            model_name="subcompany",
            name="responsible",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_responsible_subcompanies",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
