# Generated by Django 2.2.23 on 2021-12-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0050_auto_20211126_0842"),
        ("companies", "0043_auto_20211130_1644"),
    ]

    operations = []
