# Generated by Django 2.2.23 on 2021-12-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0051_merge_20211207_0929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubcompany",
            name="office",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="subcompany",
            name="office",
            field=models.TextField(blank=True),
        ),
    ]
