# Generated by Django 2.2.23 on 2022-02-10 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0052_auto_20211215_0857"),
        ("companies", "0051_merge_20211207_0836"),
    ]

    operations = []
