# Generated by Django 2.2.23 on 2022-06-22 08:44
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0053_merge_20220210_0019"),
    ]
    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="companies",
            field=models.ManyToManyField(
                related_name="access_requests", to="companies.Company"
            ),
        ),
    ]
