# Generated by Django 2.2.28 on 2023-03-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0054_auto_20220711_1147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firm",
            name="members_amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfirm",
            name="members_amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
