# Generated by Django 2.2.28 on 2023-05-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0055_auto_20230315_0030"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="mobile_app_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("energy", "energy"),
                    ("road", "road"),
                    ("undefined", "undefined"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcompany",
            name="mobile_app_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("energy", "energy"),
                    ("road", "road"),
                    ("undefined", "undefined"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
