# Generated by Django 2.2.28 on 2023-06-01 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0056_auto_20230505_1201"),
        ("companies", "0056_fill_reportingspreadsheet"),
    ]

    operations = []
