# Generated by Django 2.2.28 on 2023-06-27 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0057_merge_20230601_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firm",
            name="inspectors",
            field=models.ManyToManyField(
                blank=True,
                related_name="inspector_firms",
                through="companies.InspectorInFirm",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
