# Generated by Django 2.2.28 on 2023-06-08 14:44

from django.db import migrations
from django.db.models import Q
from django_bulk_update.helper import bulk_update

from helpers.strings import get_obj_from_path


def change_occurrence_description(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Company = apps.get_model("companies", "Company")

    company_qs = Company.objects.using(db_alias).filter(
        Q(custom_options__has_key="dailyReportOccurrence")
        | Q(custom_options__has_key="daily_report_occurrence")
    )

    updated_companies = []

    for company in company_qs:
        occurrence_description_path = (
            "dailyReportOccurrence__fields__description__displayName"
        )
        occurrence_description_display_name = get_obj_from_path(
            company.custom_options, occurrence_description_path
        )

        if occurrence_description_display_name:
            try:
                company.custom_options["dailyReportOccurrence"]["fields"][
                    "description"
                ]["displayName"] = "Categoria"
            except Exception:
                continue

            updated_companies.append(company)

    if len(updated_companies) > 0:
        bulk_update(
            updated_companies, batch_size=1000, update_fields=["custom_options"]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0057_merge_20230601_1835"),
    ]

    operations = [
        migrations.RunPython(
            change_occurrence_description,
            reverse_code=migrations.RunPython.noop,
        )
    ]
