# Generated by Django 2.2.28 on 2023-09-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0058_change_occurrence_description"),
        ("companies", "0058_auto_20230627_1022"),
    ]

    operations = []
