# Generated by Django 2.2.28 on 2024-02-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0060_add_max_reportings_by_job_20231113_0731"),
        ("companies", "0060_fill_inventoryspreadsheet"),
    ]

    operations = []
