# Generated by Django 2.2.28 on 2024-03-28 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0061_fill_metadata_with_new_keys"),
        ("companies", "0061_merge_20240215_1118"),
    ]

    operations = []
