# Generated by Django 2.2.28 on 2024-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0062_merge_20240328_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="is_judiciary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalfirm",
            name="is_judiciary",
            field=models.BooleanField(default=False),
        ),
    ]
