# Generated by Django 2.2.28 on 2024-04-30 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0063_auto_20240422_1157"),
        ("companies", "0060_create_copy_occurrences_to_new_rdo"),
    ]

    operations = []
