# Generated by Django 2.2.28 on 2024-09-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0064_merge_20240430_1604"),
        ("companies", "0062_create_artesp_occurrence_type"),
    ]

    operations = []
