# Generated by Django 2.2.28 on 2024-07-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0064_merge_20240430_1604"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubcompany",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaluserincompany",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subcompany",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userincompany",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
