# Generated by Django 2.2.28 on 2023-04-12 13:15

from django.db import migrations


def deactivates_inactive_users(apps, schema_editor):
    UserInCompany = apps.get_model("companies", "UserInCompany")
    HistoricalUserInCompany = apps.get_model("companies", "HistoricalUserInCompany")
    UserPermission = apps.get_model("permissions", "UserPermission")
    all_history = (
        HistoricalUserInCompany.objects.prefetch_related("permissions")
        .only("uuid", "permissions", "history_date")
        .all()
    )

    for user_in_company in (
        UserInCompany.objects.filter(permissions__name__icontains="inativo")
        .prefetch_related("permissions")
        .all()
    ):
        user_in_company_history = (
            all_history.filter(uuid=user_in_company.uuid)
            .exclude(permissions_id=user_in_company.permissions_id)
            .exclude(permissions__name__icontains="inativo")
            .order_by("-history_date")
        )
        if user_in_company_history.exists():
            last_perm_id = user_in_company_history.first().permissions_id
            if UserPermission.objects.filter(
                uuid=last_perm_id, companies=user_in_company.company_id
            ).exists():
                user_in_company.permissions_id = last_perm_id

        user_in_company.is_active = False
        user_in_company.save()


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0065_auto_20240712_0006"),
    ]

    operations = [migrations.RunPython(deactivates_inactive_users)]
