# Generated by Django 2.2.28 on 2024-10-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0065_merge_20240912_1801"),
        ("companies", "0065_auto_20240712_0006"),
    ]

    operations = []
