# Generated by Django 2.2.28 on 2024-10-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0066_merge_20241010_1042"),
        ("companies", "0066_deactivates_inactive_users"),
    ]

    operations = []
