# Generated by Django 2.2.28 on 2025-03-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0068_auto_20241214_1054"),
        ("companies", "0055_change_company_to_companies"),
        ("companies", "0068_fill_is_clustered_access_request"),
    ]

    operations = []
