# Generated by Django 2.2.28 on 2025-04-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0069_merge_20250424_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="delete_in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalfirm",
            name="delete_in_progress",
            field=models.BooleanField(default=False),
        ),
    ]
