# Generated by Django 2.2.28 on 2025-05-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0070_auto_20250424_1620"),
        ("companies", "0069_merge_20250326_1531"),
    ]

    operations = []
