# Generated by Django 3.2.25 on 2025-05-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0068_auto_20250227_1243"),
        ("companies", "0071_merge_20250506_1721"),
    ]

    operations = []
