# Generated by Django 3.2.25 on 2025-05-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0072_merge_20250507_1544"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcompanyusage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Company Usage",
                "verbose_name_plural": "historical Company Usages",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaluserusage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical User Usage",
                "verbose_name_plural": "historical User Usages",
            },
        ),
        migrations.AlterField(
            model_name="companyusage",
            name="company_names",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="historicalcompanyusage",
            name="company_names",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="historicalcompanyusage",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaluserusage",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
