# Generated by Django 3.2.25 on 2025-06-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0073_auto_20250516_1459"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalequipment",
            name="company",
        ),
        migrations.RemoveField(
            model_name="historicalequipment",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalequipment",
            name="manager",
        ),
        migrations.DeleteModel(
            name="Equipment",
        ),
        migrations.DeleteModel(
            name="HistoricalEquipment",
        ),
    ]
