# Generated by Django 3.2.25 on 2025-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0073_auto_20250516_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="legacy_uuid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalfirm",
            name="legacy_uuid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsubcompany",
            name="legacy_uuid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="subcompany",
            name="legacy_uuid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
