# Generated by Django 3.2.25 on 2025-09-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0074_auto_20250604_1735"),
        ("companies", "0074_auto_20250909_1951"),
    ]

    operations = []
