# Generated by Django 3.2.25 on 2026-04-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0076_fill_auto_archive_job_defaults"),
        ("companies", "0077_backfill_current_month_snapshot"),
    ]

    operations = []
