# Generated by Django 2.1.2 on 2021-04-19 12:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0040_auto_20210314_2321"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("day_without_work", models.BooleanField(default=False)),
                (
                    "morning_weather",
                    models.CharField(
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "afternoon_weather",
                    models.CharField(
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "night_weather",
                    models.CharField(
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "morning_conditions",
                    models.CharField(
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "afternoon_conditions",
                    models.CharField(
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "night_conditions",
                    models.CharField(
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("morning_start", models.TimeField()),
                ("morning_end", models.TimeField()),
                ("aftertoon_start", models.TimeField()),
                ("afternoon_end", models.TimeField()),
                ("night_start", models.TimeField()),
                ("night_end", models.TimeField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_daily_reports",
                        to="companies.Company",
                    ),
                ),
            ],
        ),
    ]
