# Generated by Django 2.1.2 on 2021-04-20 11:53

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0040_auto_20210314_2321"),
        ("daily_reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDailyReport",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("date", models.DateField()),
                ("day_without_work", models.BooleanField(default=False)),
                (
                    "morning_weather",
                    models.CharField(
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "afternoon_weather",
                    models.CharField(
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "night_weather",
                    models.CharField(
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "morning_conditions",
                    models.CharField(
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "afternoon_conditions",
                    models.CharField(
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "night_conditions",
                    models.CharField(
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                    ),
                ),
                ("morning_start", models.TimeField()),
                ("morning_end", models.TimeField()),
                ("aftertoon_start", models.TimeField()),
                ("afternoon_end", models.TimeField()),
                ("night_start", models.TimeField()),
                ("night_end", models.TimeField()),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical daily report",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
