# Generated by Django 2.1.2 on 2021-04-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0002_historicaldailyreport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyreport",
            old_name="aftertoon_start",
            new_name="afternoon_start",
        ),
        migrations.RenameField(
            model_name="historicaldailyreport",
            old_name="aftertoon_start",
            new_name="afternoon_start",
        ),
    ]
