# Generated by Django 2.1.2 on 2021-04-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0040_auto_20210314_2321"),
        ("daily_reports", "0003_auto_20210422_0819"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyreport",
            unique_together={("date", "company")},
        ),
    ]
