# Generated by Django 2.1.2 on 2021-04-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0004_auto_20210428_0804")]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="afternoon_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="afternoon_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="afternoon_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="afternoon_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="morning_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="morning_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="morning_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="morning_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="night_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="night_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="night_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="night_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="afternoon_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="afternoon_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="afternoon_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="afternoon_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="morning_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="morning_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="morning_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="morning_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="night_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="night_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="night_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="night_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                ],
                max_length=6,
                null=True,
            ),
        ),
    ]
