# Generated by Django 2.1.2 on 2021-05-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0040_auto_20210314_2321"),
        ("daily_reports", "0007_auto_20210430_1535"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportexternalteam",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_external_teams",
                to="companies.Company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldailyreportexternalteam",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.Company",
            ),
        ),
    ]
