# Generated by Django 2.1.2 on 2021-05-04 12:15

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0040_auto_20210314_2321"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("daily_reports", "0010_auto_20210503_1338"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReportSignaling",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                ("amount", models.IntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_daily_report_signaling",
                        to="companies.Company",
                    ),
                ),
                (
                    "daily_reports",
                    models.ManyToManyField(
                        related_name="daily_report_signaling",
                        through="daily_reports.DailyReportRelation",
                        to="daily_reports.DailyReport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalDailyReportSignaling",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("description", models.TextField()),
                ("amount", models.IntegerField()),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical daily report signaling",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="dailyreportrelation",
            name="signaling",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signaling_relations",
                to="daily_reports.DailyReportSignaling",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportrelation",
            name="signaling",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="daily_reports.DailyReportSignaling",
            ),
        ),
    ]
