# Generated by Django 2.1.2 on 2021-05-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0011_auto_20210504_0915")]

    operations = [
        migrations.AlterField(
            model_name="dailyreportrelation",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="dailyreportworker",
            name="members",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportrelation",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportworker",
            name="members",
            field=models.TextField(blank=True, null=True),
        ),
    ]
