# Generated by Django 2.1.2 on 2021-05-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0012_auto_20210507_1632")]

    operations = [
        migrations.AlterModelOptions(
            name="dailyreport", options={"ordering": ["company"]}
        ),
        migrations.AlterModelOptions(
            name="dailyreportequipment",
            options={
                "ordering": ["company"],
                "verbose_name_plural": "Daily report equipment",
            },
        ),
        migrations.AlterModelOptions(
            name="dailyreportexternalteam", options={"ordering": ["company"]}
        ),
        migrations.AlterModelOptions(
            name="dailyreportrelation",
            options={"ordering": ["daily_report__company"]},
        ),
        migrations.AlterModelOptions(
            name="dailyreportsignaling",
            options={
                "ordering": ["company"],
                "verbose_name_plural": "Daily report signaling",
            },
        ),
        migrations.AlterModelOptions(
            name="dailyreportvehicle", options={"ordering": ["company"]}
        ),
        migrations.AlterModelOptions(
            name="dailyreportworker", options={"ordering": ["firm__company"]}
        ),
    ]
