# Generated by Django 2.1.2 on 2021-05-25 16:14

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0042_populate_firm_created_by"),
        ("reportings", "0039_auto_20210506_0900"),
        ("daily_reports", "0015_populate_daily_report_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMultipleDailyReport",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("date", models.DateField()),
                ("day_without_work", models.BooleanField(default=False)),
                (
                    "morning_weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "afternoon_weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "night_weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "morning_conditions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "afternoon_conditions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "night_conditions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("morning_start", models.TimeField(blank=True, null=True)),
                ("morning_end", models.TimeField(blank=True, null=True)),
                ("afternoon_start", models.TimeField(blank=True, null=True)),
                ("afternoon_end", models.TimeField(blank=True, null=True)),
                ("night_start", models.TimeField(blank=True, null=True)),
                ("night_end", models.TimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Firm",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical multiple daily report",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MultipleDailyReport",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("day_without_work", models.BooleanField(default=False)),
                (
                    "morning_weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "afternoon_weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "night_weather",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUNNY", "SUNNY"),
                            ("CLOUDY", "CLOUDY"),
                            ("RAINY", "RAINY"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "morning_conditions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "afternoon_conditions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "night_conditions",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FEASIBLE", "FEASIBLE"),
                            ("UNFEASIBLE", "UNFEASIBLE"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("morning_start", models.TimeField(blank=True, null=True)),
                ("morning_end", models.TimeField(blank=True, null=True)),
                ("afternoon_start", models.TimeField(blank=True, null=True)),
                ("afternoon_end", models.TimeField(blank=True, null=True)),
                ("night_start", models.TimeField(blank=True, null=True)),
                ("night_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_multipledailyreports",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_multipledailyreports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firm_multiple_daily_report",
                        to="companies.Firm",
                    ),
                ),
                (
                    "reportings",
                    models.ManyToManyField(
                        related_name="reporting_multiple_daily_reports",
                        to="reportings.Reporting",
                    ),
                ),
            ],
            options={"ordering": ["company"], "abstract": False},
        ),
        migrations.AlterUniqueTogether(
            name="multipledailyreport",
            unique_together={("created_by", "firm", "date")},
        ),
    ]
