# Generated by Django 2.1.2 on 2021-05-26 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0016_auto_20210525_1314")]

    operations = [
        migrations.AddField(
            model_name="dailyreportrelation",
            name="multiple_daily_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multiple_report_relations",
                to="daily_reports.MultipleDailyReport",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportrelation",
            name="multiple_daily_report",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="daily_reports.MultipleDailyReport",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreportrelation",
            name="daily_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_relations",
                to="daily_reports.DailyReport",
            ),
        ),
    ]
