# Generated by Django 2.2.23 on 2021-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0017_auto_20210526_0914")]

    operations = [
        migrations.AddConstraint(
            model_name="dailyreportrelation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("daily_report__isnull", False),
                        ("multiple_daily_report__isnull", True),
                    ),
                    models.Q(
                        ("daily_report__isnull", True),
                        ("multiple_daily_report__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="only_one_report_field_is_filled",
            ),
        )
    ]
