# Generated by Django 2.2.23 on 2021-05-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0018_auto_20210526_1103")]

    operations = [
        migrations.AddField(
            model_name="dailyreportequipment",
            name="multiple_daily_reports",
            field=models.ManyToManyField(
                related_name="multiple_daily_report_equipment",
                through="daily_reports.DailyReportRelation",
                to="daily_reports.MultipleDailyReport",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportexternalteam",
            name="multiple_daily_reports",
            field=models.ManyToManyField(
                related_name="multiple_daily_report_external_teams",
                through="daily_reports.DailyReportRelation",
                to="daily_reports.MultipleDailyReport",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportsignaling",
            name="multiple_daily_reports",
            field=models.ManyToManyField(
                related_name="multiple_daily_report_signaling",
                through="daily_reports.DailyReportRelation",
                to="daily_reports.MultipleDailyReport",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportvehicle",
            name="multiple_daily_reports",
            field=models.ManyToManyField(
                related_name="multiple_daily_report_vehicles",
                through="daily_reports.DailyReportRelation",
                to="daily_reports.MultipleDailyReport",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportworker",
            name="multiple_daily_reports",
            field=models.ManyToManyField(
                related_name="multiple_daily_report_workers",
                through="daily_reports.DailyReportRelation",
                to="daily_reports.MultipleDailyReport",
            ),
        ),
    ]
