# Generated by Django 2.2.23 on 2021-05-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0019_auto_20210526_1524")]

    operations = [
        migrations.AlterField(
            model_name="multipledailyreport",
            name="reportings",
            field=models.ManyToManyField(
                blank=True,
                related_name="reporting_multiple_daily_reports",
                to="reportings.Reporting",
            ),
        )
    ]
