# Generated by Django 2.2.23 on 2021-06-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0020_auto_20210527_0922")]

    operations = [
        migrations.AlterField(
            model_name="dailyreportsignaling",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportsignaling",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
