# Generated by Django 2.2.23 on 2021-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0039_auto_20210506_0900"),
        ("daily_reports", "0021_auto_20210601_1351"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="reporting_files",
            field=models.ManyToManyField(
                blank=True,
                related_name="reporting_file_dailyreports",
                to="reportings.ReportingFile",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreport",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmultipledailyreport",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="multipledailyreport",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="multipledailyreport",
            name="reporting_files",
            field=models.ManyToManyField(
                blank=True,
                related_name="reporting_file_multipledailyreports",
                to="reportings.ReportingFile",
            ),
        ),
    ]
