# Generated by Django 2.2.23 on 2021-05-31 14:06

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0022_auto_20190527_1646"),
        ("daily_reports", "0022_auto_20210528_1321"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportrelation",
            name="daily_planned_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportrelation",
            name="daily_planned_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProductionGoal",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateField()),
                ("ends_at", models.DateField()),
                ("days_of_work", models.IntegerField()),
                ("amount", models.FloatField()),
                (
                    "daily_reports",
                    models.ManyToManyField(
                        related_name="daily_report_production_goals",
                        through="daily_reports.DailyReportRelation",
                        to="daily_reports.DailyReport",
                    ),
                ),
                (
                    "multiple_daily_reports",
                    models.ManyToManyField(
                        related_name="multiple_daily_report_production_goals",
                        through="daily_reports.DailyReportRelation",
                        to="daily_reports.MultipleDailyReport",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_production_goals",
                        to="services.Service",
                    ),
                ),
            ],
            options={"ordering": ["service__company"]},
        ),
        migrations.CreateModel(
            name="HistoricalProductionGoal",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("starts_at", models.DateField()),
                ("ends_at", models.DateField()),
                ("days_of_work", models.IntegerField()),
                ("amount", models.FloatField()),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="services.Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical production goal",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="dailyreportrelation",
            name="production_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_goal_relations",
                to="daily_reports.ProductionGoal",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportrelation",
            name="production_goal",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="daily_reports.ProductionGoal",
            ),
        ),
    ]
