# Generated by Django 2.2.23 on 2021-07-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0023_auto_20210531_1106"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="number",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreport",
            name="number",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="historicalmultipledailyreport",
            name="number",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="multipledailyreport",
            name="number",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
