# Generated by Django 2.2.23 on 2021-08-10 11:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0024_auto_20210720_0903")]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="identification",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreport",
            name="identification",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
