# Generated by Django 2.2.23 on 2021-08-10 13:59

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0042_populate_firm_created_by"),
        ("daily_reports", "0025_auto_20210810_0808"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDailyReportOccurrence",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                ("impact_duration", models.TimeField()),
                ("description", models.TextField()),
                ("extra_info", models.TextField()),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Firm",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical daily report occurrence",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DailyReportOccurrence",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                ("impact_duration", models.TimeField()),
                ("description", models.TextField()),
                ("extra_info", models.TextField()),
                (
                    "daily_reports",
                    models.ManyToManyField(
                        related_name="daily_report_occurrences",
                        through="daily_reports.DailyReportRelation",
                        to="daily_reports.DailyReport",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firm_daily_report_occurrences",
                        to="companies.Firm",
                    ),
                ),
                (
                    "multiple_daily_reports",
                    models.ManyToManyField(
                        related_name="multiple_daily_report_occurrences",
                        through="daily_reports.DailyReportRelation",
                        to="daily_reports.MultipleDailyReport",
                    ),
                ),
            ],
            options={"ordering": ["firm__company"]},
        ),
        migrations.AddField(
            model_name="dailyreportrelation",
            name="occurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrence_relations",
                to="daily_reports.DailyReportOccurrence",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportrelation",
            name="occurrence",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="daily_reports.DailyReportOccurrence",
            ),
        ),
    ]
