# Generated by Django 2.2.23 on 2021-09-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0026_auto_20210810_1059")]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="afternoon_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="afternoon_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="morning_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="morning_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="night_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="night_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="afternoon_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="afternoon_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="morning_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="morning_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="night_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="night_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreport",
            name="afternoon_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreport",
            name="afternoon_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreport",
            name="morning_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreport",
            name="morning_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreport",
            name="night_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreport",
            name="night_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="multipledailyreport",
            name="afternoon_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="multipledailyreport",
            name="afternoon_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="multipledailyreport",
            name="morning_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="multipledailyreport",
            name="morning_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="multipledailyreport",
            name="night_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FEASIBLE", "FEASIBLE"),
                    ("UNFEASIBLE", "UNFEASIBLE"),
                    ("NA", "NA"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="multipledailyreport",
            name="night_weather",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUNNY", "SUNNY"),
                    ("CLOUDY", "CLOUDY"),
                    ("RAINY", "RAINY"),
                    ("NA", "NA"),
                ],
                max_length=6,
                null=True,
            ),
        ),
    ]
