# Generated by Django 2.2.23 on 2021-10-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0027_auto_20210920_0804")]

    operations = [
        migrations.RemoveField(model_name="dailyreportequipment", name="prefix"),
        migrations.RemoveField(model_name="dailyreportvehicle", name="license_plate"),
        migrations.RemoveField(
            model_name="historicaldailyreportequipment", name="prefix"
        ),
        migrations.RemoveField(
            model_name="historicaldailyreportvehicle", name="license_plate"
        ),
    ]
