# Generated by Django 2.2.23 on 2021-11-29 03:57

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0015_auto_20201104_0956"),
        ("daily_reports", "0029_auto_20211109_1127"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDailyReportResource",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("amount", models.IntegerField()),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="resources.Resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical daily report resource",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DailyReportResource",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "daily_reports",
                    models.ManyToManyField(
                        related_name="daily_report_resources",
                        through="daily_reports.DailyReportRelation",
                        to="daily_reports.DailyReport",
                    ),
                ),
                (
                    "multiple_daily_reports",
                    models.ManyToManyField(
                        related_name="multiple_daily_report_resources",
                        through="daily_reports.DailyReportRelation",
                        to="daily_reports.MultipleDailyReport",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_daily_report_resources",
                        to="resources.Resource",
                    ),
                ),
            ],
            options={"ordering": ["resource__company"]},
        ),
        migrations.AddField(
            model_name="dailyreportrelation",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resource_relations",
                to="daily_reports.DailyReportResource",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportrelation",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="daily_reports.DailyReportResource",
            ),
        ),
    ]
