# Generated by Django 2.2.23 on 2021-12-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0030_auto_20211129_0057")]

    operations = [
        migrations.RenameField(
            model_name="dailyreportsignaling",
            old_name="description",
            new_name="kind",
        ),
        migrations.RenameField(
            model_name="historicaldailyreportsignaling",
            old_name="description",
            new_name="kind",
        ),
        migrations.RemoveField(model_name="dailyreportsignaling", name="amount"),
        migrations.RemoveField(
            model_name="historicaldailyreportsignaling", name="amount"
        ),
    ]
