# Generated by Django 2.2.23 on 2021-12-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0031_auto_20211206_0305")]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="use_reporting_resources",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldailyreport",
            name="use_reporting_resources",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalmultipledailyreport",
            name="use_reporting_resources",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="multipledailyreport",
            name="use_reporting_resources",
            field=models.BooleanField(default=False),
        ),
    ]
