# Generated by Django 2.2.23 on 2021-12-17 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0009_auto_20201105_0351"),
        ("daily_reports", "0032_auto_20211215_2259"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_dailyreports",
                to="approval_flows.ApprovalStep",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreport",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="approval_flows.ApprovalStep",
            ),
        ),
        migrations.AddField(
            model_name="historicalmultipledailyreport",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="approval_flows.ApprovalStep",
            ),
        ),
        migrations.AddField(
            model_name="multipledailyreport",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_multipledailyreports",
                to="approval_flows.ApprovalStep",
            ),
        ),
    ]
