# Generated by Django 2.2.23 on 2021-12-17 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0033_auto_20211216_2201")]

    operations = [
        migrations.AddField(
            model_name="historicaldailyreport",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                default="00000db3-a561-4387-ac47-d48fca2d6c24",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="history_historicaldailyreports",
                to="daily_reports.DailyReport",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmultipledailyreport",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                default="00000db3-a561-4387-ac47-d48fca2d6c24",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="history_historicalmultipledailyreports",
                to="daily_reports.MultipleDailyReport",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreport",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
