# Generated by Django 2.2.23 on 2021-12-17 19:43

from django.db import migrations
from django.db.models import F


def copy_value_to_related_name_reports(apps, schema_editor):
    HistoricalMultipleDailyReport = apps.get_model(
        "daily_reports", "HistoricalMultipleDailyReport"
    )
    HistoricalDailyReport = apps.get_model("daily_reports", "HistoricalDailyReport")
    db_alias = schema_editor.connection.alias

    HistoricalMultipleDailyReport.objects.using(db_alias).all().update(
        history_relation=F("uuid")
    )

    HistoricalDailyReport.objects.using(db_alias).all().update(
        history_relation=F("uuid")
    )


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0034_auto_20211217_1640")]

    operations = [
        migrations.RunPython(
            copy_value_to_related_name_reports, migrations.RunPython.noop
        )
    ]
