# Generated by Django 2.2.23 on 2021-12-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0035_auto_20211217_1643")]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="editable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreport",
            name="editable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalmultipledailyreport",
            name="editable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="multipledailyreport",
            name="editable",
            field=models.BooleanField(default=True),
        ),
    ]
