# Generated by Django 2.2.23 on 2021-12-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0037_dailyreportexport_historicaldailyreportexport")
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreportexport",
            name="daily_reports",
            field=models.ManyToManyField(
                blank=True,
                related_name="daily_report_exports",
                to="daily_reports.DailyReport",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreportexport",
            name="multiple_daily_reports",
            field=models.ManyToManyField(
                blank=True,
                related_name="multiple_daily_report_exports",
                to="daily_reports.MultipleDailyReport",
            ),
        ),
    ]
