# Generated by Django 2.2.23 on 2022-02-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daily_reports",
            "0037_dailyreportboarditem_historicaldailyreportboarditem",
        )
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreportboarditem",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportworker"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportexternalteam"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportequipment"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportvehicle"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportsignaling"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportoccurrence"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportresource"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "productiongoal"),
                    ),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportboarditem",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to=models.Q(
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportworker"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportexternalteam"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportequipment"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportvehicle"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportsignaling"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportoccurrence"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportresource"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "productiongoal"),
                    ),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.ContentType",
            ),
        ),
    ]
