# Generated by Django 2.2.23 on 2021-12-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0038_auto_20211222_0903")]

    operations = [
        migrations.AddField(
            model_name="dailyreportexport",
            name="is_compiled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldailyreportexport",
            name="is_compiled",
            field=models.BooleanField(default=False),
        ),
    ]
