# Generated by Django 2.2.23 on 2022-03-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0038_auto_20220209_1106")]

    operations = [migrations.DeleteModel(name="HistoricalDailyReportBoardItem")]
