# Generated by Django 2.2.23 on 2022-03-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0039_delete_historicaldailyreportboarditem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DailyReportBoardItem",
        ),
    ]
