# Generated by Django 2.2.23 on 2022-01-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0039_auto_20211222_1514")]

    operations = [
        migrations.AddField(
            model_name="dailyreportresource",
            name="kind",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicaldailyreportresource",
            name="kind",
            field=models.TextField(default=""),
        ),
    ]
