# Generated by Django 2.2.23 on 2022-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0040_auto_20220104_1655")]

    operations = [
        migrations.AlterField(
            model_name="dailyreportresource",
            name="kind",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportresource",
            name="kind",
            field=models.TextField(blank=True, null=True),
        ),
    ]
