# Generated by Django 2.2.23 on 2022-03-09 00:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0028_auto_20220308_1939"),
        ("daily_reports", "0040_delete_dailyreportboarditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportequipment",
            name="contract_item_administration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_item_administration_equipment",
                to="resources.ContractItemAdministration",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportequipment",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dailyreportequipment",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreportvehicle",
            name="contract_item_administration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_item_administration_vehicles",
                to="resources.ContractItemAdministration",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportvehicle",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dailyreportvehicle",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreportworker",
            name="contract_item_administration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_item_administration_workers",
                to="resources.ContractItemAdministration",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportworker",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dailyreportworker",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportequipment",
            name="contract_item_administration",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resources.ContractItemAdministration",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportequipment",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="historicaldailyreportequipment",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportvehicle",
            name="contract_item_administration",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resources.ContractItemAdministration",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportvehicle",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="historicaldailyreportvehicle",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportworker",
            name="contract_item_administration",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resources.ContractItemAdministration",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportworker",
            name="creation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="historicaldailyreportworker",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreportequipment",
            name="kind",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreportsignaling",
            name="kind",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreportvehicle",
            name="kind",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportequipment",
            name="kind",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportsignaling",
            name="kind",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportvehicle",
            name="kind",
            field=models.TextField(blank=True, null=True),
        ),
    ]
