# Generated by Django 2.2.23 on 2022-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0041_auto_20220308_2129")]

    operations = [
        migrations.AlterField(
            model_name="dailyreportequipment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreportvehicle",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreportworker",
            name="role",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportequipment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportvehicle",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportworker",
            name="role",
            field=models.TextField(blank=True, null=True),
        ),
    ]
