# Generated by Django 2.2.23 on 2022-03-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0051_merge_20211207_0836"),
        ("daily_reports", "0042_auto_20220309_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportworker",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_daily_report_workers",
                to="companies.Company",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportworker",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.Company",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreportworker",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="firm_daily_report_workers",
                to="companies.Firm",
            ),
        ),
    ]
