# Generated by Django 2.2.23 on 2022-03-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0043_auto_20220309_1459")]

    operations = [migrations.AlterModelOptions(name="dailyreportworker", options={})]
