# Generated by Django 2.2.23 on 2022-03-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0044_auto_20220311_0924"),
        ("daily_reports", "0041_auto_20220216_1127"),
    ]

    operations = []
