# Generated by Django 2.2.23 on 2022-03-15 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0095_auto_20220308_1513"),
        ("daily_reports", "0045_merge_20220315_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportequipment",
            name="measurement_bulletin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletin_equipments",
                to="service_orders.MeasurementBulletin",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportvehicle",
            name="measurement_bulletin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletin_vehicles",
                to="service_orders.MeasurementBulletin",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportworker",
            name="measurement_bulletin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletin_workers",
                to="service_orders.MeasurementBulletin",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportequipment",
            name="measurement_bulletin",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.MeasurementBulletin",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportvehicle",
            name="measurement_bulletin",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.MeasurementBulletin",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportworker",
            name="measurement_bulletin",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.MeasurementBulletin",
            ),
        ),
    ]
