# Generated by Django 2.2.23 on 2022-03-24 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("daily_reports", "0045_merge_20220324_0855"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportequipment",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreportequipment",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                    ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                    ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                ],
                default="WAITING_APPROVAL",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="dailyreportequipment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyreportvehicle",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreportvehicle",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                    ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                    ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                ],
                default="WAITING_APPROVAL",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="dailyreportvehicle",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicle_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyreportworker",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreportworker",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                    ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                    ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                ],
                default="WAITING_APPROVAL",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="dailyreportworker",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workers_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportequipment",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportequipment",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                    ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                    ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                ],
                default="WAITING_APPROVAL",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportequipment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportvehicle",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportvehicle",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                    ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                    ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                ],
                default="WAITING_APPROVAL",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportvehicle",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportworker",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportworker",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                    ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                    ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                ],
                default="WAITING_APPROVAL",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportworker",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
