# Generated by Django 2.2.23 on 2022-03-30 14:00

from django.db import migrations
from tqdm import tqdm


def create_missing_contract_usages(apps, schema_editor):
    """
    Searches for all board items related to a contract_item_administration and missing
    a DailyReportContract usage and creates the missing instances.
    """

    db_alias = schema_editor.connection.alias
    DailyReportWorker = apps.get_model("daily_reports", "DailyReportWorker")
    DailyReportEquipment = apps.get_model("daily_reports", "DailyReportEquipment")
    DailyReportVehicle = apps.get_model("daily_reports", "DailyReportVehicle")
    DailyReportContractUsage = apps.get_model(
        "daily_reports", "DailyReportContractUsage"
    )

    worker_queryset = DailyReportWorker.objects.using(db_alias).filter(
        contract_item_administration__isnull=False,
        worker_contract_usage__isnull=True,
    )
    vehicle_queryset = DailyReportVehicle.objects.using(db_alias).filter(
        contract_item_administration__isnull=False,
        vehicle_contract_usage__isnull=True,
    )
    equipment_queryset = DailyReportEquipment.objects.using(db_alias).filter(
        contract_item_administration__isnull=False,
        equipment_contract_usage__isnull=True,
    )

    for worker in tqdm(worker_queryset):
        DailyReportContractUsage.objects.create(worker=worker)

    for vehicle in tqdm(vehicle_queryset):
        DailyReportContractUsage.objects.create(vehicle=vehicle)

    for equipment in tqdm(equipment_queryset):
        DailyReportContractUsage.objects.create(equipment=equipment)


class Migration(migrations.Migration):

    dependencies = [
        (
            "daily_reports",
            "0047_dailyreportcontractusage_historicaldailyreportcontractusage",
        )
    ]

    operations = [
        migrations.RunPython(
            create_missing_contract_usages,
            reverse_code=migrations.RunPython.noop,
        )
    ]
