# Generated by Django 2.2.23 on 2022-04-01 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0048_auto_20220330_1100")]

    operations = [
        migrations.AddField(
            model_name="historicaldailyreportequipment",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                default="00000db3-a561-4387-ac47-d48fca2d6c24",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="history_equipment",
                to="daily_reports.DailyReportEquipment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldailyreportvehicle",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                default="00000db3-a561-4387-ac47-d48fca2d6c24",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="history_vehicles",
                to="daily_reports.DailyReportVehicle",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldailyreportworker",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                default="00000db3-a561-4387-ac47-d48fca2d6c24",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="history_workers",
                to="daily_reports.DailyReportWorker",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicaldailyreportequipment",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportvehicle",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportworker",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
