# Generated by Django 2.2.23 on 2022-04-01 10:21

from django.db import migrations
from django.db.models import F


def copy_value_to_related_name_board_items(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    HistoricalDailyReportWorker = apps.get_model(
        "daily_reports", "HistoricalDailyReportWorker"
    )
    HistoricalDailyReportVehicle = apps.get_model(
        "daily_reports", "HistoricalDailyReportVehicle"
    )
    HistoricalDailyReportEquipment = apps.get_model(
        "daily_reports", "HistoricalDailyReportEquipment"
    )

    HistoricalDailyReportWorker.objects.using(db_alias).all().update(
        history_relation=F("uuid")
    )
    HistoricalDailyReportVehicle.objects.using(db_alias).all().update(
        history_relation=F("uuid")
    )
    HistoricalDailyReportEquipment.objects.using(db_alias).all().update(
        history_relation=F("uuid")
    )


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0049_auto_20220401_0719")]

    operations = [
        migrations.RunPython(
            copy_value_to_related_name_board_items, migrations.RunPython.noop
        )
    ]
