# Generated by Django 2.2.23 on 2022-04-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0050_auto_20220401_0721"),
        ("daily_reports", "0046_auto_20220315_1630"),
    ]

    operations = []
