# Generated by Django 2.2.23 on 2022-03-30 14:00

from django.db import migrations
from django.db.models import Q
from django_bulk_update.helper import bulk_update
from tqdm import tqdm


def fill_created_by(apps, schema_editor):
    """
    Searches for all board items where we added a created_by field and fills it
    using information from the related DailyReport or MultipleDailyReport
    """

    db_alias = schema_editor.connection.alias
    DailyReportWorker = apps.get_model("daily_reports", "DailyReportWorker")
    DailyReportExternalTeam = apps.get_model("daily_reports", "DailyReportExternalTeam")
    DailyReportEquipment = apps.get_model("daily_reports", "DailyReportEquipment")
    DailyReportVehicle = apps.get_model("daily_reports", "DailyReportVehicle")
    DailyReportSignaling = apps.get_model("daily_reports", "DailyReportSignaling")
    DailyReportOccurrence = apps.get_model("daily_reports", "DailyReportOccurrence")
    DailyReportResource = apps.get_model("daily_reports", "DailyReportResource")
    ProductionGoal = apps.get_model("daily_reports", "ProductionGoal")

    worker_queryset = (
        DailyReportWorker.objects.using(db_alias)
        .filter(
            Q(daily_reports__isnull=False) | Q(multiple_daily_reports__isnull=False)
        )
        .prefetch_related(
            "daily_reports",
            "multiple_daily_reports",
            "daily_reports__created_by",
            "multiple_daily_reports__created_by",
        )
    )
    external_team_queryset = (
        DailyReportExternalTeam.objects.using(db_alias)
        .filter(
            Q(daily_reports__isnull=False) | Q(multiple_daily_reports__isnull=False)
        )
        .prefetch_related(
            "daily_reports",
            "multiple_daily_reports",
            "daily_reports__created_by",
            "multiple_daily_reports__created_by",
        )
    )
    equipment_queryset = (
        DailyReportEquipment.objects.using(db_alias)
        .filter(
            Q(daily_reports__isnull=False) | Q(multiple_daily_reports__isnull=False)
        )
        .prefetch_related(
            "daily_reports",
            "multiple_daily_reports",
            "daily_reports__created_by",
            "multiple_daily_reports__created_by",
        )
    )
    vehicle_queryset = (
        DailyReportVehicle.objects.using(db_alias)
        .filter(
            Q(daily_reports__isnull=False) | Q(multiple_daily_reports__isnull=False)
        )
        .prefetch_related(
            "daily_reports",
            "multiple_daily_reports",
            "daily_reports__created_by",
            "multiple_daily_reports__created_by",
        )
    )
    signaling_queryset = (
        DailyReportSignaling.objects.using(db_alias)
        .filter(
            Q(daily_reports__isnull=False) | Q(multiple_daily_reports__isnull=False)
        )
        .prefetch_related(
            "daily_reports",
            "multiple_daily_reports",
            "daily_reports__created_by",
            "multiple_daily_reports__created_by",
        )
    )
    occurrence_queryset = (
        DailyReportOccurrence.objects.using(db_alias)
        .filter(
            Q(daily_reports__isnull=False) | Q(multiple_daily_reports__isnull=False)
        )
        .prefetch_related(
            "daily_reports",
            "multiple_daily_reports",
            "daily_reports__created_by",
            "multiple_daily_reports__created_by",
        )
    )
    resource_queryset = (
        DailyReportResource.objects.using(db_alias)
        .filter(
            Q(daily_reports__isnull=False) | Q(multiple_daily_reports__isnull=False)
        )
        .prefetch_related(
            "daily_reports",
            "multiple_daily_reports",
            "daily_reports__created_by",
            "multiple_daily_reports__created_by",
        )
    )
    production_goal_queryset = (
        ProductionGoal.objects.using(db_alias)
        .filter(
            Q(daily_reports__isnull=False) | Q(multiple_daily_reports__isnull=False)
        )
        .prefetch_related(
            "daily_reports",
            "multiple_daily_reports",
            "daily_reports__created_by",
            "multiple_daily_reports__created_by",
        )
    )

    querysets = [
        worker_queryset,
        external_team_queryset,
        equipment_queryset,
        vehicle_queryset,
        signaling_queryset,
        occurrence_queryset,
        resource_queryset,
        production_goal_queryset,
    ]

    for queryset in querysets:
        updated_items = []
        for qs_item in tqdm(queryset):
            if len(qs_item.daily_reports.all()):
                daily_report = next(a for a in qs_item.daily_reports.all())
            elif len(qs_item.multiple_daily_reports.all()):
                daily_report = next(a for a in qs_item.multiple_daily_reports.all())
            else:
                continue
            qs_item.created_by = daily_report.created_by
            updated_items.append(qs_item)

        bulk_update(updated_items, batch_size=1000, update_fields=["created_by"])


class Migration(migrations.Migration):

    dependencies = [("daily_reports", "0052_auto_20220420_0837")]

    operations = [
        migrations.RunPython(fill_created_by, reverse_code=migrations.RunPython.noop)
    ]
