# Generated by Django 2.2.23 on 2022-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0053_fill_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportoccurrence",
            name="origin",
            field=models.CharField(
                choices=[("EXECUTOR", "EXECUTOR"), ("INSPECTION", "INSPECTION")],
                default="EXECUTOR",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportoccurrence",
            name="origin",
            field=models.CharField(
                choices=[("EXECUTOR", "EXECUTOR"), ("INSPECTION", "INSPECTION")],
                default="EXECUTOR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreportoccurrence",
            name="ends_at",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreportoccurrence",
            name="impact_duration",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreportoccurrence",
            name="starts_at",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportoccurrence",
            name="ends_at",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportoccurrence",
            name="impact_duration",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportoccurrence",
            name="starts_at",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
