# Generated by Django 2.2.23 on 2022-06-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0053_fill_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreportequipment",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="dailyreportresource",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="dailyreportvehicle",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="dailyreportworker",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportequipment",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportresource",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportvehicle",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportworker",
            name="amount",
            field=models.FloatField(),
        ),
    ]
