# Generated by Django 2.2.23 on 2022-07-27 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0054_auto_20220711_1749"),
        ("daily_reports", "0054_auto_20220719_1059"),
        ("daily_reports", "0054_auto_20220603_0029"),
    ]

    operations = []
