# Generated by Django 2.2.23 on 2022-07-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0054_auto_20220603_0029"),
        ("daily_reports", "0054_auto_20220711_1749"),
        ("daily_reports", "0054_auto_20220719_1059"),
    ]

    operations = []
