# Generated by Django 2.2.23 on 2022-07-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0055_merge_20220726_2103"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreportoccurrence",
            name="extra_info",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportoccurrence",
            name="extra_info",
            field=models.TextField(blank=True),
        ),
    ]
