# Generated by Django 2.2.23 on 2022-08-15 12:46

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0044_merge_20220711_1256"),
        ("daily_reports", "0056_auto_20220729_1309"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_dailyreports",
                to="resources.Contract",
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="header_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreport",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resources.Contract",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreport",
            name="header_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalmultipledailyreport",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resources.Contract",
            ),
        ),
        migrations.AddField(
            model_name="historicalmultipledailyreport",
            name="header_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="multipledailyreport",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_multipledailyreports",
                to="resources.Contract",
            ),
        ),
        migrations.AddField(
            model_name="multipledailyreport",
            name="header_info",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
