# Generated by Django 2.2.23 on 2022-11-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0057_auto_20220815_0946"),
        ("daily_reports", "0055_merge_20220726_1514"),
    ]

    operations = []
