# Generated by Django 2.2.28 on 2023-06-16 21:49

import uuid

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("daily_reports", "0058_merge_20221111_1348"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleDailyReportFile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("md5", models.TextField(blank=True)),
                (
                    "upload",
                    models.FileField(
                        storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                        upload_to="",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("kind", models.CharField(blank=True, default="", max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_multiple_daily_report_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "multiple_daily_report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="multiple_daily_report_files",
                        to="daily_reports.MultipleDailyReport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalMultipleDailyReportFile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("description", models.TextField(blank=True)),
                ("md5", models.TextField(blank=True)),
                ("upload", models.TextField(max_length=100)),
                ("uploaded_at", models.DateTimeField(blank=True, editable=False)),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("kind", models.CharField(blank=True, default="", max_length=100)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "multiple_daily_report",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="daily_reports.MultipleDailyReport",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical multiple daily report file",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
