# Generated by Django 2.2.28 on 2023-06-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0058_merge_20221111_1348"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportexport",
            name="order",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="dailyreportexport",
            name="sort",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="historicaldailyreportexport",
            name="order",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="historicaldailyreportexport",
            name="sort",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
