# Generated by Django 2.2.28 on 2023-10-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0059_auto_20230629_1232"),
        ("daily_reports", "0059_fill_header_info"),
    ]

    operations = []
