# Generated by Django 2.2.28 on 2023-11-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0060_merge_20231018_1027"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportexport",
            name="format",
            field=models.CharField(
                choices=[("PDF", "PDF"), ("EXCEL", "EXCEL")],
                default="EXCEL",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportexport",
            name="format",
            field=models.CharField(
                choices=[("PDF", "PDF"), ("EXCEL", "EXCEL")],
                default="EXCEL",
                max_length=5,
            ),
        ),
    ]
