# Generated by Django 2.2.28 on 2023-12-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0060_merge_20231018_1027"),
        (
            "daily_reports",
            "0059_historicalmultipledailyreportfile_multipledailyreportfile",
        ),
    ]

    operations = []
