# Generated by Django 2.2.28 on 2024-01-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0061_auto_20231127_0805"),
        ("daily_reports", "0061_merge_20231206_1401"),
    ]

    operations = []
