# Generated by Django 2.2.28 on 2024-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0062_merge_20240112_1536"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalDailyReportExport",
        ),
    ]
