# Generated by Django 2.2.28 on 2024-10-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0063_delete_historicaldailyreportexport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyreportrelation",
            options={"ordering": ["multiple_daily_report__company"]},
        ),
        migrations.AlterModelOptions(
            name="dailyreportworker",
            options={"ordering": ["uuid"]},
        ),
    ]
