# Generated by Django 2.2.28 on 2024-10-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0064_auto_20241022_1051"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dailyreportrelation",
            constraint=models.UniqueConstraint(
                fields=("multiple_daily_report", "worker"), name="mdr_worker"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyreportrelation",
            constraint=models.UniqueConstraint(
                fields=("multiple_daily_report", "external_team"),
                name="mdr_external_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyreportrelation",
            constraint=models.UniqueConstraint(
                fields=("multiple_daily_report", "equipment"), name="mdr_equipment"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyreportrelation",
            constraint=models.UniqueConstraint(
                fields=("multiple_daily_report", "vehicle"), name="mdr_vehicle"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyreportrelation",
            constraint=models.UniqueConstraint(
                fields=("multiple_daily_report", "signaling"), name="mdr_signaling"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyreportrelation",
            constraint=models.UniqueConstraint(
                fields=("multiple_daily_report", "occurrence"), name="mdr_occurrence"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyreportrelation",
            constraint=models.UniqueConstraint(
                fields=("multiple_daily_report", "resource"), name="mdr_resource"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyreportrelation",
            constraint=models.UniqueConstraint(
                fields=("multiple_daily_report", "production_goal"),
                name="mdr_production_goal",
            ),
        ),
    ]
