# Generated by Django 2.2.28 on 2024-12-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0065_auto_20241025_1440"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportequipment",
            name="unit_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreportvehicle",
            name="unit_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyreportworker",
            name="unit_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportequipment",
            name="unit_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportvehicle",
            name="unit_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportworker",
            name="unit_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
