# Generated by Django 2.2.28 on 2025-02-26 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daily_reports",
            "0068_historicalmultipledailyreportsignature_multipledailyreportsignature",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreportoccurrence",
            name="impact_duration",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_format",
                        message="Formato inválido. Preencha o campo no formato esperado HH:MM",
                        regex="^\\d{2}:\\d{2}(:\\d{2})?$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportoccurrence",
            name="impact_duration",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_format",
                        message="Formato inválido. Preencha o campo no formato esperado HH:MM",
                        regex="^\\d{2}:\\d{2}(:\\d{2})?$",
                    )
                ],
            ),
        ),
    ]
