# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "daily_reports",
            "0068_historicalmultipledailyreportsignature_multipledailyreportsignature",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaldailyreport",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical daily report",
                "verbose_name_plural": "historical daily reports",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldailyreportcontractusage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical daily report contract usage",
                "verbose_name_plural": "historical daily report contract usages",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldailyreportequipment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical daily report equipment",
                "verbose_name_plural": "historical Daily report equipment",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldailyreportexternalteam",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical daily report external team",
                "verbose_name_plural": "historical daily report external teams",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldailyreportoccurrence",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical daily report occurrence",
                "verbose_name_plural": "historical daily report occurrences",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldailyreportrelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical daily report relation",
                "verbose_name_plural": "historical daily report relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldailyreportresource",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical daily report resource",
                "verbose_name_plural": "historical daily report resources",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldailyreportsignaling",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical daily report signaling",
                "verbose_name_plural": "historical Daily report signaling",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldailyreportvehicle",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical daily report vehicle",
                "verbose_name_plural": "historical daily report vehicles",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldailyreportworker",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical daily report worker",
                "verbose_name_plural": "historical daily report workers",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmultipledailyreport",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical multiple daily report",
                "verbose_name_plural": "historical multiple daily reports",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmultipledailyreportfile",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical multiple daily report file",
                "verbose_name_plural": "historical multiple daily report files",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmultipledailyreportsignature",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical multiple daily report signature",
                "verbose_name_plural": "historical multiple daily report signatures",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproductiongoal",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical production goal",
                "verbose_name_plural": "historical production goals",
            },
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="header_info",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="identification",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="header_info",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreport",
            name="identification",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportcontractusage",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportequipment",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportexternalteam",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportoccurrence",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportrelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportresource",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportsignaling",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportvehicle",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldailyreportworker",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreport",
            name="header_info",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreport",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreportfile",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreportsignature",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalproductiongoal",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="multipledailyreport",
            name="header_info",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
