# Generated by Django 3.2.25 on 2025-05-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0069_auto_20250226_1629"),
        ("daily_reports", "0069_auto_20250227_1243"),
    ]

    operations = []
