# Generated by Django 3.2.25 on 2025-05-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0070_merge_0069_auto_20250226_1629_0069_auto_20250227_1243"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportequipment",
            name="extra_hours",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="dailyreportvehicle",
            name="extra_hours",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="dailyreportworker",
            name="extra_hours",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportequipment",
            name="extra_hours",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportvehicle",
            name="extra_hours",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="historicaldailyreportworker",
            name="extra_hours",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
