# Generated by Django 3.2.25 on 2025-09-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0071_auto_20250516_1500"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmultipledailyreport",
            name="compensation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="multipledailyreport",
            name="compensation",
            field=models.BooleanField(default=False),
        ),
    ]
