# Generated by Django 3.2.25 on 2025-08-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_usersignature"),
        ("daily_reports", "0071_auto_20250516_1500"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmultipledailyreportsignature",
            name="user_signature",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="users.usersignature",
            ),
        ),
        migrations.AddField(
            model_name="multipledailyreportsignature",
            name="user_signature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="multiple_daily_report_user_signatures",
                to="users.usersignature",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmultipledailyreportsignature",
            name="signature_name",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="multipledailyreportsignature",
            name="signature_name",
            field=models.TextField(blank=True),
        ),
    ]
