# Generated by Django 3.2.25 on 2025-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0071_auto_20250516_1500"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmultipledailyreport",
            name="legacy_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="multipledailyreport",
            name="legacy_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
