# Generated by Django 3.2.25 on 2025-09-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0072_auto_20250808_1335"),
        ("daily_reports", "0072_auto_20250909_1951"),
    ]

    operations = []
