# Generated by Django 3.2.25 on 2025-10-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0072_auto_20250916_1750"),
        ("daily_reports", "0073_merge_0072_auto_20250808_1335_0072_auto_20250909_1951"),
    ]

    operations = []
