# Generated by Django 3.2.25 on 2025-10-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0073_merge_0072_auto_20250808_1335_0072_auto_20250909_1951"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmultipledailyreportfile",
            name="legacy_uuid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="multipledailyreportfile",
            name="legacy_uuid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
