# Generated by Django 3.2.25 on 2025-10-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0074_merge_20251013_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportexport",
            name="export_photos",
            field=models.BooleanField(default=True),
        ),
    ]
