# Generated by Django 3.2.25 on 2025-10-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0074_auto_20251008_2002"),
        ("daily_reports", "0074_merge_20251013_1322"),
    ]

    operations = []
