# Generated by Django 3.2.25 on 2025-10-14 16:48

import uuid

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0064_merge_0063_auto_20250804_1317_0063_reportingbulkedit"),
        ("daily_reports", "0074_merge_20251013_1322"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMultipleDailyReport_reportings",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "m2m_history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="daily_reports.historicalmultipledailyreport",
                    ),
                ),
                (
                    "multipledailyreport",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="daily_reports.multipledailyreport",
                    ),
                ),
                (
                    "reporting",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="reportings.reporting",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalMultipleDailyReport_reportings",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
