# Generated by Django 3.2.25 on 2025-10-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0075_historicalmultipledailyreport_reportings"),
        ("daily_reports", "0075_merge_20251021_1655"),
    ]

    operations = []
