# Generated by Django 3.2.25 on 2025-11-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0075_dailyreportexport_export_photos"),
        ("daily_reports", "0076_merge_20251024_1856"),
    ]

    operations = []
