# Generated by Django 3.2.25 on 2026-01-26 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0077_merge_20251106_1710"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreportcontractusage",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Denormalized from worker/equipment/vehicle for query optimization",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_usages",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportcontractusage",
            name="contract_item_administration",
            field=models.ForeignKey(
                blank=True,
                help_text="Denormalized from worker/equipment/vehicle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_usages",
                to="resources.contractitemadministration",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportcontractusage",
            name="daily_reports",
            field=models.ManyToManyField(
                blank=True,
                help_text="Denormalized M2M from worker/equipment/vehicle",
                related_name="contract_usages",
                to="daily_reports.DailyReport",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportcontractusage",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                help_text="Only relevant for workers, null for equipment/vehicle",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_usages",
                to="companies.firm",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportcontractusage",
            name="measurement_bulletin",
            field=models.ForeignKey(
                blank=True,
                help_text="Denormalized from worker/equipment/vehicle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_usages",
                to="service_orders.measurementbulletin",
            ),
        ),
        migrations.AddField(
            model_name="dailyreportcontractusage",
            name="multiple_daily_reports",
            field=models.ManyToManyField(
                blank=True,
                help_text="Denormalized M2M from worker/equipment/vehicle",
                related_name="contract_usages",
                to="daily_reports.MultipleDailyReport",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportcontractusage",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Denormalized from worker/equipment/vehicle for query optimization",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportcontractusage",
            name="contract_item_administration",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Denormalized from worker/equipment/vehicle",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resources.contractitemadministration",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportcontractusage",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Only relevant for workers, null for equipment/vehicle",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.firm",
            ),
        ),
        migrations.AddField(
            model_name="historicaldailyreportcontractusage",
            name="measurement_bulletin",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Denormalized from worker/equipment/vehicle",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.measurementbulletin",
            ),
        ),
    ]
