# Generated by Django 3.2.25 on 2026-01-26 17:43

import time

from django.db import migrations


def populate_denormalized_fields(apps, schema_editor):
    """
    Populate denormalized fields in DailyReportContractUsage from related
    Worker/Equipment/Vehicle instances using raw SQL for optimal performance.

    This migration copies:
    - ForeignKey fields: company, contract_item_administration, firm, measurement_bulletin
    - ManyToMany fields: daily_reports, multiple_daily_reports
    """
    migration_start_time = time.time()
    print("Starting migration 0079...")

    BATCH_SIZE = 1000

    with schema_editor.connection.cursor() as cursor:
        # ==================================================
        # STEP 1: Update ForeignKeys from Workers
        # ==================================================
        step_start_time = time.time()
        print("Step 1: Updating ForeignKeys from Workers...")
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM daily_reports_dailyreportcontractusage cu
            WHERE cu.worker_id IS NOT NULL;
            """
        )
        total_workers = cursor.fetchone()[0]
        print(f"Total ContractUsages with workers: {total_workers}")

        if total_workers > 0:
            cursor.execute(
                """
                UPDATE daily_reports_dailyreportcontractusage cu
                SET
                    company_id = COALESCE(f.company_id, w.company_id),
                    firm_id = w.firm_id,
                    contract_item_administration_id = w.contract_item_administration_id,
                    measurement_bulletin_id = w.measurement_bulletin_id
                FROM daily_reports_dailyreportworker w
                LEFT JOIN companies_firm f ON w.firm_id = f.uuid
                WHERE cu.worker_id = w.uuid
                  AND cu.worker_id IS NOT NULL;
                """
            )
            print(f"Updated {cursor.rowcount} ContractUsages with Worker ForeignKeys")

        step_duration = time.time() - step_start_time
        print(f"Step 1 completed in {step_duration:.2f} seconds")

        # ==================================================
        # STEP 2: Update ForeignKeys from Equipment
        # ==================================================
        step_start_time = time.time()
        print("Step 2: Updating ForeignKeys from Equipment...")
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM daily_reports_dailyreportcontractusage cu
            WHERE cu.equipment_id IS NOT NULL;
            """
        )
        total_equipment = cursor.fetchone()[0]
        print(f"Total ContractUsages with equipment: {total_equipment}")

        if total_equipment > 0:
            cursor.execute(
                """
                UPDATE daily_reports_dailyreportcontractusage cu
                SET
                    company_id = e.company_id,
                    firm_id = NULL,
                    contract_item_administration_id = e.contract_item_administration_id,
                    measurement_bulletin_id = e.measurement_bulletin_id
                FROM daily_reports_dailyreportequipment e
                WHERE cu.equipment_id = e.uuid
                  AND cu.equipment_id IS NOT NULL;
                """
            )
            print(
                f"Updated {cursor.rowcount} ContractUsages with Equipment ForeignKeys"
            )

        step_duration = time.time() - step_start_time
        print(f"Step 2 completed in {step_duration:.2f} seconds")

        # ==================================================
        # STEP 3: Update ForeignKeys from Vehicles
        # ==================================================
        step_start_time = time.time()
        print("Step 3: Updating ForeignKeys from Vehicles...")
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM daily_reports_dailyreportcontractusage cu
            WHERE cu.vehicle_id IS NOT NULL;
            """
        )
        total_vehicles = cursor.fetchone()[0]
        print(f"Total ContractUsages with vehicles: {total_vehicles}")

        if total_vehicles > 0:
            cursor.execute(
                """
                UPDATE daily_reports_dailyreportcontractusage cu
                SET
                    company_id = v.company_id,
                    firm_id = NULL,
                    contract_item_administration_id = v.contract_item_administration_id,
                    measurement_bulletin_id = v.measurement_bulletin_id
                FROM daily_reports_dailyreportvehicle v
                WHERE cu.vehicle_id = v.uuid
                  AND cu.vehicle_id IS NOT NULL;
                """
            )
            print(f"Updated {cursor.rowcount} ContractUsages with Vehicle ForeignKeys")

        step_duration = time.time() - step_start_time
        print(f"Step 3 completed in {step_duration:.2f} seconds")

        # ==================================================
        # STEP 4: Copy M2M daily_reports
        # Get all DailyReportRelation with daily_report_id, find matching ContractUsage
        # ==================================================
        step_start_time = time.time()
        print("Step 4: Copying M2M daily_reports...")

        cursor.execute(
            """
            INSERT INTO daily_reports_dailyreportcontractusage_daily_reports (
                dailyreportcontractusage_id, dailyreport_id
            )
            SELECT DISTINCT
                cu.uuid,
                dr.daily_report_id
            FROM daily_reports_dailyreportrelation dr
            INNER JOIN daily_reports_dailyreportcontractusage cu ON (
                cu.worker_id = dr.worker_id OR
                cu.equipment_id = dr.equipment_id OR
                cu.vehicle_id = dr.vehicle_id
            )
            WHERE dr.daily_report_id IS NOT NULL
              AND (dr.worker_id IS NOT NULL OR dr.equipment_id IS NOT NULL OR dr.vehicle_id IS NOT NULL)
              AND NOT EXISTS (
                  SELECT 1 FROM daily_reports_dailyreportcontractusage_daily_reports cudr
                  WHERE cudr.dailyreportcontractusage_id = cu.uuid
                    AND cudr.dailyreport_id = dr.daily_report_id
              );
            """
        )
        total_daily_reports = cursor.rowcount
        step_duration = time.time() - step_start_time
        print(
            f"Step 4 completed in {step_duration:.2f} seconds ({total_daily_reports} relationships)"
        )

        # ==================================================
        # STEP 5: Copy M2M multiple_daily_reports
        # Get all DailyReportRelation with multiple_daily_report_id, find matching ContractUsage
        # ==================================================
        step_start_time = time.time()
        print("Step 5: Copying M2M multiple_daily_reports...")

        cursor.execute(
            """
            INSERT INTO daily_reports_dailyreportcontractusage_multiple_daily_reports (
                dailyreportcontractusage_id, multipledailyreport_id
            )
            SELECT DISTINCT
                cu.uuid,
                dr.multiple_daily_report_id
            FROM daily_reports_dailyreportrelation dr
            INNER JOIN daily_reports_dailyreportcontractusage cu ON (
                cu.worker_id = dr.worker_id OR
                cu.equipment_id = dr.equipment_id OR
                cu.vehicle_id = dr.vehicle_id
            )
            WHERE dr.multiple_daily_report_id IS NOT NULL
              AND (dr.worker_id IS NOT NULL OR dr.equipment_id IS NOT NULL OR dr.vehicle_id IS NOT NULL)
              AND NOT EXISTS (
                  SELECT 1 FROM daily_reports_dailyreportcontractusage_multiple_daily_reports cumdr
                  WHERE cumdr.dailyreportcontractusage_id = cu.uuid
                    AND cumdr.multipledailyreport_id = dr.multiple_daily_report_id
              );
            """
        )
        total_multiple = cursor.rowcount
        step_duration = time.time() - step_start_time
        print(
            f"Step 5 completed in {step_duration:.2f} seconds ({total_multiple} relationships)"
        )

    # Migration summary
    total_duration = time.time() - migration_start_time
    minutes = int(total_duration // 60)
    seconds = int(total_duration % 60)
    print(
        f"Migration completed! Total time: {minutes}m {seconds}s "
        f"({total_duration:.1f}s)"
    )


def reverse_populate_denormalized_fields(_apps, schema_editor):
    """
    Reverse migration: clear all denormalized fields using raw SQL for optimal performance.
    """
    with schema_editor.connection.cursor() as cursor:
        print("Reversing migration: clearing denormalized fields...")

        # Clear ForeignKey fields
        print("Clearing ForeignKey fields...")
        cursor.execute(
            """
            UPDATE daily_reports_dailyreportcontractusage
            SET
                company_id = NULL,
                contract_item_administration_id = NULL,
                measurement_bulletin_id = NULL,
                firm_id = NULL;
            """
        )
        print(f"Cleared ForeignKeys for {cursor.rowcount} ContractUsages")

        # Clear M2M daily_reports
        print("Clearing M2M daily_reports...")
        cursor.execute(
            """
            DELETE FROM daily_reports_dailyreportcontractusage_daily_reports;
            """
        )
        print(f"Cleared {cursor.rowcount} daily_reports M2M relationships")

        # Clear M2M multiple_daily_reports
        print("Clearing M2M multiple_daily_reports...")
        cursor.execute(
            """
            DELETE FROM daily_reports_dailyreportcontractusage_multiple_daily_reports;
            """
        )
        print(f"Cleared {cursor.rowcount} multiple_daily_reports M2M relationships")

        print("Reverse migration completed successfully!")


class Migration(migrations.Migration):

    dependencies = [
        ("daily_reports", "0078_add_denormalized_m2m_fields_to_contract_usage"),
    ]

    operations = [
        migrations.RunPython(
            populate_denormalized_fields,
            reverse_code=reverse_populate_denormalized_fields,
        ),
    ]
