# Generated by Django 2.1.2 on 2021-01-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("scarface", "0004_auto_20151217_1131")]

    operations = [
        migrations.CreateModel(
            name="ZASArea",
            fields=[
                (
                    "plant_initials",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("plant_full_name", models.TextField()),
                (
                    "push_devices",
                    models.ManyToManyField(
                        blank=True,
                        related_name="device_plant",
                        to="scarface.Device",
                    ),
                ),
            ],
        )
    ]
