# Generated by Django 2.1.2 on 2021-01-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zas", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="zasarea",
            old_name="plant_full_name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="zasarea", old_name="plant_initials", new_name="initials"
        ),
        migrations.AddField(
            model_name="zasarea",
            name="threshold_value",
            field=models.IntegerField(default=700),
        ),
        migrations.AddField(
            model_name="zasarea",
            name="threshold_variable",
            field=models.CharField(default="nivelCanalFuga", max_length=50),
        ),
        migrations.AlterField(
            model_name="zasarea",
            name="push_devices",
            field=models.ManyToManyField(
                blank=True, related_name="device_zas", to="scarface.Device"
            ),
        ),
    ]
