# Generated by Django 2.1.2 on 2021-02-06 00:44

import datetime
import uuid

import django.contrib.postgres.fields.jsonb
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zas", "0002_auto_20210125_1038")]

    operations = [
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "logic",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                ("description", models.TextField()),
                (
                    "cooldown",
                    models.DurationField(default=datetime.timedelta(0, 1800)),
                ),
                (
                    "severity",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "warning_type",
                    models.CharField(
                        choices=[
                            ("FLOOD", "Inundação"),
                            ("MISCELLANEOUS", "Outros"),
                        ],
                        default="FLOOD",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="zasarea", name="threshold_value"),
        migrations.RemoveField(model_name="zasarea", name="threshold_variable"),
        migrations.AddField(
            model_name="threshold",
            name="zas_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="zas.ZASArea"
            ),
        ),
    ]
