# Generated by Django 2.1.2 on 2021-02-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zas", "0003_auto_20210205_2144")]

    operations = [
        migrations.AddField(
            model_name="threshold",
            name="latest_alert_created_at",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
