# Generated by Django 2.1.2 on 2021-04-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zas", "0004_threshold_latest_alert_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="zasarea",
            name="sms_devices",
            field=models.ManyToManyField(
                blank=True, related_name="zas_areas", to="zas.SMSDevice"
            ),
        ),
    ]
