# Generated by Django 2.1.2 on 2021-04-13 11:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zas", "0005_auto_20210409_1007"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smsdevice",
            name="id",
        ),
        migrations.AddField(
            model_name="smsdevice",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
