# Generated by Django 2.2.23 on 2021-09-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("zas", "0006_auto_20210413_0822")]

    operations = [migrations.RemoveField(model_name="zasarea", name="sms_devices")]
