# Generated by Django 2.2.23 on 2021-09-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("zas", "0007_remove_zasarea_sms_devices")]

    operations = [
        migrations.AddField(
            model_name="zasarea",
            name="sms_devices",
            field=models.ManyToManyField(
                blank=True, related_name="zas_areas", to="zas.SMSDevice"
            ),
        )
    ]
