# Generated by Django 3.2.25 on 2024-04-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zas", "0008_zasarea_sms_devices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threshold",
            name="logic",
            field=models.JSONField(default=dict),
        ),
    ]
