# Generated by Django 3.2.25 on 2025-05-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_migrate_userpush_data"),
        ("zas", "0009_alter_threshold_logic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zasarea",
            name="push_devices",
            field=models.ManyToManyField(
                blank=True, related_name="device_zas", to="notifications.Device"
            ),
        ),
    ]
