# Generated by Django 3.2.25 on 2025-12-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zas", "0010_alter_zasarea_push_devices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="threshold",
            name="zas_area",
        ),
        migrations.RemoveField(
            model_name="zasarea",
            name="push_devices",
        ),
        migrations.RemoveField(
            model_name="zasarea",
            name="sms_devices",
        ),
        migrations.DeleteModel(
            name="SMSDevice",
        ),
        migrations.DeleteModel(
            name="Threshold",
        ),
        migrations.DeleteModel(
            name="ZASArea",
        ),
    ]
