# Generated by Django 2.1.2 on 2019-03-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltemplate",
            name="item_name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="model_name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="template",
            name="item_name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="template",
            name="model_name",
            field=models.CharField(max_length=60),
        ),
    ]
