# Generated by Django 2.1.2 on 2019-05-02 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0003_historicallog_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_log",
                to="companies.Company",
            ),
        ),
    ]
