# Generated by Django 2.1.2 on 2019-12-02 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("templates", "0005_auto_20191202_1016")]

    operations = [
        migrations.AlterModelOptions(
            name="canvascard",
            options={
                "get_latest_by": ["created_at"],
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="canvaslist",
            options={
                "get_latest_by": ["created_at"],
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="canvascard",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="canvaslist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcanvascard",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcanvaslist",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
    ]
