# Generated by Django 2.1.2 on 2019-12-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("templates", "0007_auto_20191202_1552")]

    operations = [
        migrations.AddField(
            model_name="canvaslist",
            name="color",
            field=models.CharField(default="#FF0000", max_length=100),
        ),
        migrations.AddField(
            model_name="historicalcanvaslist",
            name="color",
            field=models.CharField(default="#FF0000", max_length=100),
        ),
        migrations.AlterField(
            model_name="canvascard",
            name="color",
            field=models.CharField(default="#FF0000", max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalcanvascard",
            name="color",
            field=models.CharField(default="#FF0000", max_length=100),
        ),
    ]
