# Generated by Django 2.1.2 on 2020-03-07 18:17

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates", "0008_auto_20191203_1304"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notification_title", models.TextField(blank=True, null=True)),
                ("notification_body", models.TextField(blank=True, null=True)),
                ("target_app", models.TextField(blank=True, null=True)),
                ("target_platform", models.TextField(blank=True, null=True)),
                (
                    "start_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "version",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalAppVersion",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("notification_title", models.TextField(blank=True, null=True)),
                ("notification_body", models.TextField(blank=True, null=True)),
                ("target_app", models.TextField(blank=True, null=True)),
                ("target_platform", models.TextField(blank=True, null=True)),
                (
                    "start_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "version",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical app version",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
