# Generated by Django 2.1.2 on 2020-06-03 13:50

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0033_auto_20200521_0005"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates", "0009_appversion_historicalappversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportRequest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.TextField(blank=True, null=True)),
                (
                    "json_zip",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_export_requests",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_export_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
