# Generated by Django 2.1.2 on 2020-06-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0010_exportrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportrequest",
            name="error",
            field=models.BooleanField(default=False),
        ),
    ]
