# Generated by Django 2.1.2 on 2020-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "templates",
            "0012_historicalexportrequest_historicalmobilesync_mobilesync",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmobilesync",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mobilesync",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
