# Generated by Django 2.1.2 on 2020-12-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scarface", "0004_auto_20151217_1131"),
        ("templates", "0014_actionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZASArea",
            fields=[
                (
                    "plant_initials",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("plant_full_name", models.TextField()),
                (
                    "push_devices",
                    models.ManyToManyField(
                        related_name="device_plant", to="scarface.Device"
                    ),
                ),
            ],
        )
    ]
