# Generated by Django 2.1.2 on 2020-12-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("templates", "0015_zasarea")]

    operations = [
        migrations.AlterField(
            model_name="zasarea",
            name="push_devices",
            field=models.ManyToManyField(
                blank=True, related_name="device_plant", to="scarface.Device"
            ),
        )
    ]
