# Generated by Django 2.1.2 on 2021-01-05 23:54

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scarface", "0004_auto_20151217_1131"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates", "0015_zasarea"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalQueuedPushAlert",
            fields=[
                (
                    "pushmessage_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="scarface.PushMessage",
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("sound", models.TextField(blank=True, null=True)),
                ("message", models.TextField(default="", null=True)),
                ("has_new_content", models.BooleanField(default=False)),
                ("context_id", models.TextField(default="none", null=True)),
                ("context", models.TextField(default="default", null=True)),
                ("badge_count", models.SmallIntegerField(default=0)),
                ("extra_payload", models.TextField(blank=True, null=True)),
                ("receiver_arn", models.TextField(blank=True, null=True)),
                ("message_type", models.PositiveSmallIntegerField(default=0)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical queued push alert",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="QueuedPushAlert",
            fields=[
                (
                    "pushmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="scarface.PushMessage",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            bases=("scarface.pushmessage",),
        ),
        migrations.AlterField(
            model_name="zasarea",
            name="push_devices",
            field=models.ManyToManyField(
                blank=True, related_name="device_plant", to="scarface.Device"
            ),
        ),
        migrations.AddField(
            model_name="queuedpushalert",
            name="zas_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="templates.ZASArea"
            ),
        ),
        migrations.AddField(
            model_name="historicalqueuedpushalert",
            name="zas_area",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="templates.ZASArea",
            ),
        ),
    ]
