# Generated by Django 2.1.2 on 2021-01-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0016_auto_20210105_2054"),
    ]

    operations = [
        migrations.AddField(
            model_name="zasarea",
            name="threshold_value",
            field=models.IntegerField(default=700),
        ),
        migrations.AddField(
            model_name="zasarea",
            name="threshold_variable",
            field=models.CharField(default="nivelCanalFuga", max_length=50),
        ),
    ]
