# Generated by Django 2.1.2 on 2021-01-24 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0017_auto_20210119_0950"),
        ("templates", "0016_auto_20201221_1443"),
    ]

    operations = []
