# Generated by Django 2.1.2 on 2021-01-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0018_merge_20210124_2038"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalqueuedpushalert",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalqueuedpushalert",
            name="pushmessage_ptr",
        ),
        migrations.RemoveField(
            model_name="historicalqueuedpushalert",
            name="zas_area",
        ),
        migrations.RemoveField(
            model_name="queuedpushalert",
            name="pushmessage_ptr",
        ),
        migrations.RemoveField(
            model_name="queuedpushalert",
            name="zas_area",
        ),
        migrations.RemoveField(
            model_name="zasarea",
            name="push_devices",
        ),
        migrations.DeleteModel(
            name="HistoricalQueuedPushAlert",
        ),
        migrations.DeleteModel(
            name="QueuedPushAlert",
        ),
        migrations.DeleteModel(
            name="ZASArea",
        ),
    ]
