# Generated by Django 2.1.2 on 2021-03-11 14:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0039_auto_20210218_1701"),
        ("templates", "0019_auto_20210126_1025"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTag",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("select_option", "select_option"),
                            ("text_field", "text_field"),
                        ],
                        default="select_option",
                        max_length=100,
                    ),
                ),
                ("level", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_tags",
                        to="companies.Company",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_tags",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
                (
                    "parent_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="child_tags",
                        to="templates.SearchTag",
                    ),
                ),
            ],
        )
    ]
