# Generated by Django 2.1.2 on 2021-03-11 19:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0053_auto_20210219_0733"),
        ("companies", "0039_auto_20210218_1701"),
        ("templates", "0020_searchtag"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTagOccurrenceType",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.Company",
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_tag_relationships",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="searchtag",
            name="form",
        ),
        migrations.AddField(
            model_name="searchtagoccurrencetype",
            name="search_tags",
            field=models.ManyToManyField(
                related_name="occurrence_type_relationships", to="templates.SearchTag"
            ),
        ),
    ]
