# Generated by Django 2.1.2 on 2021-04-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0021_auto_20210311_1645"),
        ("templates", "0020_auto_20210322_0746"),
    ]

    operations = []
