# Generated by Django 2.1.2 on 2021-05-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0022_merge_20210422_1352"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchtag",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
