# Generated by Django 2.1.2 on 2021-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0023_searchtag_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchtag",
            name="redirect",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="searchtag",
            name="kind",
            field=models.CharField(
                choices=[
                    ("select_option", "select_option"),
                    ("text_field", "text_field"),
                    ("redirect", "redirect"),
                ],
                default="select_option",
                max_length=100,
            ),
        ),
    ]
