# Generated by Django 2.2.23 on 2021-07-30 13:25

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0093_auto_20210601_1514"),
        ("companies", "0042_populate_firm_created_by"),
        ("templates", "0025_auto_20210727_0841"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpdfimport",
            name="branch",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpdfimport",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalpdfimport",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.Firm",
            ),
        ),
        migrations.AddField(
            model_name="historicalpdfimport",
            name="form_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalpdfimport",
            name="kind",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="historicalpdfimport",
            name="km_reference",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpdfimport",
            name="lane",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalpdfimport",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
        migrations.AddField(
            model_name="historicalpdfimport",
            name="track",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pdfimport",
            name="branch",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pdfimport",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pdfimport",
            name="firm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pdf_imports",
                to="companies.Firm",
            ),
        ),
        migrations.AddField(
            model_name="pdfimport",
            name="form_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="pdfimport",
            name="kind",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="pdfimport",
            name="km_reference",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pdfimport",
            name="lane",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pdfimport",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pdf_imports",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
        migrations.AddField(
            model_name="pdfimport",
            name="track",
            field=models.TextField(blank=True, null=True),
        ),
    ]
