# Generated by Django 2.2.23 on 2021-08-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("templates", "0026_auto_20210730_1025")]

    operations = [
        migrations.RemoveField(model_name="historicalpdfreporting", name="operation"),
        migrations.RemoveField(model_name="historicalpdfreporting", name="row"),
        migrations.RemoveField(model_name="pdfreporting", name="operation"),
        migrations.RemoveField(model_name="pdfreporting", name="row"),
    ]
