# Generated by Django 2.2.23 on 2021-08-06 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0063_auto_20210610_2157"),
        ("templates", "0027_auto_20210806_1141"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpdfimport",
            name="occurrence_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="occurrence_records.OccurrenceType",
            ),
        ),
        migrations.AddField(
            model_name="pdfimport",
            name="occurrence_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pdf_import_occurrence",
                to="occurrence_records.OccurrenceType",
            ),
        ),
    ]
