# Generated by Django 2.2.23 on 2021-08-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("templates", "0028_auto_20210806_1526")]

    operations = [
        migrations.RemoveField(model_name="pdfreporting", name="pdf_import"),
        migrations.RemoveField(model_name="pdfreporting", name="reporting"),
        migrations.RemoveField(model_name="pdfimport", name="reportings"),
        migrations.DeleteModel(name="HistoricalPDFReporting"),
        migrations.DeleteModel(name="PDFReporting"),
    ]
