# Generated by Django 2.2.23 on 2021-11-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0063_auto_20210610_2157"),
        ("templates", "0030_csvimport_historicalcsvimport"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvimport",
            name="occurrence_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_csv_imports",
                to="occurrence_records.OccurrenceType",
            ),
        ),
        migrations.AddField(
            model_name="historicalcsvimport",
            name="occurrence_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="occurrence_records.OccurrenceType",
            ),
        ),
    ]
