# Generated by Django 2.2.23 on 2021-11-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("templates", "0031_auto_20211103_0849")]

    operations = [
        migrations.RemoveField(model_name="csvimport", name="firm"),
        migrations.RemoveField(model_name="historicalcsvimport", name="firm"),
    ]
