# Generated by Django 2.2.23 on 2023-06-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0032_auto_20211130_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelimport",
            name="generating_preview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalexcelimport",
            name="generating_preview",
            field=models.BooleanField(default=False),
        ),
    ]
