# Generated by Django 2.2.23 on 2023-05-30 21:20

from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0032_auto_20211130_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportrequest",
            name="file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="historicalexportrequest",
            name="file",
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
