# Generated by Django 2.2.23 on 2023-06-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0033_auto_20230530_1820"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportrequest",
            name="url",
        ),
        migrations.RemoveField(
            model_name="historicalexportrequest",
            name="url",
        ),
    ]
