# Generated by Django 2.2.28 on 2024-01-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0034_auto_20230601_1437"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportrequest",
            name="url",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalexportrequest",
            name="url",
            field=models.TextField(blank=True),
        ),
    ]
