# Generated by Django 2.2.28 on 2024-04-02 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0033_auto_20230622_1459"),
        ("templates", "0035_auto_20240117_0958"),
    ]

    operations = []
