# Generated by Django 2.2.28 on 2024-04-02 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("templates", "0036_merge_20240402_1543"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportrequest",
            name="url",
        ),
        migrations.RemoveField(
            model_name="historicalexportrequest",
            name="url",
        ),
    ]
