# Generated by Django 2.2.28 on 2024-06-17 18:39

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0064_merge_20240430_1604"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates", "0037_auto_20240402_1543"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingExport",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "export_type",
                    models.CharField(
                        choices=[("SIMPLE", "SIMPLE"), ("NORMAL", "NORMAL")],
                        default="SIMPLE",
                        max_length=100,
                    ),
                ),
                (
                    "extra_info",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                ("is_inventory", models.BooleanField(default=False)),
                (
                    "filters",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                ("done", models.BooleanField(default=False)),
                ("error", models.BooleanField(default=False)),
                (
                    "exported_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_reporting_exports",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_reporting_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
