# Generated by Django 2.2.28 on 2024-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0037_auto_20240402_1543"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalexcelreporting",
            name="excel_import",
        ),
        migrations.RemoveField(
            model_name="historicalexcelreporting",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalexcelreporting",
            name="reporting",
        ),
        migrations.RemoveField(
            model_name="historicalexportrequest",
            name="company",
        ),
        migrations.RemoveField(
            model_name="historicalexportrequest",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalexportrequest",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicallog",
            name="company",
        ),
        migrations.RemoveField(
            model_name="historicallog",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="HistoricalExcelImport",
        ),
        migrations.DeleteModel(
            name="HistoricalExcelReporting",
        ),
        migrations.DeleteModel(
            name="HistoricalExportRequest",
        ),
        migrations.DeleteModel(
            name="HistoricalLog",
        ),
    ]
