# Generated by Django 2.2.28 on 2024-08-06 18:28

from django.db import migrations
from django_bulk_update.helper import bulk_update
from tqdm import tqdm


def populate_user_permission_with_reporting_export(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Company = apps.get_model("companies", "Company")
    company_qs = Company.objects.using(db_alias).filter(
        company_group__mobile_app="road"
    )
    UserPermission = apps.get_model("permissions", "UserPermission")
    user_permission_qs = (
        UserPermission.objects.using(db_alias)
        .filter(companies__in=company_qs)
        .distinct()
    )

    updated_items = []
    reporting_export_value = {
        "can_edit": True,
        "can_view": True,
        "queryset": "all",
        "can_create": True,
        "can_delete": True,
    }
    for user_permission in tqdm(user_permission_qs):
        user_permission.permissions.update({"ReportingExport": reporting_export_value})
        updated_items.append(user_permission)

    if updated_items:
        bulk_update(updated_items, batch_size=100, update_fields=["permissions"])


def reverse_populate_user_permission_with_reporting_export(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Company = apps.get_model("companies", "Company")
    company_qs = Company.objects.using(db_alias).filter(
        company_group__mobile_app="road"
    )
    UserPermission = apps.get_model("permissions", "UserPermission")
    user_permission_qs = (
        UserPermission.objects.using(db_alias)
        .filter(companies__in=company_qs)
        .distinct()
    )

    updated_items = []
    for user_permission in tqdm(user_permission_qs):
        if "ReportingExport" in user_permission.permissions:
            user_permission.permissions.pop("ReportingExport", None)
            updated_items.append(user_permission)

    if updated_items:
        bulk_update(updated_items, batch_size=100, update_fields=["permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0038_reportingexport"),
    ]
    operations = [
        migrations.RunPython(
            populate_user_permission_with_reporting_export,
            reverse_code=reverse_populate_user_permission_with_reporting_export,
        )
    ]
