# Generated by Django 2.2.28 on 2024-09-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0038_auto_20240808_1040"),
        ("templates", "0039_fill_reporting_export_permission"),
    ]

    operations = []
