# Generated by Django 2.2.28 on 2024-10-10 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0059_merge_20240912_1801"),
        ("templates", "0040_merge_20240913_1628"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpdfimport",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="reportings.RecordMenu",
            ),
        ),
        migrations.AddField(
            model_name="pdfimport",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pdf_imports",
                to="reportings.RecordMenu",
            ),
        ),
    ]
