# Generated by Django 2.2.28 on 2024-10-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0040_merge_20240913_1628"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelimport",
            name="is_over_limit",
            field=models.BooleanField(default=False),
        ),
    ]
