# Generated by Django 2.2.28 on 2024-10-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0041_excelimport_is_over_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelimport",
            name="is_forbidden",
            field=models.BooleanField(default=False),
        ),
    ]
