# Generated by Django 2.2.28 on 2024-12-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0042_excelimport_is_forbidden"),
        ("templates", "0041_auto_20241001_1608"),
    ]

    operations = []
