# Generated by Django 2.2.28 on 2025-02-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0043_merge_20241202_1539"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmobilesync",
            name="connection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "unknown"),
                    ("cellular", "cellular"),
                    ("wifi", "wifi"),
                    ("bluetooth", "bluetooth"),
                    ("ethernet", "ethernet"),
                    ("wimax", "wimax"),
                    ("vpn", "vpn"),
                    ("other", "other"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalmobilesync",
            name="has_error",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalmobilesync",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmobilesync",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmobilesync",
            name="speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmobilesync",
            name="time_spent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmobilesync",
            name="version",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilesync",
            name="connection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "unknown"),
                    ("cellular", "cellular"),
                    ("wifi", "wifi"),
                    ("bluetooth", "bluetooth"),
                    ("ethernet", "ethernet"),
                    ("wimax", "wimax"),
                    ("vpn", "vpn"),
                    ("other", "other"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mobilesync",
            name="has_error",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mobilesync",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilesync",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilesync",
            name="speed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilesync",
            name="time_spent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobilesync",
            name="version",
            field=models.TextField(blank=True, null=True),
        ),
    ]
