# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0044_auto_20250204_1604"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalappversion",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical app version",
                "verbose_name_plural": "historical app versions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcanvascard",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical canvas card",
                "verbose_name_plural": "historical canvas cards",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcanvaslist",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical canvas list",
                "verbose_name_plural": "historical canvas lists",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcsvimport",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical csv import",
                "verbose_name_plural": "historical csv imports",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmobilesync",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical mobile sync",
                "verbose_name_plural": "historical mobile syncs",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpdfimport",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical pdf import",
                "verbose_name_plural": "historical pdf imports",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltemplate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical template",
                "verbose_name_plural": "historical templates",
            },
        ),
        migrations.AlterField(
            model_name="appversion",
            name="version",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="canvascard",
            name="extra_info",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="csvimport",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="exportrequest",
            name="json_zip",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalappversion",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalappversion",
            name="version",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcanvascard",
            name="extra_info",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcanvascard",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcanvaslist",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcsvimport",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcsvimport",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmobilesync",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpdfimport",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpdfimport",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="options",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="validation",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="description",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="pdfimport",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="reportingexport",
            name="extra_info",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="reportingexport",
            name="filters",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="template",
            name="options",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="validation",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
