# Generated by Django 2.2.28 on 2025-02-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0044_auto_20250204_1604"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="actionlog",
            index=models.Index(
                fields=["created_at"], name="templates_a_created_e7f143_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionlog",
            index=models.Index(fields=["user"], name="templates_a_user_id_0d9cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="actionlog",
            index=models.Index(
                fields=["company"], name="templates_a_company_c34cd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionlog",
            index=models.Index(
                fields=["company_group"], name="templates_a_company_b55d67_idx"
            ),
        ),
    ]
