# Generated by Django 2.2.28 on 2025-04-14 15:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0047_auto_20250227_0958"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelContractItemUnitPrice",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row", models.CharField(blank=True, max_length=60, null=True)),
                ("operation", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "contract_item_unit_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_contract_items_unit_price",
                        to="resources.ContractItemUnitPrice",
                    ),
                ),
                (
                    "excel_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_contract_items_unit_price",
                        to="templates.ExcelImport",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="excelimport",
            name="contract_items_unit_price",
            field=models.ManyToManyField(
                related_name="excel_imports",
                through="templates.ExcelContractItemUnitPrice",
                to="resources.ContractItemUnitPrice",
            ),
        ),
    ]
