# Generated by Django 3.2.25 on 2025-05-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0045_auto_20250227_1243"),
        ("templates", "0048_auto_20250414_1258"),
    ]

    operations = []
