# Generated by Django 3.2.25 on 2025-05-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0049_merge_0045_auto_20250227_1243_0048_auto_20250414_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmobilesync",
            name="sync_post_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="mobilesync",
            name="sync_post_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
