# Generated by Django 3.2.25 on 2025-06-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0050_auto_20250509_2128"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmobilesync",
            name="sync_get_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="mobilesync",
            name="sync_get_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
