# Generated by Django 3.2.25 on 2025-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0051_auto_20250608_2224"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelimport",
            name="done_zip_upload",
            field=models.BooleanField(default=False),
        ),
    ]
