# Generated by Django 3.2.25 on 2025-07-21 23:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0063_auto_20250721_2049"),
        ("templates", "0051_auto_20250608_2224"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelContractItemAdministration",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row", models.CharField(blank=True, max_length=60, null=True)),
                ("operation", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "contract_item_administration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_contract_items_administration",
                        to="resources.contractitemadministration",
                    ),
                ),
                (
                    "excel_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excel_contract_items_administration",
                        to="templates.excelimport",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="excelimport",
            name="contract_items_administration",
            field=models.ManyToManyField(
                related_name="excel_imports",
                through="templates.ExcelContractItemAdministration",
                to="resources.ContractItemAdministration",
            ),
        ),
    ]
