# Generated by Django 3.2.25 on 2025-08-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0052_excelimport_done_zip_upload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="excelimport",
            old_name="done_zip_upload",
            new_name="uploading_zip_images",
        ),
    ]
