# Generated by Django 3.2.25 on 2025-08-07 15:16

from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0053_rename_done_zip_upload_excelimport_uploading_zip_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelimport",
            name="zip_file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                upload_to="",
            ),
        ),
    ]
