# Generated by Django 3.2.25 on 2025-09-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0052_auto_20250721_2049"),
        ("templates", "0054_excelimport_zip_file"),
    ]

    operations = []
