# Generated by Django 3.2.25 on 2025-09-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0055_merge_20250902_1542"),
        ("templates", "0055_merge_20250902_1615"),
    ]

    operations = []
