# Generated by Django 3.2.25 on 2025-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0056_merge_20250904_1950"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelimport",
            name="remaining_parts",
            field=models.IntegerField(default=0),
        ),
    ]
