# Generated by Django 3.2.25 on 2025-10-09 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0075_merge_0074_auto_20250604_1735_0074_auto_20250909_1951"),
        ("occurrence_records", "0102_auto_20250724_1840"),
        ("templates", "0057_excelimport_remaining_parts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfimport",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pdf_imports",
                to="companies.firm",
            ),
        ),
        migrations.AlterField(
            model_name="pdfimport",
            name="occurrence_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pdf_import_occurrence",
                to="occurrence_records.occurrencetype",
            ),
        ),
    ]
