# Generated by Django 3.2.25 on 2025-10-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0057_excelimport_remaining_parts"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmobilesync",
            name="sync_steps_duration_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="mobilesync",
            name="sync_steps_duration_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
