# Generated by Django 3.2.25 on 2025-10-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0058_auto_20251009_1651"),
        ("templates", "0058_auto_20251020_2202"),
    ]

    operations = []
