# Generated by Django 3.2.25 on 2026-03-02 16:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0075_merge_0074_auto_20250604_1735_0074_auto_20250909_1951"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("templates", "0060_exceldnitreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoReport",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("ArtespReport", "ArtespReport"),
                            ("NewPhotoReport", "NewPhotoReport"),
                        ],
                        default="NewPhotoReport",
                        max_length=100,
                    ),
                ),
                ("is_inventory", models.BooleanField(default=False)),
                ("options", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("done", models.BooleanField(default=False)),
                ("error", models.BooleanField(default=False)),
                (
                    "exported_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_photo_reports",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_photo_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
