# Generated by Django 3.2.25 on 2026-03-16 19:40

from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0061_photoreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoreport",
            name="options_file",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                upload_to="",
            ),
        ),
    ]
