# Generated by Django 3.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0062_photoreport_options_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="photoreport",
            name="processing_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
