# Generated by Django 2.1.2 on 2019-04-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservicespecs",
            name="unit",
            field=models.TextField(default="m"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicespecs",
            name="unit",
            field=models.TextField(default="m"),
            preserve_default=False,
        ),
    ]
