# Generated by Django 2.1.2 on 2019-04-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservice",
            name="kind",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="service",
            name="kind",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
