# Generated by Django 2.1.2 on 2019-04-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_auto_20190417_1040"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservice",
            name="code",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="service",
            name="code",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
