# Generated by Django 2.1.2 on 2019-04-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_auto_20190415_1647"),
        ("services", "0003_auto_20190417_1513"),
    ]

    operations = []
