# Generated by Django 2.1.2 on 2019-04-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_merge_20190422_1628"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalservicespecs",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="servicespecs",
            name="unit",
        ),
        migrations.AddField(
            model_name="historicalservice",
            name="unit",
            field=models.TextField(default="m"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="unit",
            field=models.TextField(default="m"),
            preserve_default=False,
        ),
    ]
