# Generated by Django 2.1.2 on 2019-04-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_historicalmeasurementservice_measurementservice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalserviceusage",
            old_name="current_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="serviceusage",
            old_name="current_amount",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="historicalservice",
            name="last_measured_balance",
        ),
        migrations.RemoveField(
            model_name="historicalserviceusage",
            name="adjustment_coefficient",
        ),
        migrations.RemoveField(
            model_name="historicalserviceusage",
            name="last_measured_amount",
        ),
        migrations.RemoveField(
            model_name="historicalserviceusage",
            name="unit_price",
        ),
        migrations.RemoveField(
            model_name="service",
            name="last_measured_balance",
        ),
        migrations.RemoveField(
            model_name="serviceusage",
            name="adjustment_coefficient",
        ),
        migrations.RemoveField(
            model_name="serviceusage",
            name="last_measured_amount",
        ),
        migrations.RemoveField(
            model_name="serviceusage",
            name="unit_price",
        ),
    ]
