# Generated by Django 2.1.2 on 2019-04-23 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_auto_20190423_2006"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmeasurement",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalmeasurement",
            name="previous_measurement",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="services.Measurement",
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="measurement",
            name="previous_measurement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_measurement",
                to="services.Measurement",
            ),
        ),
    ]
