# Generated by Django 2.1.2 on 2019-05-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_auto_20190423_2020"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservice",
            name="group",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="service",
            name="group",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
