# Generated by Django 2.1.2 on 2019-05-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("services", "0010_goal_historicalgoal")]

    operations = [
        migrations.RemoveField(model_name="goal", name="company"),
        migrations.RemoveField(model_name="goal", name="occurrence_type"),
        migrations.RemoveField(model_name="historicalgoal", name="company"),
        migrations.RemoveField(model_name="historicalgoal", name="history_user"),
        migrations.RemoveField(model_name="historicalgoal", name="occurrence_type"),
        migrations.DeleteModel(name="Goal"),
        migrations.DeleteModel(name="HistoricalGoal"),
    ]
