# Generated by Django 2.1.2 on 2019-05-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0017_auto_20190403_1521"),
        ("services", "0012_auto_20190508_1712"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="goal", unique_together={("aggregate", "occurrence_type")}
        )
    ]
