# Generated by Django 2.1.2 on 2019-05-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0013_auto_20190508_1943")]

    operations = [
        migrations.AddField(
            model_name="goalaggregate",
            name="number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="historicalgoalaggregate",
            name="number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
