# Generated by Django 2.1.2 on 2019-05-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0019_auto_20190513_1246"),
        ("services", "0014_auto_20190509_1955"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="servicespecs",
            unique_together={("service", "occurrence_type")},
        )
    ]
