# Generated by Django 2.1.2 on 2019-05-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0015_auto_20190513_1246")]

    operations = [
        migrations.AddField(
            model_name="historicalservice",
            name="initial_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="initial_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
