# Generated by Django 2.1.2 on 2019-05-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0016_auto_20190513_1442")]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_goal",
                to="services.Service",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="third_party",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalgoal",
            name="service",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="services.Service",
            ),
        ),
        migrations.AddField(
            model_name="historicalgoal",
            name="third_party",
            field=models.BooleanField(default=False),
        ),
    ]
