# Generated by Django 2.1.2 on 2019-05-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("services", "0017_auto_20190514_1745")]

    operations = [
        migrations.RenameField(
            model_name="goal", old_name="third_party", new_name="internal"
        ),
        migrations.RenameField(
            model_name="historicalgoal",
            old_name="third_party",
            new_name="internal",
        ),
    ]
