# Generated by Django 2.1.2 on 2019-05-14 21:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("services", "0018_auto_20190514_1808")]

    operations = [
        migrations.AddField(
            model_name="goalaggregate",
            name="group_goals",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalgoalaggregate",
            name="group_goals",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
