# Generated by Django 2.1.2 on 2019-05-15 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0019_auto_20190514_1834")]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="service",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_goal",
                to="services.Service",
            ),
            preserve_default=False,
        )
    ]
