# Generated by Django 2.1.2 on 2019-05-16 21:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("services", "0020_auto_20190515_0949")]

    operations = [
        migrations.AddField(
            model_name="historicalservice",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
