# Generated by Django 2.1.2 on 2019-05-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("services", "0021_auto_20190516_1839")]

    operations = [
        migrations.AlterField(
            model_name="measurementservice",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_measurements",
                to="services.Service",
            ),
        )
    ]
