# Generated by Django 2.2.28 on 2024-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0022_auto_20190527_1646"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalserviceusage",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalserviceusage",
            name="measurement",
        ),
        migrations.RemoveField(
            model_name="historicalserviceusage",
            name="reporting",
        ),
        migrations.RemoveField(
            model_name="historicalserviceusage",
            name="service",
        ),
        migrations.DeleteModel(
            name="HistoricalService",
        ),
        migrations.DeleteModel(
            name="HistoricalServiceUsage",
        ),
    ]
