# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0023_auto_20240808_1040"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalgoal",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical goal",
                "verbose_name_plural": "historical goals",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalgoalaggregate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical goal aggregate",
                "verbose_name_plural": "historical goal aggregates",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmeasurement",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical measurement",
                "verbose_name_plural": "historical measurements",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmeasurementservice",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical measurement service",
                "verbose_name_plural": "historical measurement services",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalservicespecs",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical service specs",
                "verbose_name_plural": "historical service specss",
            },
        ),
        migrations.AlterField(
            model_name="goalaggregate",
            name="group_goals",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalgoal",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalgoalaggregate",
            name="group_goals",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalgoalaggregate",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmeasurement",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmeasurementservice",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalservicespecs",
            name="formula",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalservicespecs",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="servicespecs",
            name="formula",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="serviceusage",
            name="formula",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
