# Generated by Django 2.2.23 on 2022-05-12 04:06

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("monitorings", "0035_historicaloperationalcycle_operationalcycle"),
        ("occurrence_records", "0070_auto_20220418_1509"),
        ("companies", "0053_merge_20220210_0019"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConfig",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("last_run_at", models.DateField(auto_now_add=True)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[("ENGIE_HISTORIADOR", "ENGIE_HISTORIADOR")],
                        max_length=20,
                    ),
                ),
                ("historiador_path", models.TextField()),
                ("instrument_code_field", models.TextField()),
                (
                    "field_map",
                    django.contrib.postgres.fields.jsonb.JSONField(default=list),
                ),
                (
                    "fields_to_copy",
                    django.contrib.postgres.fields.jsonb.JSONField(default=list),
                ),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("HOURLY", "HOURLY"),
                            ("DAILY_NOON", "DAILY_NOON"),
                            ("DAILY_MIDNIGHT", "DAILY_MIDNIGHT"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="companies.Company",
                    ),
                ),
                (
                    "instrument_occurrence_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrations_instrument",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
                (
                    "reading_occurrence_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrations_reading",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
                (
                    "reading_operational_control",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integrations_reading",
                        to="monitorings.OperationalControl",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationRun",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                ("log", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                (
                    "integration_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="integrations.IntegrationConfig",
                    ),
                ),
            ],
            options={
                "ordering": ["started_at"],
            },
        ),
    ]
