# Generated by Django 2.2.23 on 2022-05-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_auto_20220512_0114"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationrun",
            name="error",
            field=models.BooleanField(default=False),
        ),
    ]
