# Generated by Django 2.2.23 on 2022-05-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_integrationrun_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="integrationconfig",
            name="last_run_at",
            field=models.DateTimeField(null=True),
        ),
    ]
