# Generated by Django 2.2.23 on 2022-05-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_auto_20220512_0200"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationconfig",
            name="instrument_code_prefix",
            field=models.TextField(default=""),
        ),
    ]
