# Generated by Django 2.2.23 on 2022-05-30 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integrations", "0005_integrationconfig_instrument_code_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationconfig",
            name="reading_created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="integrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
