# Generated by Django 2.2.23 on 2022-06-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0006_integrationconfig_reading_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconfig",
            name="integration_type",
            field=models.CharField(
                choices=[
                    ("ENGIE_HISTORIADOR", "ENGIE_HISTORIADOR"),
                    ("ENGIE_MAXIMO", "ENGIE_MAXIMO"),
                ],
                max_length=20,
            ),
        ),
    ]
