# Generated by Django 2.2.23 on 2022-06-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0007_auto_20220630_0728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconfig",
            name="historiador_path",
            field=models.TextField(null=True),
        ),
    ]
