# Generated by Django 2.2.23 on 2022-11-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_auto_20220630_0801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconfig",
            name="historiador_path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="integrationconfig",
            name="instrument_code_prefix",
            field=models.TextField(blank=True, default=""),
        ),
    ]
