# Generated by Django 2.2.28 on 2023-04-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_auto_20221122_1436"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationconfig",
            name="instrument_operational_position",
            field=models.TextField(blank=True, null=True),
        ),
    ]
