# Generated by Django 2.2.28 on 2024-05-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0104_sync_new_fields"),
        ("approval_flows", "0014_auto_20220829_1118"),
        ("integrations", "0010_integrationconfig_instrument_operational_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationconfig",
            name="default_approval_step",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="integrations_default_step",
                to="approval_flows.ApprovalStep",
            ),
        ),
        migrations.AddField(
            model_name="integrationconfig",
            name="default_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="integrations_default_status",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
    ]
