# Generated by Django 2.2.28 on 2024-02-27 18:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "integrations",
            "0011_artespintegrationhistory_historicalartespintegrationhistory",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtespAuthentication",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("token", models.TextField()),
            ],
        ),
    ]
