# Generated by Django 2.2.28 on 2024-07-31 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0012_artespauthentication"),
        ("integrations", "0011_auto_20240513_1059"),
    ]

    operations = []
