# Generated by Django 2.2.28 on 2024-07-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0013_merge_20240731_1146"),
    ]

    operations = [
        migrations.AddField(
            model_name="artespintegrationhistory",
            name="error",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalartespintegrationhistory",
            name="error",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="artespintegrationhistory",
            name="sync",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="historicalartespintegrationhistory",
            name="sync",
            field=models.CharField(max_length=200),
        ),
    ]
