# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0014_auto_20240731_1146"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalartespintegrationhistory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical artesp integration history",
                "verbose_name_plural": "historical artesp integration historys",
            },
        ),
        migrations.AlterField(
            model_name="historicalartespintegrationhistory",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="integrationconfig",
            name="field_map",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="integrationconfig",
            name="fields_to_copy",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="integrationrun",
            name="log",
            field=models.JSONField(default=dict),
        ),
    ]
