# Generated by Django 3.2.25 on 2025-08-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0015_auto_20250227_1243"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArtespAuthentication",
        ),
        migrations.RemoveField(
            model_name="historicalartespintegrationhistory",
            name="company",
        ),
        migrations.RemoveField(
            model_name="historicalartespintegrationhistory",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalartespintegrationhistory",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalartespintegrationhistory",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="ArtespIntegrationHistory",
        ),
        migrations.DeleteModel(
            name="HistoricalArtespIntegrationHistory",
        ),
    ]
