# Generated by Django 2.1.2 on 2019-08-09 16:41

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0028_copy_additional_documents"),
        ("service_orders", "0060_procedure_additional_documents"),
        ("companies", "0022_auto_20190514_2005"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0009_auto_20190809_1341"),
        ("monitorings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMonitoringCycle",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("start_date", models.DateTimeField(default=None)),
                ("end_date", models.DateTimeField(default=None)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical monitoring cycle",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMonitoringFrequency",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("start_date", models.DateTimeField(default=None)),
                ("end_date", models.DateTimeField(default=None)),
                ("frequency", models.TextField(blank=True)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical monitoring frequency",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMonitoringPoint",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("code", models.TextField()),
                ("uf_code", models.IntegerField()),
                ("place_on_dam", models.CharField(blank=True, max_length=50)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "coverage_area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("segment", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("depth", models.TextField(blank=True)),
                ("position", models.TextField(blank=True)),
                ("stratification", models.TextField(blank=True)),
                ("zone", models.TextField(blank=True)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="locations.City",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="locations.Location",
                    ),
                ),
                (
                    "river",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="locations.River",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical monitoring point",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MonitoringCycle",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateTimeField(default=None)),
                ("end_date", models.DateTimeField(default=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approvers",
                    models.ManyToManyField(
                        related_name="cycles_approvers", to="companies.Firm"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cycles_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluators",
                    models.ManyToManyField(
                        related_name="cycles_evaluators", to="companies.Firm"
                    ),
                ),
                (
                    "executers",
                    models.ManyToManyField(
                        related_name="cycles_executers", to="companies.Firm"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonitoringFrequency",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateTimeField(default=None)),
                ("end_date", models.DateTimeField(default=None)),
                ("frequency", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MonitoringPoint",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.TextField()),
                ("uf_code", models.IntegerField()),
                ("place_on_dam", models.CharField(blank=True, max_length=50)),
                (
                    "coordinates",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "coverage_area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("segment", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("depth", models.TextField(blank=True)),
                ("position", models.TextField(blank=True)),
                ("stratification", models.TextField(blank=True)),
                ("zone", models.TextField(blank=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.City",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.Company",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.Location",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="monitoringplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="monitoringplan",
            name="responsibles",
            field=models.ManyToManyField(
                related_name="plans_responsibles", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="monitoringpoint",
            name="monitoring_plans",
            field=models.ManyToManyField(
                related_name="points_plans",
                through="monitorings.MonitoringFrequency",
                to="monitorings.MonitoringPlan",
            ),
        ),
        migrations.AddField(
            model_name="monitoringpoint",
            name="parameters",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="points_types",
                to="occurrence_records.OccurrenceType",
            ),
        ),
        migrations.AddField(
            model_name="monitoringpoint",
            name="river",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.River",
            ),
        ),
        migrations.AddField(
            model_name="monitoringfrequency",
            name="monitoring_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frequency_plans",
                to="monitorings.MonitoringPlan",
            ),
        ),
        migrations.AddField(
            model_name="monitoringfrequency",
            name="monitoring_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frequency_points",
                to="monitorings.MonitoringPoint",
            ),
        ),
        migrations.AddField(
            model_name="monitoringcycle",
            name="monitoring_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cycles_plan",
                to="monitorings.MonitoringPlan",
            ),
        ),
        migrations.AddField(
            model_name="monitoringcycle",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cycles_status",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
        migrations.AddField(
            model_name="monitoringcycle",
            name="viewers",
            field=models.ManyToManyField(
                related_name="cycles_viewers", to="companies.Firm"
            ),
        ),
        migrations.AddField(
            model_name="historicalmonitoringfrequency",
            name="monitoring_plan",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="monitorings.MonitoringPlan",
            ),
        ),
        migrations.AddField(
            model_name="historicalmonitoringfrequency",
            name="monitoring_point",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="monitorings.MonitoringPoint",
            ),
        ),
        migrations.AddField(
            model_name="historicalmonitoringcycle",
            name="monitoring_plan",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="monitorings.MonitoringPlan",
            ),
        ),
        migrations.AddField(
            model_name="historicalmonitoringcycle",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
    ]
