# Generated by Django 2.1.2 on 2019-08-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("monitorings", "0002_auto_20190809_1341")]

    operations = [
        migrations.AlterField(
            model_name="monitoringpoint",
            name="parameters",
            field=models.ManyToManyField(
                blank=True,
                related_name="points_types",
                to="occurrence_records.OccurrenceType",
            ),
        )
    ]
