# Generated by Django 2.1.2 on 2019-08-09 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("monitorings", "0003_auto_20190809_1341")]

    operations = [
        migrations.AlterField(
            model_name="monitoringcycle",
            name="approvers",
            field=models.ManyToManyField(
                blank=True, related_name="cycles_approvers", to="companies.Firm"
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcycle",
            name="evaluators",
            field=models.ManyToManyField(
                blank=True,
                related_name="cycles_evaluators",
                to="companies.Firm",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcycle",
            name="executers",
            field=models.ManyToManyField(
                blank=True, related_name="cycles_executers", to="companies.Firm"
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcycle",
            name="viewers",
            field=models.ManyToManyField(
                blank=True, related_name="cycles_viewers", to="companies.Firm"
            ),
        ),
        migrations.AlterField(
            model_name="monitoringplan",
            name="responsibles",
            field=models.ManyToManyField(
                blank=True,
                related_name="plans_responsibles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
