# Generated by Django 2.1.2 on 2019-08-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0004_auto_20190809_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmonitoringcycle",
            name="number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalmonitoringplan",
            name="number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="monitoringcycle",
            name="number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="monitoringplan",
            name="number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
