# Generated by Django 2.1.2 on 2019-09-18 03:19

import uuid

import django.db.models.deletion
import django.utils.datetime_safe
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0064_auto_20190813_1613"),
        ("companies", "0022_auto_20190514_2005"),
        ("occurrence_records", "0033_historicaloccurrencerecord_history_relation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monitorings", "0005_auto_20190826_2037"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMonitoringCampaign",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("start_date", models.DateTimeField(default=None)),
                ("end_date", models.DateTimeField(default=None)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Firm",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monitoring_plan",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="monitorings.MonitoringPlan",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="service_orders.ServiceOrderActionStatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical monitoring campaign",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MonitoringCampaign",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateTimeField(default=None)),
                ("end_date", models.DateTimeField(default=None)),
                (
                    "firm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.Firm",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="historicalmonitoringfrequency",
            name="monitoring_point",
        ),
        migrations.RemoveField(
            model_name="historicalmonitoringpoint",
            name="company",
        ),
        migrations.RemoveField(
            model_name="monitoringfrequency",
            name="monitoring_point",
        ),
        migrations.RemoveField(
            model_name="monitoringpoint",
            name="company",
        ),
        migrations.RemoveField(
            model_name="monitoringpoint",
            name="monitoring_plans",
        ),
        migrations.RemoveField(
            model_name="monitoringpoint",
            name="parameters",
        ),
        migrations.AddField(
            model_name="historicalmonitoringfrequency",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.datetime_safe.datetime.now,
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmonitoringfrequency",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalmonitoringfrequency",
            name="parameter_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="occurrence_records.OccurrenceType",
            ),
        ),
        migrations.AddField(
            model_name="historicalmonitoringfrequency",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.datetime_safe.datetime.now,
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmonitoringpoint",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.datetime_safe.datetime.now,
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmonitoringpoint",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalmonitoringpoint",
            name="monitoring_plan",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="monitorings.MonitoringPlan",
            ),
        ),
        migrations.AddField(
            model_name="historicalmonitoringpoint",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.datetime_safe.datetime.now,
                editable=False,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monitoringfrequency",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.datetime_safe.datetime.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monitoringfrequency",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="monitoringfrequency",
            name="monitoring_points",
            field=models.ManyToManyField(
                blank=True,
                related_name="scheduled_frequencies",
                to="monitorings.MonitoringPoint",
            ),
        ),
        migrations.AddField(
            model_name="monitoringfrequency",
            name="parameter_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="occurrence_records.OccurrenceType",
            ),
        ),
        migrations.AddField(
            model_name="monitoringfrequency",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="monitoringpoint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.datetime_safe.datetime.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monitoringpoint",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="monitoringpoint",
            name="monitoring_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitoring_points",
                to="monitorings.MonitoringPlan",
            ),
        ),
        migrations.AddField(
            model_name="monitoringpoint",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="monitoringcampaign",
            name="frequencies",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaigns",
                to="monitorings.MonitoringFrequency",
            ),
        ),
        migrations.AddField(
            model_name="monitoringcampaign",
            name="monitoring_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="monitorings.MonitoringPlan",
            ),
        ),
        migrations.AddField(
            model_name="monitoringcampaign",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
    ]
