# Generated by Django 2.1.2 on 2019-09-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0007_auto_20190920_1951"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalmonitoringrecord",
            old_name="occurrence_type",
            new_name="parameter_group",
        ),
        migrations.RenameField(
            model_name="monitoringrecord",
            old_name="occurrence_type",
            new_name="parameter_group",
        ),
    ]
