# Generated by Django 2.1.2 on 2019-09-28 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0008_auto_20190924_1657"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmonitoringrecord",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalmonitoringrecord",
            name="history_relation",
        ),
        migrations.RemoveField(
            model_name="historicalmonitoringrecord",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalmonitoringrecord",
            name="monitoring_campaign",
        ),
        migrations.RemoveField(
            model_name="historicalmonitoringrecord",
            name="monitoring_frequency",
        ),
        migrations.RemoveField(
            model_name="historicalmonitoringrecord",
            name="monitoring_point",
        ),
        migrations.RemoveField(
            model_name="historicalmonitoringrecord",
            name="parameter_group",
        ),
        migrations.RemoveField(
            model_name="monitoringrecord",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="monitoringrecord",
            name="monitoring_campaign",
        ),
        migrations.RemoveField(
            model_name="monitoringrecord",
            name="monitoring_frequency",
        ),
        migrations.RemoveField(
            model_name="monitoringrecord",
            name="monitoring_point",
        ),
        migrations.RemoveField(
            model_name="monitoringrecord",
            name="parameter_group",
        ),
        migrations.DeleteModel(
            name="HistoricalMonitoringRecord",
        ),
        migrations.DeleteModel(
            name="MonitoringRecord",
        ),
    ]
