# Generated by Django 2.1.2 on 2019-10-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0010_auto_20190927_2114"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmonitoringpoint",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="monitoringpoint",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
