# Generated by Django 2.1.2 on 2019-10-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_auto_20190827_1419"),
        ("monitorings", "0011_auto_20191023_2002"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmonitoringplan",
            name="monitoring_object",
        ),
        migrations.RemoveField(
            model_name="monitoringplan",
            name="monitoring_object",
        ),
        migrations.AddField(
            model_name="monitoringcycle",
            name="contracts",
            field=models.ManyToManyField(
                blank=True, related_name="monitoring_cycles", to="resources.Contract"
            ),
        ),
    ]
