# Generated by Django 2.1.2 on 2019-11-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0066_auto_20191129_0920"),
        ("monitorings", "0013_auto_20191129_0728"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="procedure_resource",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.ProcedureResource",
            ),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="procedure_resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resource_op_records",
                to="service_orders.ProcedureResource",
            ),
        ),
    ]
