# Generated by Django 2.1.2 on 2019-12-05 12:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("monitorings", "0014_auto_20191129_0921")]

    operations = [
        migrations.AddField(
            model_name="historicaloperationalcontrol",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="operationalcontrol",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
