# Generated by Django 2.1.2 on 2020-01-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0068_auto_20191210_1600"),
        ("monitorings", "0015_auto_20191205_0958"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaloperationalcontrolrecord",
            name="procedure_resource",
        ),
        migrations.RemoveField(
            model_name="operationalcontrolrecord",
            name="procedure_resource",
        ),
        migrations.AddField(
            model_name="monitoringcampaign",
            name="procedures",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedures_monitoring_campaign",
                to="service_orders.Procedure",
            ),
        ),
        migrations.AddField(
            model_name="monitoringcycle",
            name="service_orders",
            field=models.ManyToManyField(
                blank=True,
                related_name="services_cycle",
                to="service_orders.ServiceOrder",
            ),
        ),
        migrations.AddField(
            model_name="monitoringrecord",
            name="procedures",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedures_monitoring_record",
                to="service_orders.Procedure",
            ),
        ),
        migrations.AddField(
            model_name="operationalcontrol",
            name="service_orders",
            field=models.ManyToManyField(
                blank=True,
                related_name="services_control",
                to="service_orders.ServiceOrder",
            ),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="procedures",
            field=models.ManyToManyField(
                blank=True,
                related_name="procedures_control_record",
                to="service_orders.Procedure",
            ),
        ),
    ]
