# Generated by Django 2.1.2 on 2020-01-10 10:59

import uuid

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_auto_20190827_1419"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0028_auto_20191217_0940"),
        ("monitorings", "0016_auto_20200114_1543"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMaterialItem",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.TextField()),
                ("amount", models.FloatField(default=0)),
                ("unit_price", models.FloatField(default=0)),
                ("used_price", models.FloatField(default=0)),
                ("remaining_amount", models.FloatField(default=0)),
                (
                    "creation_date",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "effective_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("is_extra", models.BooleanField(default=False)),
                ("resource_kind", models.CharField(blank=True, max_length=60)),
                ("provider", models.CharField(blank=True, max_length=60)),
                (
                    "additional_control",
                    models.CharField(blank=True, max_length=60),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="resources.Contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operational_control",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="monitorings.OperationalControl",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical material item",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMaterialUsage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("amount", models.FloatField(default=0)),
                ("unit_price", models.FloatField(blank=True, null=True)),
                ("total_price", models.FloatField(blank=True, null=True)),
                (
                    "creation_date",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                            ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                            ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                        ],
                        default="WAITING_APPROVAL",
                        max_length=100,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Firm",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical material usage",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MaterialItem",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("amount", models.FloatField(default=0)),
                ("unit_price", models.FloatField(default=0)),
                ("used_price", models.FloatField(default=0)),
                ("remaining_amount", models.FloatField(default=0)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "effective_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("is_extra", models.BooleanField(default=False)),
                ("resource_kind", models.CharField(blank=True, max_length=60)),
                ("provider", models.CharField(blank=True, max_length=60)),
                (
                    "additional_control",
                    models.CharField(blank=True, max_length=60),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_material_items",
                        to="companies.Company",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_material_items",
                        to="resources.Contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_material_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operational_control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_material_items",
                        to="monitorings.OperationalControl",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialUsage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                ("unit_price", models.FloatField(blank=True, null=True)),
                ("total_price", models.FloatField(blank=True, null=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                            ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                            ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                        ],
                        default="WAITING_APPROVAL",
                        max_length=100,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approver_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creator_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firm_usages",
                        to="companies.Firm",
                    ),
                ),
                (
                    "material_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_item_usages",
                        to="monitorings.MaterialItem",
                    ),
                ),
                (
                    "operational_control_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_record_usages",
                        to="monitorings.OperationalControlRecord",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historicalmaterialusage",
            name="material_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="monitorings.MaterialItem",
            ),
        ),
        migrations.AddField(
            model_name="historicalmaterialusage",
            name="operational_control_record",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="monitorings.OperationalControlRecord",
            ),
        ),
    ]
