# Generated by Django 2.1.2 on 2020-01-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0017_auto_20200110_0759"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringcampaign",
            name="procedures",
            field=models.ManyToManyField(
                blank=True,
                related_name="monitoring_campaigns",
                to="service_orders.Procedure",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringcycle",
            name="service_orders",
            field=models.ManyToManyField(
                blank=True,
                related_name="monitoring_cycles",
                to="service_orders.ServiceOrder",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringrecord",
            name="procedures",
            field=models.ManyToManyField(
                blank=True,
                related_name="monitoring_records",
                to="service_orders.Procedure",
            ),
        ),
        migrations.AlterField(
            model_name="operationalcontrol",
            name="service_orders",
            field=models.ManyToManyField(
                blank=True,
                related_name="operational_controls",
                to="service_orders.ServiceOrder",
            ),
        ),
        migrations.AlterField(
            model_name="operationalcontrolrecord",
            name="procedures",
            field=models.ManyToManyField(
                blank=True,
                related_name="operational_control_records",
                to="service_orders.Procedure",
            ),
        ),
    ]
