# Generated by Django 2.1.2 on 2020-01-22 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0018_auto_20200116_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalcontrol",
            name="contract",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_op_controls",
                to="resources.Contract",
            ),
        ),
    ]
