# Generated by Django 2.1.2 on 2020-01-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0019_auto_20200122_1949"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmaterialitem",
            name="contract",
        ),
        migrations.RemoveField(
            model_name="materialitem",
            name="contract",
        ),
    ]
