# Generated by Django 2.1.2 on 2019-07-18 21:36

from django.db import migrations
from fnc.mappings import get
from fnc.sequences import find
from tqdm import tqdm


def forwards_func(apps, schema_editor):
    MaterialItem = apps.get_model("monitorings", "MaterialItem")
    Entity = apps.get_model("companies", "Entity")

    db_alias = schema_editor.connection.alias

    existing_material_items = (
        MaterialItem.objects.using(db_alias).all().prefetch_related("company")
    )

    for material_item in tqdm(existing_material_items):
        if not material_item.company or material_item.provider == "":
            continue

        provider_options = get(
            "materialItem.fields.provider.selectOptions.options",
            material_item.company.custom_options,
        )
        provider_object = find(
            lambda x: x["value"] == material_item.provider, provider_options
        )
        provider_name = provider_object["name"]

        entity = Entity.objects.filter(
            company=material_item.company, name__icontains=provider_name
        ).first()
        if not entity:
            entity = Entity.objects.create(
                company=material_item.company, name=provider_name
            )

        material_item.entity = entity
        material_item.save()


class Migration(migrations.Migration):

    dependencies = [("monitorings", "0021_auto_20201123_2311")]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)
    ]
