# Generated by Django 2.1.2 on 2020-11-24 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("monitorings", "0022_fill_material_item_entity")]

    operations = [
        migrations.RemoveField(model_name="historicalmaterialitem", name="provider"),
        migrations.RemoveField(model_name="materialitem", name="provider"),
    ]
