# Generated by Django 2.1.2 on 2020-12-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0023_auto_20201123_2322"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="editable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="editable",
            field=models.BooleanField(default=True),
        ),
    ]
