# Generated by Django 2.1.2 on 2021-01-04 17:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0024_auto_20201207_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="form_metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="form_metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
