# Generated by Django 2.1.2 on 2021-05-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0009_auto_20190809_1341"),
        ("monitorings", "0025_auto_20210104_1458"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="city",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.City",
            ),
        ),
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="distance_from_dam",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.Location",
            ),
        ),
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="other_reference",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="place_on_dam",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="river",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="locations.River",
            ),
        ),
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="uf_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.City",
            ),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="distance_from_dam",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.Location",
            ),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="other_reference",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="place_on_dam",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="river",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.River",
            ),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="uf_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
