# Generated by Django 2.1.2 on 2021-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0026_operationalcontrolrecord_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="geometry_hash",
            field=models.TextField(blank=True, null=True),
        ),
    ]
