# Generated by Django 2.2.23 on 2021-06-11 11:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0027_historicaloperationalcontrolrecord_geometry_hash")
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="map_default_filters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaloperationalcontrolrecord",
            name="show_map",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="map_default_filters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="operationalcontrolrecord",
            name="show_map",
            field=models.BooleanField(default=False),
        ),
    ]
