# Generated by Django 2.2.23 on 2021-06-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("monitorings", "0028_auto_20210611_0847")]

    operations = [
        migrations.RemoveField(
            model_name="historicaloperationalcontrolrecord",
            name="map_default_filters",
        ),
        migrations.RemoveField(
            model_name="historicaloperationalcontrolrecord", name="show_map"
        ),
        migrations.RemoveField(
            model_name="operationalcontrolrecord", name="map_default_filters"
        ),
        migrations.RemoveField(model_name="operationalcontrolrecord", name="show_map"),
    ]
