# Generated by Django 2.2.23 on 2021-06-23 16:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("monitorings", "0029_auto_20210623_1325")]

    operations = [
        migrations.AddField(
            model_name="historicaloperationalcontrol",
            name="map_default_filters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaloperationalcontrol",
            name="show_map",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operationalcontrol",
            name="map_default_filters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="operationalcontrol",
            name="show_map",
            field=models.BooleanField(default=False),
        ),
    ]
