# Generated by Django 2.2.23 on 2021-07-01 12:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("monitorings", "0030_auto_20210623_1328")]

    operations = [
        migrations.AddField(
            model_name="historicalmonitoringrecord",
            name="form_metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="monitoringrecord",
            name="form_metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
