# Generated by Django 2.2.23 on 2021-09-14 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0064_auto_20210914_1439"),
        ("monitorings", "0032_auto_20210707_0733"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmaterialusage",
            name="occurrence_record",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="materialusage",
            name="occurrence_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="record_usages",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
    ]
