# Generated by Django 2.2.23 on 2021-10-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("monitorings", "0033_auto_20210914_1739")]

    operations = [
        migrations.RemoveField(model_name="operationalcontrol", name="service_orders")
    ]
