# Generated by Django 2.2.23 on 2021-10-07 12:50

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0042_populate_firm_created_by"),
        ("monitorings", "0034_remove_operationalcontrol_service_orders"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalCycle",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateTimeField(default=None)),
                ("end_date", models.DateTimeField(default=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operational_cycle_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="operational_cycles_creators",
                        to="companies.Firm",
                    ),
                ),
                (
                    "operational_control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operational_control_cycles",
                        to="monitorings.OperationalControl",
                    ),
                ),
                (
                    "viewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="operational_cycle_viewers",
                        to="companies.Firm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalOperationalCycle",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("number", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateTimeField(default=None)),
                ("end_date", models.DateTimeField(default=None)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operational_control",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="monitorings.OperationalControl",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical operational cycle",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
