# Generated by Django 2.2.23 on 2022-05-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0035_historicaloperationalcycle_operationalcycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloperationalcontrol",
            name="show_materials",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="operationalcontrol",
            name="show_materials",
            field=models.BooleanField(default=False),
        ),
    ]
