# Generated by Django 2.2.23 on 2022-02-01 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monitorings", "0035_historicaloperationalcycle_operationalcycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringcycle",
            name="responsibles",
            field=models.ManyToManyField(
                blank=True,
                related_name="responsible_cycles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
