# Generated by Django 2.2.28 on 2022-10-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0074_auto_20220920_1141"),
        ("monitorings", "0035_historicaloperationalcycle_operationalcycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalcontrol",
            name="config_occurrence_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="occurrence_type_op_controls",
                to="occurrence_records.OccurrenceType",
            ),
        ),
    ]
