# Generated by Django 2.2.23 on 2022-02-02 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0094_auto_20220202_1631"),
        ("monitorings", "0036_monitoringcycle_responsibles"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmonitoringplan",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
        migrations.AddField(
            model_name="monitoringplan",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_monitorings",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
    ]
