# Generated by Django 2.2.23 on 2022-03-09 14:22

from django.db import migrations
from django_bulk_update.helper import bulk_update

from apps.service_orders.const import status_types


def add_final_status_monitorings(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    MonitoringPlan = apps.get_model("monitorings", "MonitoringPlan")
    monitorings = MonitoringPlan.objects.using(db_alias).filter(status__isnull=True)

    ServiceOrderActionStatus = apps.get_model(
        "service_orders", "ServiceOrderActionStatus"
    )
    final_monitoring_status = ServiceOrderActionStatus.objects.using(db_alias).filter(
        kind=status_types.MONITORING_STATUS, is_final=True
    )

    # List of updated monitorings
    updated_monitorings = []

    for status in final_monitoring_status:
        monitorings_by_company = monitorings.filter(company__in=status.companies.all())
        for monitoring in monitorings_by_company:
            monitoring.status = status
            updated_monitorings.append(monitoring)

    bulk_update(updated_monitorings, batch_size=2000, update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0038_historicalmonitoringcollect_monitoringcollect"),
    ]

    operations = [
        migrations.RunPython(
            add_final_status_monitorings, reverse_code=migrations.RunPython.noop
        )
    ]
