# Generated by Django 2.2.23 on 2022-03-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0039_auto_20220309_1122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmonitoringpoint",
            name="uf_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringpoint",
            name="uf_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
