# Generated by Django 2.2.23 on 2022-03-16 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0040_auto_20220310_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringcollect",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_collects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
