# Generated by Django 2.2.23 on 2022-03-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0041_auto_20220315_2204"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmonitoringcycle",
            name="email_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="monitoringcycle",
            name="email_created",
            field=models.BooleanField(default=False),
        ),
    ]
