# Generated by Django 2.2.23 on 2022-03-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0042_auto_20220321_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmonitoringfrequency",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="monitoringfrequency",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
