# Generated by Django 2.2.23 on 2022-03-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0043_auto_20220321_1637"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmonitoringplan",
            name="is_not_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="monitoringplan",
            name="is_not_notified",
            field=models.BooleanField(default=False),
        ),
    ]
