# Generated by Django 2.2.23 on 2022-03-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0044_auto_20220322_1551"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitoringcycle",
            name="service_orders",
        ),
    ]
