# Generated by Django 2.2.23 on 2022-03-25 10:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0045_remove_monitoringcycle_service_orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalmonitoringcollect",
            old_name="form_data",
            new_name="dict_form_data",
        ),
        migrations.RenameField(
            model_name="monitoringcollect",
            old_name="form_data",
            new_name="dict_form_data",
        ),
        migrations.RemoveField(
            model_name="historicalmonitoringcollect",
            name="form_metadata",
        ),
        migrations.RemoveField(
            model_name="monitoringcollect",
            name="form_metadata",
        ),
        migrations.AddField(
            model_name="historicalmonitoringcollect",
            name="array_form_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
        migrations.AddField(
            model_name="monitoringcollect",
            name="array_form_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
    ]
