# Generated by Django 2.2.23 on 2022-11-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0036_operationalcontrol_config_occurrence_types"),
        ("monitorings", "0046_auto_20220325_0748"),
    ]

    operations = []
