# Generated by Django 2.2.23 on 2022-11-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0047_merge_20221111_1348"),
        ("monitorings", "0036_auto_20220530_0956"),
    ]

    operations = []
