# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0048_merge_20221121_0956"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalmaterialitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical material item",
                "verbose_name_plural": "historical material items",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmaterialusage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical material usage",
                "verbose_name_plural": "historical material usages",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmonitoringcampaign",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical monitoring campaign",
                "verbose_name_plural": "historical monitoring campaigns",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmonitoringcollect",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical monitoring collect",
                "verbose_name_plural": "historical monitoring collects",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmonitoringcycle",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical monitoring cycle",
                "verbose_name_plural": "historical monitoring cycles",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmonitoringfrequency",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical monitoring frequency",
                "verbose_name_plural": "historical monitoring frequencys",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmonitoringplan",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical monitoring plan",
                "verbose_name_plural": "historical monitoring plans",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmonitoringpoint",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical monitoring point",
                "verbose_name_plural": "historical monitoring points",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalmonitoringrecord",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical monitoring record",
                "verbose_name_plural": "historical monitoring records",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaloperationalcontrol",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical operational control",
                "verbose_name_plural": "historical operational controls",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaloperationalcontrolrecord",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical operational control record",
                "verbose_name_plural": "historical operational control records",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaloperationalcycle",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical operational cycle",
                "verbose_name_plural": "historical operational cycles",
            },
        ),
        migrations.AlterField(
            model_name="historicalmaterialitem",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmaterialusage",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmonitoringcampaign",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmonitoringcollect",
            name="array_form_data",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmonitoringcollect",
            name="dict_form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmonitoringcollect",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmonitoringcycle",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmonitoringfrequency",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmonitoringplan",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmonitoringpoint",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalmonitoringrecord",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmonitoringrecord",
            name="form_metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmonitoringrecord",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaloperationalcontrol",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaloperationalcontrol",
            name="map_default_filters",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloperationalcontrol",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloperationalcontrolrecord",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloperationalcontrolrecord",
            name="form_metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloperationalcontrolrecord",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaloperationalcontrolrecord",
            name="properties",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="historicaloperationalcycle",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="monitoringcollect",
            name="array_form_data",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringcollect",
            name="dict_form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringrecord",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringrecord",
            name="form_metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="operationalcontrol",
            name="map_default_filters",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="operationalcontrol",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="operationalcontrolrecord",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="operationalcontrolrecord",
            name="form_metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="operationalcontrolrecord",
            name="properties",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
