# Generated by Django 3.2.25 on 2025-09-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0049_auto_20250227_1243"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operationalcontrolrecord",
            name="city",
        ),
        migrations.RemoveField(
            model_name="operationalcontrolrecord",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="operationalcontrolrecord",
            name="firm",
        ),
        migrations.RemoveField(
            model_name="operationalcontrolrecord",
            name="location",
        ),
        migrations.RemoveField(
            model_name="operationalcontrolrecord",
            name="occurrence_type",
        ),
        migrations.RemoveField(
            model_name="operationalcontrolrecord",
            name="operational_control",
        ),
        migrations.RemoveField(
            model_name="operationalcontrolrecord",
            name="procedures",
        ),
        migrations.RemoveField(
            model_name="operationalcontrolrecord",
            name="responsible",
        ),
        migrations.RemoveField(
            model_name="operationalcontrolrecord",
            name="river",
        ),
        migrations.RemoveField(
            model_name="operationalcontrolrecord",
            name="status",
        ),
        migrations.RemoveField(
            model_name="historicalmaterialusage",
            name="operational_control_record",
        ),
        migrations.RemoveField(
            model_name="materialusage",
            name="operational_control_record",
        ),
        migrations.DeleteModel(
            name="HistoricalOperationalControlRecord",
        ),
        migrations.DeleteModel(
            name="OperationalControlRecord",
        ),
    ]
