# Generated by Django 2.1.2 on 2018-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="unit_price",
            field=models.FloatField(default=0),
        ),
    ]
