# Generated by Django 2.1.2 on 2018-10-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_resource_unit_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="unit_price",
        ),
    ]
