# Generated by Django 2.1.2 on 2018-12-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_remove_resource_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="isExtra",
            field=models.BooleanField(default=False),
        ),
    ]
