# Generated by Django 2.1.2 on 2019-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_resource_isextra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="resource",
            name="unit",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
