# Generated by Django 2.1.2 on 2019-01-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_resource_isextra"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resource",
            old_name="isExtra",
            new_name="is_extra",
        ),
    ]
