# Generated by Django 2.1.2 on 2019-01-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_auto_20190108_1258"),
        ("resources", "0005_auto_20190107_0335"),
    ]

    operations = []
