# Generated by Django 2.1.2 on 2020-01-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_auto_20190827_1419"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="contract_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="contract_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
