# Generated by Django 2.1.2 on 2020-01-20 16:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0010_auto_20200116_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="spend_schedule",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="spend_schedule",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
