# Generated by Django 2.1.2 on 2020-11-04 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0012_auto_20200207_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="responsibles_hired",
            field=models.ManyToManyField(
                related_name="hired_contracts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="responsibles_hirer",
            field=models.ManyToManyField(
                related_name="hirer_contracts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
