# Generated by Django 2.1.2 on 2019-12-17 12:40

from django.db import migrations


def unique_together(apps, schema_editor):
    Contract = apps.get_model("resources", "Contract")
    db_alias = schema_editor.connection.alias

    contracts = Contract.objects.using(db_alias).all()
    for contract in contracts:
        if contract.responsible:
            contract.responsibles_hirer.set([contract.responsible])

        if contract.firm_responsible:
            contract.responsibles_hired.set([contract.firm_responsible])


class Migration(migrations.Migration):

    dependencies = [("resources", "0013_auto_20201104_0951")]

    operations = [migrations.RunPython(unique_together, migrations.RunPython.noop)]
