# Generated by Django 2.1.2 on 2020-11-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("resources", "0014_copy_fk_responsibles_to_m2m")]

    operations = [
        migrations.RemoveField(model_name="contract", name="firm_responsible"),
        migrations.RemoveField(model_name="contract", name="responsible"),
        migrations.RemoveField(
            model_name="historicalcontract", name="firm_responsible"
        ),
        migrations.RemoveField(model_name="historicalcontract", name="responsible"),
    ]
