# Generated by Django 2.2.23 on 2021-12-07 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0015_auto_20201104_0956"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="firm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firm_contracts",
                to="companies.Firm",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_contracts",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
    ]
