# Generated by Django 2.2.23 on 2022-01-19 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0051_merge_20211207_0836"),
        ("resources", "0015_auto_20201104_0956"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="subcompany",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcompany_contracts",
                to="companies.SubCompany",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="subcompany",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.SubCompany",
            ),
        ),
    ]
