# Generated by Django 2.2.23 on 2022-01-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0017_auto_20220119_0953")]

    operations = [
        migrations.RemoveField(
            model_name="contractitemunitprice", name="contract_service"
        ),
        migrations.RemoveField(
            model_name="historicalcontractitemunitprice",
            name="contract_service",
        ),
        migrations.AddField(
            model_name="contractservice",
            name="contract_item_unit_prices",
            field=models.ManyToManyField(
                related_name="contract_item_unit_price_services",
                to="resources.ContractItemUnitPrice",
            ),
        ),
    ]
