# Generated by Django 2.2.23 on 2022-01-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0018_auto_20220121_0937")]

    operations = [
        migrations.AlterField(
            model_name="contractitemunitprice",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resource_contract_unit_price_items",
                to="service_orders.ServiceOrderResource",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontractitemunitprice",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.ServiceOrderResource",
            ),
        ),
    ]
