# Generated by Django 2.2.23 on 2022-01-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0019_auto_20220121_1425")]

    operations = [
        migrations.AlterField(
            model_name="contractservice",
            name="contract_item_unit_prices",
            field=models.ManyToManyField(
                blank=True,
                related_name="contract_item_unit_price_services",
                to="resources.ContractItemUnitPrice",
            ),
        )
    ]
