# Generated by Django 2.2.23 on 2022-02-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0020_auto_20220124_2357")]

    operations = [
        migrations.AddField(
            model_name="contractservice",
            name="provisioned_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractservice",
            name="provisioned_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
