# Generated by Django 2.2.23 on 2022-03-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("resources", "0024_contractservice_contract_item_administration")]

    operations = [
        migrations.RemoveField(model_name="contractservice", name="provisioned_price"),
        migrations.RemoveField(
            model_name="historicalcontractservice", name="provisioned_price"
        ),
    ]
