# Generated by Django 2.2.23 on 2022-03-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("resources", "0026_migrate_old_contract_items")]

    operations = [
        migrations.RemoveField(
            model_name="contractitemadministration", name="board_item"
        ),
        migrations.RemoveField(
            model_name="historicalcontractitemadministration", name="board_item"
        ),
    ]
