# Generated by Django 2.2.23 on 2022-03-08 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("resources", "0027_auto_20220308_1520"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitemadministration",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportworker"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportvehicle"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportequipment"),
                    ),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontractitemadministration",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to=models.Q(
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportworker"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportvehicle"),
                    ),
                    models.Q(
                        ("app_label", "daily_reports"),
                        ("model", "dailyreportequipment"),
                    ),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.ContentType",
            ),
        ),
    ]
