# Generated by Django 2.2.23 on 2022-03-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0028_auto_20220308_1939"),
        ("resources", "0016_auto_20211207_1635"),
    ]

    operations = []
