# Generated by Django 2.2.23 on 2022-04-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0029_merge_20220324_0855"),
        ("resources", "0029_merge_20220315_1626"),
    ]

    operations = []
