# Generated by Django 2.2.23 on 2022-04-19 13:52

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0097_merge_20220414_0513"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0053_merge_20220210_0019"),
        ("resources", "0030_merge_20220414_0513"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="performance_months",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="contractservice",
            name="price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="contractservice",
            name="weight",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="performance_months",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractservice",
            name="price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractservice",
            name="weight",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="HistoricalContractItemPerformance",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("weight", models.FloatField(blank=True, default=0, null=True)),
                ("sort_string", models.TextField()),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Entity",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="service_orders.ServiceOrderResource",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contract item performance",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContractItemPerformance",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("weight", models.FloatField(blank=True, default=0, null=True)),
                ("sort_string", models.TextField()),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entity_contract_performance_items",
                        to="companies.Entity",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_contract_performance_items",
                        to="service_orders.ServiceOrderResource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contractservice",
            name="contract_item_performance",
            field=models.ManyToManyField(
                blank=True,
                related_name="contract_item_performance_services",
                to="resources.ContractItemPerformance",
            ),
        ),
    ]
