# Generated by Django 2.2.23 on 2022-04-19 13:54

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0097_merge_20220414_0513"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0030_merge_20220414_0513"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementBulletinExport",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exported_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                        upload_to="",
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                ("error", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_measurement_bulletin_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "measurement_bulletin",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_bulletin_exports",
                        to="service_orders.MeasurementBulletin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalMeasurementBulletinExport",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "exported_file",
                    models.TextField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                ("error", models.BooleanField(default=False)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "measurement_bulletin",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="service_orders.MeasurementBulletin",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical measurement bulletin export",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
