# Generated by Django 2.2.23 on 2022-05-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "resources",
            "0031_historicalmeasurementbulletinexport_measurementbulletinexport",
        ),
        ("resources", "0031_auto_20220419_1052"),
    ]

    operations = []
