# Generated by Django 2.2.23 on 2022-05-05 12:48

import django.contrib.postgres.fields.jsonb
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0031_auto_20220504_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldsurvey",
            name="responsibles_hired",
            field=models.ManyToManyField(
                related_name="survey_hireds", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="roads",
            field=models.ManyToManyField(
                related_name="survey_road_contracts",
                through="resources.FieldSurveyRoad",
                to="roads.Road",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="survey_default",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="contract",
            name="survey_responsibles_hired",
            field=models.ManyToManyField(
                related_name="survey_responsibles_hired_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="survey_responsibles_hirer",
            field=models.ManyToManyField(
                related_name="survey_responsibles_hirer_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fieldsurvey",
            name="grades",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="fieldsurvey",
            name="responsibles_hirer",
            field=models.ManyToManyField(
                related_name="survey_hirers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="survey_default",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="grades",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
