# Generated by Django 2.2.23 on 2022-05-05 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0032_auto_20220505_0948"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="responsibles_hired",
            field=models.ManyToManyField(
                null=True, related_name="hired_contracts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="responsibles_hirer",
            field=models.ManyToManyField(
                null=True, related_name="hirer_contracts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="fieldsurvey",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="fieldsurvey",
            name="executed_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="created_at",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="executed_at",
            field=models.DateField(blank=True, editable=False),
        ),
    ]
