# Generated by Django 2.2.23 on 2022-05-05 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0033_auto_20220505_1037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="responsibles_hired",
            field=models.ManyToManyField(
                related_name="hired_contracts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="responsibles_hirer",
            field=models.ManyToManyField(
                related_name="hirer_contracts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
