# Generated by Django 2.2.23 on 2022-05-09 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0097_merge_20220414_0513"),
        ("resources", "0034_auto_20220505_1045"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="has_survey_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="higher_grade",
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="lower_grade",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="fieldsurvey",
            name="name",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fieldsurvey",
            name="number",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fieldsurvey",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_status_surveys",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="has_survey_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="higher_grade",
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="lower_grade",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalfieldsurvey",
            name="name",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalfieldsurvey",
            name="number",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalfieldsurvey",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
        migrations.AlterField(
            model_name="fieldsurveyroad",
            name="contract",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys_roads",
                to="resources.Contract",
            ),
        ),
        migrations.AlterField(
            model_name="fieldsurveyroad",
            name="road",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_roads",
                to="roads.Road",
            ),
        ),
    ]
