# Generated by Django 2.2.23 on 2022-05-10 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0035_auto_20220509_1140"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fieldsurvey",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="fieldsurveyroad",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalfieldsurvey",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="historicalfieldsurveyroad",
            name="entity",
        ),
    ]
