# Generated by Django 2.2.23 on 2022-05-10 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0036_auto_20220509_2129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldsurvey",
            name="responsibles_hired",
            field=models.ManyToManyField(
                null=True, related_name="survey_hireds", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="fieldsurvey",
            name="responsibles_hirer",
            field=models.ManyToManyField(
                null=True, related_name="survey_hirers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
