# Generated by Django 2.2.23 on 2022-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0037_auto_20220509_2135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldsurvey",
            name="number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
