# Generated by Django 2.2.23 on 2022-05-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0038_auto_20220510_1158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldsurvey",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fieldsurvey",
            name="number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
