# Generated by Django 2.2.23 on 2022-05-23 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0032_merge_20220511_1041"),
        ("resources", "0039_auto_20220510_1419"),
    ]

    operations = []
