# Generated by Django 2.2.23 on 2022-05-23 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("service_orders", "0097_merge_20220414_0513"),
        ("resources", "0040_merge_20220523_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldsurvey",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fieldsurvey",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                    ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                    ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                ],
                default="WAITING_APPROVAL",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="fieldsurvey",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_survey_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fieldsurvey",
            name="measurement_bulletin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletin_surveys",
                to="service_orders.MeasurementBulletin",
            ),
        ),
        migrations.AddField(
            model_name="historicalfieldsurvey",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfieldsurvey",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("WAITING_APPROVAL", "WAITING_APPROVAL"),
                    ("APPROVED_APPROVAL", "APPROVED_APPROVAL"),
                    ("DENIED_APPROVAL", "DENIED_APPROVAL"),
                ],
                default="WAITING_APPROVAL",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalfieldsurvey",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalfieldsurvey",
            name="measurement_bulletin",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.MeasurementBulletin",
            ),
        ),
    ]
