# Generated by Django 2.2.23 on 2022-05-24 13:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0041_auto_20220523_1339"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldSurveySignature",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="fieldsurvey", name="responsibles_hired"),
        migrations.RemoveField(model_name="fieldsurvey", name="responsibles_hirer"),
        migrations.AddField(
            model_name="fieldsurvey",
            name="responsibles_hired",
            field=models.ManyToManyField(
                null=True,
                related_name="hired_surveys",
                through="resources.FieldSurveySignature",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fieldsurvey",
            name="responsibles_hirer",
            field=models.ManyToManyField(
                null=True,
                related_name="hirer_surveys",
                through="resources.FieldSurveySignature",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fieldsurvey",
            name="status",
            field=models.CharField(
                choices=[
                    ("SURVEY_IN_PROGRESS", "SURVEY_IN_PROGRESS"),
                    ("SURVEY_DONE", "SURVEY_DONE"),
                    ("SURVEY_APPROVED", "SURVEY_APPROVED"),
                ],
                default="SURVEY_IN_PROGRESS",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="status",
            field=models.CharField(
                choices=[
                    ("SURVEY_IN_PROGRESS", "SURVEY_IN_PROGRESS"),
                    ("SURVEY_DONE", "SURVEY_DONE"),
                    ("SURVEY_APPROVED", "SURVEY_APPROVED"),
                ],
                default="SURVEY_IN_PROGRESS",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="fieldsurveysignature",
            name="field_survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signatures",
                to="resources.FieldSurvey",
            ),
        ),
        migrations.AddField(
            model_name="fieldsurveysignature",
            name="hired",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hirer_signature",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fieldsurveysignature",
            name="hirer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hired_signature",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
