# Generated by Django 2.2.23 on 2022-05-24 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0042_auto_20220524_1035"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldsurveysignature",
            name="field_survey",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signatures",
                to="resources.FieldSurvey",
            ),
        ),
        migrations.AlterField(
            model_name="fieldsurveysignature",
            name="hired",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hirer_signature",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fieldsurveysignature",
            name="hirer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hired_signature",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
