# Generated by Django 2.2.23 on 2022-07-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0043_auto_20220524_1455"),
        ("resources", "0042_auto_20220628_2258"),
    ]

    operations = []
