# Generated by Django 2.2.28 on 2023-01-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0045_auto_20220913_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldsurvey",
            name="final_grade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fieldsurvey",
            name="manual",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="historicalfieldsurvey",
            name="final_grade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfieldsurvey",
            name="manual",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
