# Generated by Django 2.2.28 on 2023-01-19 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0045_auto_20220913_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldsurvey",
            name="executed_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="executed_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
