# Generated by Django 2.2.28 on 2023-02-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0045_fieldsurveyexport_historicalfieldsurveyexport"),
        ("resources", "0045_auto_20220913_1115"),
    ]

    operations = []
