# Generated by Django 2.2.28 on 2023-01-19 14:43

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0046_auto_20230119_0932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldsurvey",
            name="executed_at",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="executed_at",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
