# Generated by Django 2.2.28 on 2023-01-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0046_auto_20230131_1138"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldsurvey",
            name="final_grade",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="final_grade",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
