# Generated by Django 2.2.28 on 2023-02-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0046_merge_20230213_1527"),
        ("resources", "0047_auto_20230131_1444"),
    ]

    operations = []
