# Generated by Django 2.2.28 on 2023-03-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0048_merge_20230228_1523"),
        ("resources", "0047_auto_20230119_1143"),
    ]

    operations = []
