# Generated by Django 2.2.28 on 2023-03-31 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0049_merge_20230328_0753"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="default_grade",
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="default_grade",
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="contract_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fieldsurvey",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SURVEY_IN_PROGRESS", "SURVEY_IN_PROGRESS"),
                    ("SURVEY_DONE", "SURVEY_DONE"),
                    ("SURVEY_APPROVED", "SURVEY_APPROVED"),
                ],
                default="SURVEY_IN_PROGRESS",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="fieldsurveysignature",
            name="hirer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hirer_signature",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="contract_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="contract_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SURVEY_IN_PROGRESS", "SURVEY_IN_PROGRESS"),
                    ("SURVEY_DONE", "SURVEY_DONE"),
                    ("SURVEY_APPROVED", "SURVEY_APPROVED"),
                ],
                default="SURVEY_IN_PROGRESS",
                max_length=100,
            ),
        ),
    ]
