# Generated by Django 2.2.28 on 2023-01-13 12:05

from django.db import migrations
from django_bulk_update.helper import bulk_update


def set_null_default_grade(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Contract = apps.get_model("resources", "Contract")

    contracts = Contract.objects.using(db_alias).all()

    updated_grades = []

    for contract in contracts:
        contract.default_grade = None
        updated_grades.append(contract)

    bulk_update(updated_grades, batch_size=1000, update_fields=["default_grade"])


def reset_set_null_default_grade(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Contract = apps.get_model("Contract")

    contracts = Contract.objects.using(db_alias).all()

    updated_grades = []

    for contract in contracts:
        contract.default_grade = 10
        updated_grades.append(contract)

    bulk_update(updated_grades, batch_size=1000, update_fields=["default_grade"])


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0050_auto_20230331_1359"),
    ]

    operations = [
        migrations.RunPython(
            set_null_default_grade,
            reverse_code=reset_set_null_default_grade,
        )
    ]
