# Generated by Django 2.2.28 on 2023-06-27 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0051_resources_contract_default_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldsurvey",
            name="responsibles_hired",
            field=models.ManyToManyField(
                blank=True,
                related_name="hired_surveys",
                through="resources.FieldSurveySignature",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fieldsurvey",
            name="responsibles_hirer",
            field=models.ManyToManyField(
                blank=True,
                related_name="hirer_surveys",
                through="resources.FieldSurveySignature",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
