# Generated by Django 2.2.28 on 2023-10-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0052_auto_20230627_1022"),
        ("resources", "0053_auto_20230623_1255"),
    ]

    operations = []
