# Generated by Django 2.2.28 on 2023-12-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0054_merge_20231017_1028"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="spent_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="total_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="spent_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="total_price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
