# Generated by Django 2.2.28 on 2024-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0057_recalculate_to_account_for_work_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalmeasurementbulletinexport",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalmeasurementbulletinexport",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalmeasurementbulletinexport",
            name="measurement_bulletin",
        ),
        migrations.DeleteModel(
            name="HistoricalFieldSurveyExport",
        ),
        migrations.DeleteModel(
            name="HistoricalMeasurementBulletinExport",
        ),
    ]
