# Generated by Django 2.2.28 on 2024-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0058_auto_20240808_1040"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitemadministration",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractitemperformance",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractitemunitprice",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractitemadministration",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractitemperformance",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcontractitemunitprice",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
