# Generated by Django 2.2.28 on 2024-09-24 18:49

from django.db import migrations
from django_bulk_update.helper import bulk_update
from tqdm import tqdm


def set_contract_item_order(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ContractService = apps.get_model("resources", "ContractService")

    contract_services = (
        ContractService.objects.using(db_alias)
        .all()
        .prefetch_related(
            "contract_item_unit_prices",
            "contract_item_administration",
            "contract_item_performance",
        )
    )

    for contract_service in tqdm(contract_services):
        item_list = []
        if contract_service.contract_item_unit_prices.exists():
            for index, item in enumerate(
                contract_service.contract_item_unit_prices.all()
                .order_by("sort_string")
                .only("uuid", "sort_string", "order")
            ):
                item.order = index + 1
                item_list.append(item)
        elif contract_service.contract_item_administration.exists():
            for index, item in enumerate(
                contract_service.contract_item_administration.all()
                .order_by("sort_string")
                .only("uuid", "sort_string", "order")
            ):
                item.order = index + 1
                item_list.append(item)
        elif contract_service.contract_item_performance.exists():
            for index, item in enumerate(
                contract_service.contract_item_performance.all()
                .order_by("sort_string")
                .only("uuid", "sort_string", "order")
            ):
                item.order = index + 1
                item_list.append(item)
        else:
            continue

        if item_list:
            bulk_update(item_list, update_fields=["order"])


def reverse_set_contract_item_order(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ContractService = apps.get_model("resources", "ContractService")

    contract_services = (
        ContractService.objects.using(db_alias)
        .all()
        .prefetch_related(
            "contract_item_unit_prices",
            "contract_item_administration",
            "contract_item_performance",
        )
    )

    for contract_service in tqdm(contract_services):
        if contract_service.contract_item_unit_prices.exists():
            contract_service.contract_item_unit_prices.all().update(order=None)
        elif contract_service.contract_item_administration.exists():
            contract_service.contract_item_administration.all().update(order=None)
        elif contract_service.contract_item_performance.exists():
            contract_service.contract_item_performance.all().update(order=None)
        else:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0059_auto_20240924_1451"),
    ]

    operations = [
        migrations.RunPython(
            set_contract_item_order,
            reverse_code=reverse_set_contract_item_order,
        )
    ]
