# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0060_auto_20240924_1549"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcontract",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical contract",
                "verbose_name_plural": "historical contracts",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontractitemadministration",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical contract item administration",
                "verbose_name_plural": "historical contract item administrations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontractitemperformance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical contract item performance",
                "verbose_name_plural": "historical contract item performances",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontractitemunitprice",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical contract item unit price",
                "verbose_name_plural": "historical contract item unit prices",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcontractservice",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical contract service",
                "verbose_name_plural": "historical contract services",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfieldsurvey",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical field survey",
                "verbose_name_plural": "historical field surveys",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalfieldsurveyroad",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical field survey road",
                "verbose_name_plural": "historical field survey roads",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalresource",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical resource",
                "verbose_name_plural": "historical resources",
            },
        ),
        migrations.AlterField(
            model_name="contract",
            name="extra_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="contract",
            name="spend_schedule",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="survey_default",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="fieldsurvey",
            name="grades",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="extra_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="spend_schedule",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="survey_default",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalcontractitemadministration",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcontractitemperformance",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcontractitemunitprice",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcontractservice",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="grades",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurvey",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalfieldsurveyroad",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalresource",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
