# Generated by Django 2.2.28 on 2025-04-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0060_auto_20240924_1549"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitemunitprice",
            name="was_from_import",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcontractitemunitprice",
            name="was_from_import",
            field=models.BooleanField(default=False),
        ),
    ]
