# Generated by Django 3.2.25 on 2025-07-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0062_merge_0061_auto_20250227_1243_0061_auto_20250414_1738"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractitemadministration",
            name="was_from_import",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcontractitemadministration",
            name="was_from_import",
            field=models.BooleanField(default=False),
        ),
    ]
