# Generated by Django 3.2.25 on 2026-01-08 20:51

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "service_orders",
            "0110_merge_0108_auto_20251105_1153_0109_auto_20251105_1413",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "resources",
            "0064_historicalcontract_responsibles_hired_historicalcontract_responsibles_hirer_historicalcontractservic",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractItemPerformanceBulletin",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parent_uuid", models.UUIDField(db_index=True, editable=False)),
                ("weight", models.FloatField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sort_string", models.TextField()),
                (
                    "measurement_bulletins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="measurement_bulletin_contract_items_performance_bulletin",
                        to="service_orders.MeasurementBulletin",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_contract_items_performance_bulletin",
                        to="service_orders.serviceorderresource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalContractServiceBulletin",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("parent_uuid", models.UUIDField(db_index=True, editable=False)),
                ("weight", models.FloatField(blank=True, default=0, null=True)),
                ("price", models.FloatField(blank=True, default=0, null=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="resources.contract",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contract service bulletin",
                "verbose_name_plural": "historical contract service bulletins",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContractItemPerformanceBulletin",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("parent_uuid", models.UUIDField(db_index=True, editable=False)),
                ("weight", models.FloatField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("sort_string", models.TextField()),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="service_orders.serviceorderresource",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contract item performance bulletin",
                "verbose_name_plural": "historical contract item performance bulletins",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContractServiceBulletin",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parent_uuid", models.UUIDField(db_index=True, editable=False)),
                ("weight", models.FloatField(blank=True, default=0, null=True)),
                ("price", models.FloatField(blank=True, default=0, null=True)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_services_bulletins",
                        to="resources.contract",
                    ),
                ),
                (
                    "contract_item_performance",
                    models.ManyToManyField(
                        blank=True,
                        related_name="contract_item_performance_bulletin_services",
                        to="resources.ContractItemPerformanceBulletin",
                    ),
                ),
                (
                    "measurement_bulletins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="measurement_bulletin_contract_services_bulletins",
                        to="service_orders.MeasurementBulletin",
                    ),
                ),
            ],
        ),
    ]
