# Generated by Django 3.2.25 on 2026-01-08 20:57

from django.db import migrations
from tqdm import tqdm

from apps.resources.helpers.create_contract_items import create_contract_bulletin_items


def create_contract_items(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Contract = apps.get_model("resources", "Contract")

    contracts = (
        Contract.objects.using(db_alias)
        .filter(performance_services__isnull=False)
        .distinct()
        .prefetch_related("performance_services", "bulletins")
    )

    for contract in tqdm(contracts):
        contract_services = contract.performance_services.all()
        bulletins = (
            contract.bulletins.filter(bulletin_surveys__isnull=False)
            .distinct()
            .values_list("pk", flat=True)
            or []
        )
        for contract_service in contract_services.prefetch_related(
            "contract_item_performance"
        ):
            create_contract_bulletin_items(
                contract_service, contract, measurement_bulletins=bulletins
            )


def reverse_create_contract_items(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Contract = apps.get_model("resources", "Contract")
    ContractServiceBulletin = apps.get_model("resources", "ContractServiceBulletin")
    ContractItemPerformanceBulletin = apps.get_model(
        "resources", "ContractItemPerformanceBulletin"
    )

    contracts = (
        Contract.objects.using(db_alias)
        .filter(performance_services__isnull=False)
        .distinct()
    )

    for contract in tqdm(contracts):
        contract_service_bulletins = (
            ContractServiceBulletin.objects.using(db_alias)
            .filter(contract=contract)
            .prefetch_related("contract_item_performance")
        )
        contract_item_performance_bulletins_pk_list = (
            ContractItemPerformanceBulletin.objects.using(db_alias)
            .filter(
                contract_item_performance_bulletin_services__in=contract_service_bulletins
            )
            .distinct()
            .values_list("pk", flat=True)
        )
        contract_item_performance_bulletins = (
            ContractItemPerformanceBulletin.objects.filter(
                pk__in=contract_item_performance_bulletins_pk_list
            )
        )

        contract_item_performance_bulletins.delete()
        contract_service_bulletins.delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "resources",
            "0065_contractitemperformancebulletin_contractservicebulletin_historicalcontractitemperformancebulletin_hi",
        ),
    ]

    operations = [
        migrations.RunPython(
            create_contract_items, reverse_code=reverse_create_contract_items
        )
    ]
