# Generated by Django 3.2.25 on 2026-01-23 20:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0075_merge_0074_auto_20250604_1735_0074_auto_20250909_1951"),
        ("resources", "0066_auto_20260108_1757"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractAdditive",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("additional_percentage", models.FloatField(default=0)),
                ("old_price", models.FloatField(default=0)),
                ("new_price", models.FloatField(default=0)),
                ("done", models.BooleanField(default=False)),
                ("error", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_additives",
                        to="companies.company",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_additives",
                        to="resources.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_additives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
