# Generated by Django 2.1.2 on 2018-10-25 14:47

import uuid

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueuedEmail",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("send_to", django.contrib.postgres.fields.jsonb.JSONField()),
                ("title", models.CharField(max_length=100)),
                ("content_plain_text", models.TextField()),
                ("content_html", models.TextField()),
                ("sent", models.BooleanField(default=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
        ),
    ]
