# Generated by Django 2.1.2 on 2018-10-25 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("email_handler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queuedemail",
            name="send_to",
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="send_to_users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
