# Generated by Django 2.1.2 on 2018-10-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0002_auto_20181025_1148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedemail",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
