# Generated by Django 2.1.2 on 2018-10-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0003_auto_20181025_1317"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedemail",
            name="cleared",
            field=models.BooleanField(default=False),
        ),
    ]
