# Generated by Django 2.1.2 on 2019-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0004_queuedemail_cleared"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedemail",
            name="title",
            field=models.TextField(),
        ),
    ]
