# Generated by Django 2.1.2 on 2019-01-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0005_auto_20190108_1258"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queuedemail",
            options={"get_latest_by": ["created_at"], "ordering": ["-created_at"]},
        ),
    ]
