# Generated by Django 2.1.2 on 2020-02-04 10:12

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scarface", "0004_auto_20151217_1131"),
        ("email_handler", "0007_historicalqueuedemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalQueuePush",
            fields=[
                (
                    "pushmessage_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="scarface.PushMessage",
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                ("sound", models.TextField(blank=True, null=True)),
                ("message", models.TextField(default="", null=True)),
                ("has_new_content", models.BooleanField(default=False)),
                ("context_id", models.TextField(default="none", null=True)),
                ("context", models.TextField(default="default", null=True)),
                ("badge_count", models.SmallIntegerField(default=0)),
                ("extra_payload", models.TextField(blank=True, null=True)),
                ("receiver_arn", models.TextField(blank=True, null=True)),
                ("message_type", models.PositiveSmallIntegerField(default=0)),
                ("cleared", models.BooleanField(default=False)),
                ("sent", models.BooleanField(default=False)),
                ("created_at", models.DateField(blank=True, editable=False)),
                ("updated_at", models.DateField(blank=True, editable=False)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical queue push",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="QueuePush",
            fields=[
                (
                    "pushmessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="scarface.PushMessage",
                    ),
                ),
                ("cleared", models.BooleanField(default=False)),
                ("sent", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "devices",
                    models.ManyToManyField(
                        related_name="user_equipments", to="scarface.Device"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": ["created_at"],
            },
            bases=("scarface.pushmessage",),
        ),
    ]
