# Generated by Django 2.1.2 on 2020-02-11 22:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scarface", "0004_auto_20151217_1131"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("email_handler", "0008_historicalqueuepush_queuepush"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalQueuePush",
            new_name="HistoricalQueuedPush",
        ),
        migrations.RenameModel(
            old_name="QueuePush",
            new_name="QueuedPush",
        ),
        migrations.AlterModelOptions(
            name="historicalqueuedpush",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical queued push",
            },
        ),
    ]
