# Generated by Django 2.1.2 on 2020-05-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0009_auto_20200211_1937"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqueuedpush",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queuedpush",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
