# Generated by Django 2.1.2 on 2020-05-16 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0010_auto_20200513_0932"),
        ("email_handler", "0010_emailblacklist_historicalemailblacklist"),
    ]

    operations = []
