# Generated by Django 2.1.2 on 2020-06-11 11:45

from django.db import migrations
from tqdm import tqdm


def create_user_push(apps, schema_editor):
    QueuedPush = apps.get_model("email_handler", "QueuedPush")
    UserPush = apps.get_model("email_handler", "UserPush")
    User = apps.get_model("users", "User")
    db_alias = schema_editor.connection.alias

    for push in tqdm(QueuedPush.objects.using(db_alias).all()):
        users = (
            User.objects.using(db_alias)
            .filter(push_devices__user_equipments=push)
            .distinct()
        )
        for user in users:
            UserPush.objects.using(db_alias).create(
                user=user, push_message=push, read=push.read
            )


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0012_auto_20200611_0844"),
    ]

    operations = [
        migrations.RunPython(create_user_push, reverse_code=migrations.RunPython.noop)
    ]
