# Generated by Django 2.1.2 on 2020-06-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0013_auto_20200611_0845"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalqueuedpush",
            name="read",
        ),
        migrations.RemoveField(
            model_name="queuedpush",
            name="read",
        ),
    ]
