# Generated by Django 2.1.2 on 2020-06-24 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0033_auto_20200521_0005"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("email_handler", "0014_auto_20200611_0907"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqueuedemail",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.Company",
            ),
        ),
        migrations.AddField(
            model_name="historicalqueuedemail",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="historicalqueuedemail",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalqueuedpush",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.Company",
            ),
        ),
        migrations.AddField(
            model_name="historicalqueuedpush",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="historicalqueuedpush",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_emails",
                to="companies.Company",
            ),
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queuedpush",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_pushs",
                to="companies.Company",
            ),
        ),
        migrations.AddField(
            model_name="queuedpush",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="queuedpush",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
