# Generated by Django 2.1.2 on 2020-07-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0015_auto_20200624_1623"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqueuedemail",
            name="error",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="error",
            field=models.BooleanField(default=False),
        ),
    ]
