# Generated by Django 2.1.2 on 2020-07-21 20:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0034_company_key_users"),
        ("email_handler", "0016_auto_20200701_1734"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueuedEmailEvent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_email_events",
                        to="companies.Company",
                    ),
                ),
                (
                    "queued_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_events",
                        to="email_handler.QueuedEmail",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": ["created_at"],
            },
        ),
    ]
