# Generated by Django 2.1.2 on 2020-07-24 18:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0017_queuedemailevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedemailevent",
            name="properties",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
