# Generated by Django 2.1.2 on 2020-09-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0019_auto_20200727_1312"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqueuedemail",
            name="send_anyway",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="send_anyway",
            field=models.BooleanField(default=False),
        ),
    ]
