# Generated by Django 2.1.2 on 2020-09-11 19:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0020_auto_20200911_1428"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqueuedemail",
            name="custom_headers",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="custom_headers",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
