# Generated by Django 2.1.2 on 2021-02-06 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zas", "0003_auto_20210205_2144"),
        ("email_handler", "0022_historicalqueuedpushalertzas_queuedpushalertzas"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqueuedpushalertzas",
            name="threshold",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="zas.Threshold",
            ),
        ),
        migrations.AddField(
            model_name="queuedpushalertzas",
            name="threshold",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="zas.Threshold",
            ),
        ),
    ]
