# Generated by Django 2.1.2 on 2021-02-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0023_auto_20210205_2144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedpushalertzas",
            name="threshold",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zas.Threshold",
            ),
        ),
    ]
