# Generated by Django 2.1.2 on 2021-02-26 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0024_auto_20210223_1349"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedpushalertzas",
            name="threshold",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zas.Threshold",
            ),
        ),
    ]
