# Generated by Django 2.1.2 on 2021-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0025_auto_20210226_1932"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqueuedemail",
            name="in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="in_progress",
            field=models.BooleanField(default=False),
        ),
    ]
