# Generated by Django 2.1.2 on 2021-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0026_auto_20210326_1054"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqueuedpush",
            name="in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="queuedpush",
            name="in_progress",
            field=models.BooleanField(default=False),
        ),
    ]
