# Generated by Django 2.2.28 on 2024-04-22 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0010_filedownload_historicalfiledownload"),
        ("email_handler", "0027_auto_20210326_1056"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqueuedemail",
            name="file_download",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="files.FileDownload",
            ),
        ),
        migrations.AddField(
            model_name="historicalqueuedemail",
            name="issuer",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalqueuedemail",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalqueuedemail",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="file_download",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="file_emails",
                to="files.FileDownload",
            ),
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="issuer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queuedemail",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
