# Generated by Django 2.2.28 on 2024-08-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0028_auto_20240422_1157"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalqueuedemail",
            name="content_html",
        ),
        migrations.RemoveField(
            model_name="historicalqueuedemail",
            name="content_plain_text",
        ),
        migrations.RemoveField(
            model_name="historicalqueuedemail",
            name="custom_headers",
        ),
        migrations.RemoveField(
            model_name="historicalqueuedpush",
            name="extra_payload",
        ),
        migrations.RemoveField(
            model_name="historicalqueuedpush",
            name="message",
        ),
        migrations.RemoveField(
            model_name="historicalqueuedpush",
            name="sound",
        ),
    ]
