# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0029_auto_20240808_1029"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalemailblacklist",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical email blacklist",
                "verbose_name_plural": "historical email blacklists",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalqueuedemail",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical queued email",
                "verbose_name_plural": "historical queued emails",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalqueuedpush",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical queued push",
                "verbose_name_plural": "historical queued pushs",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalqueuedpushalertzas",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical queued push alert zas",
                "verbose_name_plural": "historical queued push alert zass",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaluserpush",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical user push",
                "verbose_name_plural": "historical user pushs",
            },
        ),
        migrations.AlterField(
            model_name="historicalemailblacklist",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalqueuedemail",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalqueuedpush",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalqueuedpush",
            name="id",
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalqueuedpushalertzas",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalqueuedpushalertzas",
            name="id",
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaluserpush",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="queuedemail",
            name="custom_headers",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="queuedemailevent",
            name="properties",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
