# Generated by Django 3.2.25 on 2025-05-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0030_auto_20250227_1243"),
        ("notifications", "0005_migrate_userpush_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalqueuedpushalertzas",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalqueuedpushalertzas",
            name="pushmessage_ptr",
        ),
        migrations.RemoveField(
            model_name="historicalqueuedpushalertzas",
            name="threshold",
        ),
        migrations.RemoveField(
            model_name="historicalqueuedpushalertzas",
            name="zas_area",
        ),
        migrations.RemoveField(
            model_name="historicaluserpush",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaluserpush",
            name="push_message",
        ),
        migrations.RemoveField(
            model_name="historicaluserpush",
            name="user",
        ),
        migrations.RemoveField(
            model_name="queuedpush",
            name="company",
        ),
        migrations.RemoveField(
            model_name="queuedpush",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="queuedpush",
            name="devices",
        ),
        migrations.RemoveField(
            model_name="queuedpush",
            name="pushmessage_ptr",
        ),
        migrations.RemoveField(
            model_name="queuedpush",
            name="users",
        ),
        migrations.RemoveField(
            model_name="queuedpushalertzas",
            name="pushmessage_ptr",
        ),
        migrations.RemoveField(
            model_name="queuedpushalertzas",
            name="threshold",
        ),
        migrations.RemoveField(
            model_name="queuedpushalertzas",
            name="zas_area",
        ),
        migrations.RemoveField(
            model_name="userpush",
            name="push_message",
        ),
        migrations.RemoveField(
            model_name="userpush",
            name="user",
        ),
    ]
