# Generated by Django 3.2.25 on 2025-05-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_handler", "0031_auto_20250527_1157"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalQueuedPush",
        ),
        migrations.DeleteModel(
            name="HistoricalQueuedPushAlertZAS",
        ),
        migrations.DeleteModel(
            name="HistoricalUserPush",
        ),
        migrations.DeleteModel(
            name="QueuedPush",
        ),
        migrations.DeleteModel(
            name="QueuedPushAlertZAS",
        ),
        migrations.DeleteModel(
            name="UserPush",
        ),
    ]
