# Generated by Django 2.2.23 on 2021-06-09 17:45

import datetime
import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("occurrence_records", "0062_merge_20210607_0728"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reportings", "0039_auto_20210506_0900"),
        ("daily_reports", "0022_auto_20210528_1321"),
        ("companies", "0042_populate_firm_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualitySample",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project_number", models.CharField(max_length=200)),
                ("construction_company", models.CharField(max_length=200)),
                ("asphalt_plant", models.CharField(max_length=200)),
                (
                    "form_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                ("number", models.CharField(max_length=40)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("is_proof", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_quality_samples",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_quality_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "multiple_daily_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="multiple_daily_report_quality_samples",
                        to="daily_reports.MultipleDailyReport",
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_quality_samples",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
                (
                    "reporting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reporting_quality_samples",
                        to="reportings.Reporting",
                    ),
                ),
            ],
            options={"ordering": ["company"]},
        ),
        migrations.CreateModel(
            name="HistoricalQualitySample",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "collected_at",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                ("project_number", models.CharField(max_length=200)),
                ("construction_company", models.CharField(max_length=200)),
                ("asphalt_plant", models.CharField(max_length=200)),
                (
                    "form_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                ("number", models.CharField(max_length=40)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("is_proof", models.BooleanField(default=False)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "multiple_daily_report",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="daily_reports.MultipleDailyReport",
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
                (
                    "reporting",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="reportings.Reporting",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical quality sample",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="qualitysample",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("multiple_daily_report__isnull", True),
                        ("reporting__isnull", True),
                    ),
                    models.Q(
                        ("multiple_daily_report__isnull", False),
                        ("reporting__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="either_reporting_or_report_is_filled",
            ),
        ),
    ]
