# Generated by Django 2.2.23 on 2021-06-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality_control", "0001_initial")]

    operations = [
        migrations.RemoveConstraint(
            model_name="qualitysample",
            name="either_reporting_or_report_is_filled",
        ),
        migrations.AddConstraint(
            model_name="qualitysample",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("multiple_daily_report__isnull", True),
                        ("reporting__isnull", False),
                    ),
                    models.Q(
                        ("multiple_daily_report__isnull", False),
                        ("reporting__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="either_reporting_or_report_is_filled",
            ),
        ),
    ]
