# Generated by Django 2.2.23 on 2021-06-10 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality_control", "0002_auto_20210610_0828")]

    operations = [
        migrations.AlterField(
            model_name="historicalqualitysample",
            name="collected_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="qualitysample",
            name="collected_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
