# Generated by Django 2.2.23 on 2021-06-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality_control", "0003_auto_20210610_1134")]

    operations = [
        migrations.AddField(
            model_name="historicalqualitysample",
            name="collected_as_specification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicalqualitysample",
            name="collected_by_construction_company",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="qualitysample",
            name="collected_as_specification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="qualitysample",
            name="collected_by_construction_company",
            field=models.BooleanField(default=True),
        ),
    ]
