# Generated by Django 2.2.23 on 2021-06-24 12:53

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0042_populate_firm_created_by"),
        ("reportings", "0040_reportings_add_address"),
        ("occurrence_records", "0063_auto_20210610_2157"),
        ("quality_control", "0004_auto_20210615_0827"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityAssay",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project_number", models.CharField(max_length=200)),
                (
                    "form_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_quality_assays",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_quality_assays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_quality_assays",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
                (
                    "quality_sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_sample_quality_assays",
                        to="quality_control.QualitySample",
                    ),
                ),
                (
                    "related_assays",
                    models.ManyToManyField(
                        related_name="quality_assay_related_assays",
                        to="quality_control.QualityAssay",
                    ),
                ),
                (
                    "reportings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reporting_quality_assays",
                        to="reportings.Reporting",
                    ),
                ),
            ],
            options={"ordering": ["company"]},
        ),
        migrations.CreateModel(
            name="HistoricalQualityAssay",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("number", models.CharField(max_length=40)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                ("project_number", models.CharField(max_length=200)),
                (
                    "form_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
                (
                    "quality_sample",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="quality_control.QualitySample",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical quality assay",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
