# Generated by Django 2.2.23 on 2021-06-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality_control", "0005_historicalqualityassay_qualityassay")]

    operations = [
        migrations.AlterField(
            model_name="qualityassay",
            name="related_assays",
            field=models.ManyToManyField(
                blank=True,
                related_name="quality_assay_related_assays",
                to="quality_control.QualityAssay",
            ),
        )
    ]
