# Generated by Django 2.2.23 on 2021-07-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality_control", "0006_auto_20210625_0850")]

    operations = [
        migrations.AddField(
            model_name="historicalqualityassay",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="qualityassay",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
