# Generated by Django 2.2.23 on 2021-07-07 11:14

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0042_populate_firm_created_by"),
        ("occurrence_records", "0063_auto_20210610_2157"),
        ("quality_control", "0007_auto_20210702_1328"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalqualityassay", name="project_number"
        ),
        migrations.RemoveField(
            model_name="historicalqualitysample", name="project_number"
        ),
        migrations.RemoveField(model_name="qualityassay", name="project_number"),
        migrations.RemoveField(model_name="qualitysample", name="project_number"),
        migrations.CreateModel(
            name="QualityProject",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_number", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("expires_at", models.DateField()),
                (
                    "form_data",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firm_quality_projects",
                        to="companies.Firm",
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_quality_projects",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
            ],
            options={"ordering": ["firm__company"]},
        ),
        migrations.AddField(
            model_name="historicalqualityassay",
            name="quality_project",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="quality_control.QualityProject",
            ),
        ),
        migrations.AddField(
            model_name="historicalqualitysample",
            name="quality_project",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="quality_control.QualityProject",
            ),
        ),
        migrations.AddField(
            model_name="qualityassay",
            name="quality_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_project_assays",
                to="quality_control.QualityProject",
            ),
        ),
        migrations.AddField(
            model_name="qualitysample",
            name="quality_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_project_samples",
                to="quality_control.QualityProject",
            ),
        ),
    ]
