# Generated by Django 2.2.23 on 2021-07-19 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("quality_control", "0008_auto_20210707_0814")]

    operations = [
        migrations.AddField(
            model_name="qualityproject",
            name="registered_at",
            field=models.DateField(default=django.utils.timezone.now),
        )
    ]
