# Generated by Django 2.2.23 on 2021-09-01 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0042_populate_firm_created_by"),
        ("quality_control", "0009_qualityproject_registered_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="qualitysample",
            name="either_reporting_or_report_is_filled",
        ),
        migrations.RemoveField(
            model_name="historicalqualitysample",
            name="collected_as_specification",
        ),
        migrations.RemoveField(
            model_name="historicalqualitysample",
            name="collected_by_construction_company",
        ),
        migrations.RemoveField(
            model_name="historicalqualitysample", name="construction_company"
        ),
        migrations.RemoveField(
            model_name="historicalqualitysample", name="multiple_daily_report"
        ),
        migrations.RemoveField(
            model_name="qualitysample", name="collected_as_specification"
        ),
        migrations.RemoveField(
            model_name="qualitysample", name="collected_by_construction_company"
        ),
        migrations.RemoveField(model_name="qualitysample", name="construction_company"),
        migrations.RemoveField(
            model_name="qualitysample", name="multiple_daily_report"
        ),
        migrations.AddField(
            model_name="historicalqualitysample",
            name="construction_firm",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.Firm",
            ),
        ),
        migrations.AddField(
            model_name="historicalqualitysample",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="qualitysample",
            name="construction_firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="firm_quality_samples",
                to="companies.Firm",
            ),
        ),
        migrations.AddField(
            model_name="qualitysample",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_responsible_quality_samples",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
