# Generated by Django 2.2.23 on 2021-09-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0044_merge_20210816_2259"),
        ("quality_control", "0010_auto_20210901_0840"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitysample",
            name="reportings",
            field=models.ManyToManyField(
                blank=True,
                related_name="reportings_quality_samples",
                to="reportings.Reporting",
            ),
        )
    ]
