# Generated by Django 2.2.23 on 2021-09-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("quality_control", "0012_auto_20210901_0858")]

    operations = [
        migrations.RemoveField(model_name="historicalqualitysample", name="reporting"),
        migrations.RemoveField(model_name="qualitysample", name="reporting"),
    ]
