# Generated by Django 2.2.23 on 2021-09-03 02:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0042_populate_firm_created_by"),
        ("quality_control", "0013_auto_20210901_0922"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionPlant",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_construction_plants",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_construction_plants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["company"]},
        ),
        migrations.AddField(
            model_name="historicalqualitysample",
            name="construction_plant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="quality_control.ConstructionPlant",
            ),
        ),
        migrations.AddField(
            model_name="qualitysample",
            name="construction_plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="construction_plant_quality_samples",
                to="quality_control.ConstructionPlant",
            ),
        ),
    ]
