# Generated by Django 2.2.23 on 2021-09-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("quality_control", "0015_auto_20210903_1603")]

    operations = [
        migrations.RenameField(
            model_name="historicalqualityassay",
            old_name="collected_at",
            new_name="executed_at",
        ),
        migrations.RenameField(
            model_name="qualityassay",
            old_name="collected_at",
            new_name="executed_at",
        ),
    ]
