# Generated by Django 2.2.23 on 2021-09-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("quality_control", "0016_auto_20210906_0959")]

    operations = [
        migrations.RemoveField(
            model_name="historicalqualitysample", name="asphalt_plant"
        ),
        migrations.RemoveField(model_name="qualitysample", name="asphalt_plant"),
    ]
