# Generated by Django 2.2.23 on 2021-10-27 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0030_csvimport_historicalcsvimport"),
        ("quality_control", "0017_auto_20210913_1639"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqualityassay",
            name="csv_import",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="templates.CSVImport",
            ),
        ),
        migrations.AddField(
            model_name="qualityassay",
            name="csv_import",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="csv_import_assays",
                to="templates.CSVImport",
            ),
        ),
    ]
