# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0019_historicalqualitycontrolexport_qualitycontrolexport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalqualityassay",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical quality assay",
                "verbose_name_plural": "historical quality assays",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalqualitycontrolexport",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical quality control export",
                "verbose_name_plural": "historical quality control exports",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalqualitysample",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical quality sample",
                "verbose_name_plural": "historical quality samples",
            },
        ),
        migrations.AlterField(
            model_name="historicalqualityassay",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalqualityassay",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalqualitycontrolexport",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalqualitysample",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalqualitysample",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="qualityassay",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="qualityproject",
            name="form_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="qualitysample",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
