# Generated by Django 2.1.2 on 2019-02-22 01:07

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("service_orders", "0030_procedureresource_created_by"),
        ("companies", "0008_merge_20190209_2010"),
        ("occurrence_records", "0010_auto_20190212_1829"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporting",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(blank=True, max_length=100)),
                ("editable", models.BooleanField(default=True)),
                (
                    "road_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("km", models.FloatField(default=0)),
                ("project_km", models.FloatField(default=0)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("direction", models.IntegerField(default=0)),
                ("lane", models.IntegerField(default=0)),
                (
                    "occurrence_kind",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "form_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                ("executed_at", models.DateTimeField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviews", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_reportings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="firm_reportings",
                        to="companies.Firm",
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_reportings",
                        to="service_orders.ServiceOrderActionStatus",
                    ),
                ),
            ],
        ),
    ]
