# Generated by Django 2.1.2 on 2019-02-26 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0004_historicaljob_job"),
        ("reportings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporting",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportings",
                to="work_plans.Job",
            ),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportings",
                to="companies.Firm",
            ),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportings",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
    ]
