# Generated by Django 2.1.2 on 2019-03-06 20:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reportings", "0002_auto_20190226_2021"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingFile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "upload",
                    models.FileField(
                        storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                        upload_to="",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_reporting_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporting_files",
                        to="reportings.Reporting",
                    ),
                ),
            ],
        ),
    ]
