# Generated by Django 2.1.2 on 2019-03-07 21:32

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("work_plans", "0004_historicaljob_job"),
        ("companies", "0011_auto_20190307_1137"),
        ("occurrence_records", "0013_occurrencetype_firms"),
        ("service_orders", "0036_merge_20190227_1304"),
        ("reportings", "0003_reportingfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReporting",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("number", models.CharField(blank=True, max_length=100)),
                ("road_name", models.CharField(max_length=50)),
                ("km", models.FloatField()),
                ("project_km", models.FloatField(default=0)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("direction", models.IntegerField()),
                ("lane", models.IntegerField()),
                (
                    "form_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                ("executed_at", models.DateTimeField(default=None, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("found_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Firm",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="work_plans.Job",
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="service_orders.ServiceOrderActionStatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical reporting",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name="reporting",
            name="datetime",
        ),
        migrations.RemoveField(
            model_name="reporting",
            name="editable",
        ),
        migrations.RemoveField(
            model_name="reporting",
            name="occurrence_kind",
        ),
        migrations.RemoveField(
            model_name="reporting",
            name="reviews",
        ),
        migrations.AddField(
            model_name="reporting",
            name="found_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="direction",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="firm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportings",
                to="companies.Firm",
            ),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="km",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="lane",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="road_name",
            field=models.CharField(default="BR280-SC", max_length=50),
            preserve_default=False,
        ),
    ]
