# Generated by Django 2.1.2 on 2019-03-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roads", "0001_initial"),
        ("reportings", "0004_auto_20190307_1832"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="road",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="roads.Road",
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="road",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportings",
                to="roads.Road",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreporting",
            name="direction",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalreporting",
            name="lane",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="direction",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="lane",
            field=models.CharField(max_length=100),
        ),
    ]
