# Generated by Django 2.1.2 on 2019-03-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0005_auto_20190308_1648"),
        ("reportings", "0005_auto_20190311_1531"),
    ]

    operations = []
