# Generated by Django 2.1.2 on 2019-03-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0006_merge_20190312_1203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreporting",
            name="project_km",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="project_km",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
