# Generated by Django 2.1.2 on 2019-03-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0007_auto_20190314_1418"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="reportings.Reporting",
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="reportings.Reporting",
            ),
        ),
    ]
