# Generated by Django 2.1.2 on 2019-03-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0008_auto_20190328_0607"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreportingfile",
            name="include_in_reports",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportingfile",
            name="include_in_reports",
            field=models.BooleanField(default=True),
        ),
    ]
