# Generated by Django 2.1.2 on 2019-04-02 14:14

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("reportings", "0009_auto_20190328_1353"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporting",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="reporting_services",
                through="services.ServiceUsage",
                to="services.Service",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreporting",
            name="form_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="form_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="occurrence_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reporting_occurrence",
                to="occurrence_records.OccurrenceType",
            ),
        ),
    ]
