# Generated by Django 2.1.2 on 2019-05-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reportings", "0011_auto_20190429_1605")]

    operations = [
        migrations.RenameField(
            model_name="historicalreportingfile",
            old_name="include_in_reports",
            new_name="include_dnit",
        ),
        migrations.RenameField(
            model_name="reportingfile",
            old_name="include_in_reports",
            new_name="include_dnit",
        ),
        migrations.AddField(
            model_name="historicalreportingfile",
            name="include_rdo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reportingfile",
            name="include_rdo",
            field=models.BooleanField(default=False),
        ),
    ]
