# Generated by Django 2.1.2 on 2020-01-14 18:34

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def copy_field(apps, schema_editor):
    ReportingFile = apps.get_model("reportings", "ReportingFile")
    ReportingFile.objects.all().update(datetime=F("uploaded_at"))
    HistoricalReportingFile = apps.get_model("reportings", "HistoricalReportingFile")
    HistoricalReportingFile.objects.all().update(datetime=F("uploaded_at"))


class Migration(migrations.Migration):

    dependencies = [("reportings", "0012_auto_20190510_1912")]

    operations = [
        migrations.AddField(
            model_name="historicalreportingfile",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reportingfile",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(copy_field, reverse_code=migrations.RunPython.noop),
    ]
