# Generated by Django 2.1.2 on 2020-01-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0013_auto_20200114_1534"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="due_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="due_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
