# Generated by Django 2.1.2 on 2020-03-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0015_auto_20200218_1527"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="due_at_manually_specified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reporting",
            name="due_at_manually_specified",
            field=models.BooleanField(default=False),
        ),
    ]
