# Generated by Django 2.1.2 on 2020-04-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reportings", "0016_auto_20200319_1534")]

    operations = [
        migrations.AddField(
            model_name="historicalreportingfile",
            name="md5",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reportingfile",
            name="md5",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalreportingfile",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
