# Generated by Django 2.1.2 on 2020-04-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0006_auto_20200129_1453"),
        ("reportings", "0018_fill_md5_from_aws_s3"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="approval_flows.ApprovalStep",
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_reportings",
                to="approval_flows.ApprovalStep",
            ),
        ),
    ]
