# Generated by Django 2.1.2 on 2020-04-30 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0019_auto_20200417_0759"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                default="00000db3-a561-4387-ac47-d48fca2d6c24",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="historicalreporting",
                to="reportings.Reporting",
            ),
            preserve_default=False,
        ),
    ]
