# Generated by Django 2.1.2 on 2020-04-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0019_auto_20200417_0759"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="keywords",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="keywords",
            field=models.TextField(default="", null=True),
        ),
    ]
