# Generated by Django 2.1.2 on 2020-04-30 12:39

from django.db import migrations
from django_bulk_update.helper import bulk_update
from tqdm import tqdm

from helpers.apps.record_filter import create_keywords


def fill_keywords_reportings(apps, schema_editor):
    Reporting = apps.get_model("reportings", "Reporting")
    db_alias = schema_editor.connection.alias

    objs = []
    reportings = Reporting.objects.using(db_alias).all()
    for reporting in tqdm(reportings):
        reporting.keywords = create_keywords(
            reporting.form_data, reporting.occurrence_type
        )
        objs.append(reporting)
    bulk_update(objs, batch_size=2000)


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0020_auto_20200430_0938"),
    ]

    operations = [
        migrations.RunPython(fill_keywords_reportings, migrations.RunPython.noop)
    ]
