# Generated by Django 2.1.2 on 2020-04-30 11:58

from django.db import migrations


def copy_value_to_related_name_reporting(apps, schema_editor):
    HistoricalReporting = apps.get_model("reportings", "HistoricalReporting")
    db_alias = schema_editor.connection.alias
    from django.db.models import F

    HistoricalReporting.objects.using(db_alias).all().update(history_relation=F("uuid"))


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0020_historicalreporting_history_relation"),
    ]

    operations = [
        migrations.RunPython(
            copy_value_to_related_name_reporting, migrations.RunPython.noop
        )
    ]
