# Generated by Django 2.1.2 on 2020-05-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0021_auto_20200430_0939"),
        ("reportings", "0021_auto_20200430_0858"),
    ]

    operations = []
