# Generated by Django 2.1.2 on 2020-05-27 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reportings", "0022_merge_20200503_1700"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportingmessage",
            name="mentioned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentione_users_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
