# Generated by Django 2.1.2 on 2020-05-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0022_merge_20200503_1700"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="end_km_manually_specified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reporting",
            name="end_km_manually_specified",
            field=models.BooleanField(default=False),
        ),
    ]
