# Generated by Django 2.1.2 on 2020-05-28 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0033_auto_20200521_0005"),
        ("reportings", "0023_reportingmessage_mentioned_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportingmessage",
            name="mentioned_firms",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_firm_in_messages",
                to="companies.Firm",
            ),
        ),
        migrations.AlterField(
            model_name="reportingmessage",
            name="mentioned_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentioned_in_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
