# Generated by Django 2.1.2 on 2020-05-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0023_auto_20200528_2017"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="end_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="end_km",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
