# Generated by Django 2.1.2 on 2020-05-29 19:00

from django.db import migrations
from django_bulk_update.helper import bulk_update
from tqdm import tqdm

from helpers.km_converter import calculate_end_km


def calc_end_km(apps, schema_editor):
    Reporting = apps.get_model("reportings", "Reporting")
    db_alias = schema_editor.connection.alias
    # Do not need to disconnect any signal because no one will be executed
    objs = []
    reportings = Reporting.objects.using(db_alias).all().prefetch_related("company")
    for reporting in tqdm(reportings):
        reporting.end_km = calculate_end_km(reporting) or 0
        objs.append(reporting)
    bulk_update(objs, batch_size=2000, update_fields=["end_km"])


class Migration(migrations.Migration):

    dependencies = [("reportings", "0024_auto_20200529_1506")]

    operations = [
        migrations.RunPython(calc_end_km, reverse_code=migrations.RunPython.noop)
    ]
