# Generated by Django 2.1.2 on 2020-06-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0024_auto_20200528_1940"),
        ("reportings", "0025_auto_20200529_1600"),
    ]

    operations = []
