# Generated by Django 2.1.2 on 2020-06-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0026_merge_20200604_1804"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="project_end_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="project_end_km",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
