# Generated by Django 2.1.2 on 2020-06-23 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0028_auto_20200609_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreporting",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_historicalreporting",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
