# Generated by Django 2.1.2 on 2020-06-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0028_auto_20200609_1635"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="project_end_km_manually_specified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reporting",
            name="project_end_km_manually_specified",
            field=models.BooleanField(default=False),
        ),
    ]
