# Generated by Django 2.1.2 on 2020-06-23 12:00

from django.db import migrations
from django_bulk_update.helper import bulk_update
from tqdm import tqdm

from helpers.km_converter import calculate_end_km


def calc_end_kms(apps, schema_editor):
    Reporting = apps.get_model("reportings", "Reporting")
    db_alias = schema_editor.connection.alias
    # Do not need to disconnect any signal because no one will be executed
    objs = []
    reportings = Reporting.objects.using(db_alias).all().prefetch_related("company")
    for reporting in tqdm(reportings):
        if reporting.project_km and reporting.project_km < 0:
            reporting.project_km = 0

        if reporting.km and reporting.km < 0:
            reporting.km = 0

        if not reporting.end_km_manually_specified:
            reporting.end_km = calculate_end_km(reporting)

        if not reporting.project_end_km_manually_specified:
            reporting.project_end_km = calculate_end_km(reporting, project_km=True)

        objs.append(reporting)
    bulk_update(
        objs,
        batch_size=2000,
        update_fields=["project_end_km", "end_km", "project_km", "km"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0029_auto_20200623_0833"),
    ]

    operations = [
        migrations.RunPython(calc_end_kms, reverse_code=migrations.RunPython.noop)
    ]
