# Generated by Django 2.1.2 on 2020-06-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0029_auto_20200623_0937"),
        ("reportings", "0030_auto_20200623_0900"),
    ]

    operations = []
