# Generated by Django 2.1.2 on 2020-06-30 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "templates",
            "0012_historicalexportrequest_historicalmobilesync_mobilesync",
        ),
        ("reportings", "0031_merge_20200624_2206"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="mobile_sync",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sync_historicalreporting",
                to="templates.MobileSync",
            ),
        ),
    ]
