# Generated by Django 2.1.2 on 2020-07-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0031_merge_20200624_2206"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="editable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="editable",
            field=models.BooleanField(default=True),
        ),
    ]
