# Generated by Django 2.1.2 on 2020-07-13 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0032_auto_20200708_1453"),
        ("reportings", "0032_historicalreporting_mobile_sync"),
    ]

    operations = []
