# Generated by Django 2.1.2 on 2020-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0033_merge_20200713_0021"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="lot",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="lot",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
