# Generated by Django 2.1.2 on 2020-08-19 00:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0034_auto_20200728_0955"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="form_metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="reporting",
            name="form_metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
