# Generated by Django 2.1.2 on 2020-11-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reportings", "0035_auto_20200818_2139")]

    operations = [
        migrations.AddField(
            model_name="historicalreportingfile",
            name="kind",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="reportingfile",
            name="kind",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
