# Generated by Django 2.1.2 on 2021-02-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0036_auto_20201113_1553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreporting",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
