# Generated by Django 2.1.2 on 2021-03-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0037_auto_20210217_1611"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="branch",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalreporting",
            name="km_reference",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalreporting",
            name="track",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="branch",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="km_reference",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="track",
            field=models.TextField(blank=True, null=True),
        ),
    ]
