# Generated by Django 2.1.2 on 2021-05-06 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0038_auto_20210302_1554"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="active_inspection",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="reportings.Reporting",
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="active_inspection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_inspection_of_inventory",
                to="reportings.Reporting",
            ),
        ),
    ]
