# Generated by Django 2.2.23 on 2021-06-18 11:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0039_auto_20210506_0900"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="address",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="reporting",
            name="address",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
