# Generated by Django 2.2.23 on 2021-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reportings", "0040_reportings_add_address")]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="technical_opinion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="technical_opinion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
