# Generated by Django 2.2.23 on 2021-07-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constructions", "0004_auto_20210707_1137"),
        ("reportings", "0041_auto_20210702_1042"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="construction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="constructions.Construction",
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="construction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="construction_reportings",
                to="constructions.Construction",
            ),
        ),
    ]
