# Generated by Django 2.2.23 on 2021-07-30 11:42

from django.db import migrations
from tqdm import tqdm

from helpers.strings import get_obj_from_path


def update_csp(apps, schema_editor):
    Reporting = apps.get_model("reportings", "Reporting")
    Company = apps.get_model("companies", "Company")
    db_alias = schema_editor.connection.alias

    try:
        company = Company.objects.filter(
            name__icontains="Eixo SP", metadata__has_key="csp"
        )[0]
        inspect_types = get_obj_from_path(company.metadata, "csp__inspect_types")
    except Exception:
        reportings = Reporting.objects.using(db_alias).filter(
            company__name__icontains="Eixo SP", company__metadata__has_key="csp"
        )
    else:
        reportings = Reporting.objects.using(db_alias).filter(
            occurrence_type_id__in=inspect_types, company=company
        )

    for reporting in tqdm(reportings):
        reporting.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0042_auto_20210707_1351"),
    ]

    operations = [
        migrations.RunPython(update_csp, reverse_code=migrations.RunPython.noop)
    ]
