# Generated by Django 2.2.23 on 2021-08-12 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0029_auto_20210812_1017"),
        ("reportings", "0042_auto_20210707_1351"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="pdf_import",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="templates.PDFImport",
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="pdf_import",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pdf_import_reportings",
                to="templates.PDFImport",
            ),
        ),
    ]
