# Generated by Django 2.2.23 on 2021-08-17 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0043_auto_20210812_1017"),
        ("reportings", "0043_auto_20210730_0842"),
    ]

    operations = []
