# Generated by Django 2.2.23 on 2021-12-01 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0050_auto_20211126_0842"),
        ("reportings", "0044_merge_20210816_2259"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="subcompany",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.SubCompany",
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="subcompany",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcompany_reportings",
                to="companies.SubCompany",
            ),
        ),
    ]
