# Generated by Django 2.2.23 on 2021-12-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("reportings", "0045_auto_20211201_0906")]

    operations = [
        migrations.RemoveField(model_name="historicalreporting", name="subcompany"),
        migrations.RemoveField(model_name="reporting", name="subcompany"),
    ]
