# Generated by Django 2.2.28 on 2023-10-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0047_auto_20220613_0842"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="shared_with_agency",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="shared_with_agency",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
