# Generated by Django 2.2.28 on 2023-05-24 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("reportings", "0048_auto_20230525_1041")]

    operations = [migrations.RunPython(migrations.RunPython.noop)]
