# Generated by Django 2.2.28 on 2023-10-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0048_auto_20231027_1329"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreportingfile",
            name="shared_with_agency",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="reportingfile",
            name="shared_with_agency",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
