# Generated by Django 2.2.28 on 2023-11-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0049_auto_20231031_1314"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalreportingfile",
            name="shared_with_agency",
        ),
        migrations.RemoveField(
            model_name="reportingfile",
            name="shared_with_agency",
        ),
        migrations.AddField(
            model_name="historicalreportingfile",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reportingfile",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
    ]
