# Generated by Django 2.2.28 on 2023-07-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0049_create_menus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recordmenu",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="recordmenurelation",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="historicalreporting",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="reportings.RecordMenu",
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="record_menu_reportings",
                to="reportings.RecordMenu",
            ),
        ),
    ]
