# Generated by Django 2.2.28 on 2024-01-05 12:55

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0009_auto_20200430_0820"),
        ("reportings", "0050_auto_20230901_1441"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="active_tile_layer",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="maps.TileLayer",
            ),
        ),
        migrations.AddField(
            model_name="historicalreporting",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="historicalreporting",
            name="properties",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="active_tile_layer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tyle_layer_reportings",
                to="maps.TileLayer",
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="properties",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list
            ),
        ),
    ]
