# Generated by Django 2.2.28 on 2023-07-14 15:52

from django.db import migrations
from django.db.models import Q

from apps.companies.const.app_types import ENERGY
from apps.companies.models import Company
from apps.reportings.models import RecordMenu, RecordMenuRelation
from apps.users.models import User


def get_active_users(company_instance, user_model):
    active_users_id = (
        company_instance.userincompany_set.all()
        .values_list("user", flat=True)
        .distinct()
    )
    return user_model.objects.filter(uuid__in=active_users_id)


def create_users_menus(
    record_menu: RecordMenu,
    user_model: User,
    record_menu_relation_model: RecordMenuRelation,
    order: int,
    company: Company,
):
    active_users = get_active_users(company, user_model)

    record_menu_relation_entries = []
    for user_instance in active_users:
        record_menu_relation_entries.append(
            record_menu_relation_model(
                record_menu=record_menu,
                user=user_instance,
                order=order,
                company=company,
            )
        )
    record_menu_relation_model.objects.bulk_create(record_menu_relation_entries)


def create_menus(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_type = ContentType.objects.get(app_label="reportings", model="reporting")
    Company = apps.get_model("companies", "company")
    companies = (
        Company.objects.using(db_alias)
        .all()
        .exclude(Q(mobile_app_override=ENERGY) | Q(company_group__mobile_app=ENERGY))
        .distinct()
    )
    RecordMenu = apps.get_model("reportings", "recordmenu")
    RecordMenuRelation = apps.get_model("reportings", "recordmenurelation")
    RecordPanel = apps.get_model("occurrence_records", "recordpanel")
    User = apps.get_model("users", "user")
    Reporting = apps.get_model("reportings", "Reporting")

    for company in companies:
        fallback_menu = RecordMenu.objects.using(db_alias).create(
            name="Apontamentos",
            content_type=content_type,
            order=2,
            system_default=False,
            company=company,
            created_by=None,
        )
        _ = RecordMenu.objects.using(db_alias).create(
            name="Todos Apontamentos",
            content_type=content_type,
            order=99999,
            system_default=True,
            company=company,
            created_by=None,
        )

        # Add all previously existing panels of the company to the new menu
        orphan_panels = RecordPanel.objects.using(db_alias).filter(
            company=company, menu__isnull=True, system_default=False
        )
        orphan_panels.update(menu=fallback_menu.pk)

        # Fill menu field of reportings
        reportings = (
            Reporting.objects.using(db_alias)
            .filter(company=company, menu__isnull=True)
            .exclude(occurrence_type__occurrence_kind="2")
            .only("uuid")
        )
        reportings.update(menu_id=fallback_menu.pk)

        create_users_menus(
            record_menu=fallback_menu,
            user_model=User,
            record_menu_relation_model=RecordMenuRelation,
            order=1,
            company=company,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("reportings", "0050_auto_20230714_1150"),
        ("occurrence_records", "0083_auto_20230627_1146"),
    ]

    operations = [migrations.RunPython(create_menus)]
