# Generated by Django 2.2.28 on 2024-01-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0050_auto_20230901_1441"),
        ("reportings", "0050_auto_20231103_1140"),
    ]

    operations = []
