# Generated by Django 2.2.28 on 2023-10-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0051_create_reporting_relation"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="created_recuperations_with_relation",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="created_recuperations_with_relation",
            field=models.BooleanField(null=True),
        ),
    ]
