# Generated by Django 2.2.28 on 2024-01-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0009_auto_20200430_0820"),
        ("reportings", "0052_fill_geometry_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporting",
            name="active_shape_files",
            field=models.ManyToManyField(
                blank=True, related_name="shape_file_reportings", to="maps.ShapeFile"
            ),
        ),
    ]
