# Generated by Django 2.2.28 on 2024-01-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0051_merge_20240115_1528"),
        ("reportings", "0052_auto_20231031_1522"),
    ]

    operations = []
