# Generated by Django 2.2.28 on 2024-02-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reportings",
            "0051_historicalreportinginreportingasyncbatch_reportinginreportingasyncbatch",
        ),
        ("reportings", "0053_merge_20240116_1606"),
    ]

    operations = []
