# Generated by Django 2.2.23 on 2024-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportings", "0053_merge_20240116_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="artesp_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalreporting",
            name="artesp_due_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="historicalreporting",
            name="artesp_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalreporting",
            name="artesp_status",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="artesp_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="artesp_due_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="artesp_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="artesp_status",
            field=models.TextField(blank=True),
        ),
    ]
