# Generated by Django 2.2.28 on 2024-03-28 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reportings", "0053_reporting_active_shape_files"),
        ("reportings", "0054_merge_20240214_1610"),
    ]

    operations = []
