# Generated by Django 2.2.28 on 2024-02-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportings", "0054_auto_20240214_1759"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="artesp_occurrence_type",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalreporting",
            name="artesp_updated_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="artesp_occurrence_type",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="artesp_updated_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.RemoveField(
            model_name="historicalreporting",
            name="artesp_status",
        ),
        migrations.RemoveField(
            model_name="reporting",
            name="artesp_status",
        ),
        migrations.AddField(
            model_name="historicalreporting",
            name="artesp_status",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="artesp_status",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
