# Generated by Django 2.2.28 on 2024-05-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportings", "0055_merge_20240328_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="manual_geometry",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reporting",
            name="manual_geometry",
            field=models.BooleanField(default=False),
        ),
    ]
