# Generated by Django 2.2.28 on 2024-07-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0056_auto_20240521_1439"),
        ("reportings", "0052_update_system_menus_order"),
    ]

    operations = []
