# Generated by Django 2.2.28 on 2024-09-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0057_merge_20240724_1005"),
        ("reportings", "0055_auto_20240226_0924"),
    ]

    operations = []
