# Generated by Django 2.2.28 on 2024-09-12 14:25

from django.db import migrations
from django_bulk_update.helper import bulk_update
from tqdm import tqdm


def populate_user_permission_with_record_menu_perms(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    UserPermission = apps.get_model("permissions", "UserPermission")
    user_permission_qs = (
        UserPermission.objects.using(db_alias)
        .filter(companies__company_group__mobile_app="road")
        .distinct()
    )

    updated_items = []
    reporting_export_value = {
        "can_edit": True,
        "can_view": True,
        "queryset": "all",
        "can_create": True,
        "can_delete": True,
        "can_delete_all": False,
    }
    for user_permission in tqdm(user_permission_qs):
        user_permission.permissions.update({"RecordMenu": reporting_export_value})
        updated_items.append(user_permission)

    if updated_items:
        bulk_update(updated_items, batch_size=100, update_fields=["permissions"])


def reverse_populate_user_permission_with_record_menu_perms(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    UserPermission = apps.get_model("permissions", "UserPermission")
    user_permission_qs = (
        UserPermission.objects.using(db_alias)
        .filter(companies__company_group__mobile_app="road")
        .distinct()
    )

    updated_items = []
    for user_permission in tqdm(user_permission_qs):
        if "RecordMenu" in user_permission.permissions:
            user_permission.permissions.pop("RecordMenu", None)
            updated_items.append(user_permission)

    if updated_items:
        bulk_update(updated_items, batch_size=100, update_fields=["permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0057_merge_20240724_1005"),
    ]

    operations = [
        migrations.RunPython(
            populate_user_permission_with_record_menu_perms,
            reverse_code=reverse_populate_user_permission_with_record_menu_perms,
        )
    ]
