# Generated by Django 2.2.28 on 2024-10-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0058_add_record_menu_permissions_to_users"),
        ("reportings", "0058_merge_20240912_1120"),
    ]

    operations = []
