# Generated by Django 2.2.28 on 2024-10-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0059_merge_20240912_1801"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reporting",
            options={"ordering": ["uuid"]},
        ),
    ]
