# Generated by Django 2.2.28 on 2025-01-13 14:24

from django.db import migrations


def fill_reportings_created_recuperations_with_relation(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Reporting = apps.get_model("reportings", "Reporting")
    reporting_qs = (
        Reporting.objects.using(db_alias)
        .filter(inspection_jobs__isnull=False, created_recuperations_with_relation=None)
        .distinct()
    )
    reporting_qs.update(created_recuperations_with_relation=True)


def reverse_fill_reportings_created_recuperations_with_relation(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Reporting = apps.get_model("reportings", "Reporting")
    reporting_qs = (
        Reporting.objects.using(db_alias)
        .filter(inspection_jobs__isnull=False, created_recuperations_with_relation=True)
        .distinct()
    )
    reporting_qs.update(created_recuperations_with_relation=None)


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0060_auto_20241016_1433"),
    ]

    operations = [
        migrations.RunPython(
            fill_reportings_created_recuperations_with_relation,
            reverse_code=reverse_fill_reportings_created_recuperations_with_relation,
        )
    ]
