# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0061_auto_20250113_1124"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalrecordmenu",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical record menu",
                "verbose_name_plural": "historical record menus",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrecordmenurelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical record menu relation",
                "verbose_name_plural": "historical record menu relations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreporting",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical reporting",
                "verbose_name_plural": "historical reportings",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreportingfile",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical reporting file",
                "verbose_name_plural": "historical reporting files",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreportinginreporting",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical reporting in reporting",
                "verbose_name_plural": "historical reporting in reportings",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreportinginreportingasyncbatch",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical reporting in reporting async batch",
                "verbose_name_plural": "historical reporting in reporting async batchs",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreportingmessage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical reporting message",
                "verbose_name_plural": "historical reporting messages",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreportingmessagereadreceipt",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical reporting message read receipt",
                "verbose_name_plural": "historical reporting message read receipts",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreportingrelation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical reporting relation",
                "verbose_name_plural": "historical reporting relations",
            },
        ),
        migrations.AlterField(
            model_name="historicalrecordmenu",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalrecordmenurelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalreporting",
            name="address",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalreporting",
            name="form_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalreporting",
            name="form_metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="historicalreporting",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalreporting",
            name="properties",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="historicalreportingfile",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalreportinginreporting",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalreportinginreportingasyncbatch",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalreportinginreportingasyncbatch",
            name="pending_batch_items",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreportingmessage",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalreportingmessagereadreceipt",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalreportingrelation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="address",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="form_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="form_metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="properties",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="reportinginreportingasyncbatch",
            name="pending_batch_items",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
