# Generated by Django 3.2.25 on 2025-07-04 19:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0062_auto_20250227_1243"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportingBulkEdit",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edit_data", models.JSONField(default=dict)),
                ("done", models.BooleanField(default=False)),
                ("error", models.BooleanField(default=False)),
                (
                    "reportings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reporting_bulk_edits",
                        to="reportings.Reporting",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_bulk_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
