# Generated by Django 3.2.25 on 2025-08-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0062_auto_20250227_1243"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalreporting",
            name="artesp_code",
        ),
        migrations.RemoveField(
            model_name="historicalreporting",
            name="artesp_due_at",
        ),
        migrations.RemoveField(
            model_name="historicalreporting",
            name="artesp_notes",
        ),
        migrations.RemoveField(
            model_name="historicalreporting",
            name="artesp_occurrence_type",
        ),
        migrations.RemoveField(
            model_name="historicalreporting",
            name="artesp_status",
        ),
        migrations.RemoveField(
            model_name="historicalreporting",
            name="artesp_updated_at",
        ),
        migrations.RemoveField(
            model_name="reporting",
            name="artesp_code",
        ),
        migrations.RemoveField(
            model_name="reporting",
            name="artesp_due_at",
        ),
        migrations.RemoveField(
            model_name="reporting",
            name="artesp_notes",
        ),
        migrations.RemoveField(
            model_name="reporting",
            name="artesp_occurrence_type",
        ),
        migrations.RemoveField(
            model_name="reporting",
            name="artesp_status",
        ),
        migrations.RemoveField(
            model_name="reporting",
            name="artesp_updated_at",
        ),
    ]
