# Generated by Django 3.2.25 on 2025-09-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0063_auto_20250804_1317"),
        ("reportings", "0063_reportingbulkedit"),
    ]

    operations = []
