# Generated by Django 3.2.25 on 2025-09-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0064_normalize_keywords_data"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="-- Extension will remain available",
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "reportings_keywords_gin_idx" ON "reportings_reporting" USING gin ("keywords" gin_trgm_ops);',
            reverse_sql='DROP INDEX IF EXISTS "reportings_keywords_gin_idx";',
        ),
    ]
