# Generated by Django 3.2.25 on 2025-11-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0065_reporting_reportings_keywords_gin_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporting",
            name="inventory_candidates",
            field=models.ManyToManyField(
                blank=True,
                related_name="inventory_candidates_for",
                to="reportings.Reporting",
            ),
        ),
    ]
