# Generated by Django 3.2.25 on 2026-04-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0066_reporting_inventory_candidates"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporting",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reporting",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
