# Generated by Django 2.2.23 on 2022-03-16 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("to_dos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="historicaltodo", name="responsible"),
        migrations.RemoveField(model_name="todo", name="responsible"),
        migrations.AddField(
            model_name="todo",
            name="responsibles",
            field=models.ManyToManyField(
                related_name="responsible_todos", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
