# Generated by Django 2.2.23 on 2022-03-27 14:24

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0012_auto_20220327_1124"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("to_dos", "0003_auto_20220326_1757"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToDoActionStep",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "destinatary",
                    models.CharField(
                        choices=[
                            ("responsible", "responsible"),
                            ("notified", "notified"),
                            ("creator", "creator"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "approval_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_steps",
                        to="approval_flows.ApprovalStep",
                    ),
                ),
                (
                    "todo_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_steps",
                        to="to_dos.ToDoAction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalToDoActionStep",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "destinatary",
                    models.CharField(
                        choices=[
                            ("responsible", "responsible"),
                            ("notified", "notified"),
                            ("creator", "creator"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approval_step",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="approval_flows.ApprovalStep",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "todo_action",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="to_dos.ToDoAction",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical to do action step",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
