# Generated by Django 2.2.23 on 2022-04-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_dos", "0004_historicaltodoactionstep_todoactionstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltodoaction",
            name="default_options",
            field=models.CharField(
                blank=True,
                choices=[("see", "see"), ("resource", "resource")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="todoaction",
            name="default_options",
            field=models.CharField(
                blank=True,
                choices=[("see", "see"), ("resource", "resource")],
                max_length=100,
                null=True,
            ),
        ),
    ]
