# Generated by Django 2.2.28 on 2023-08-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_dos", "0005_auto_20220417_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltodo",
            name="read_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="read_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
