# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_dos", "0006_auto_20230804_1339"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaltodo",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical to do",
                "verbose_name_plural": "historical to dos",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltodoaction",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical to do action",
                "verbose_name_plural": "historical to do actions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltodoactionstep",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical to do action step",
                "verbose_name_plural": "historical to do action steps",
            },
        ),
        migrations.AlterField(
            model_name="historicaltodo",
            name="description",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltodo",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltodoaction",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltodoactionstep",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
