# Generated by Django 2.1.1 on 2018-10-16 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_watchpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchpoint",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.City",
            ),
        ),
        migrations.AlterField(
            model_name="watchpoint",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.Location",
            ),
        ),
        migrations.AlterField(
            model_name="watchpoint",
            name="river",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.River",
            ),
        ),
    ]
