# Generated by Django 2.1.2 on 2018-11-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_auto_20181016_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="river",
            name="cities",
            field=models.ManyToManyField(to="locations.City"),
        ),
    ]
