# Generated by Django 2.1.2 on 2018-11-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_river_cities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="river",
            name="cities",
            field=models.ManyToManyField(
                blank=True, related_name="rivers_in_cities", to="locations.City"
            ),
        ),
    ]
