# Generated by Django 2.1.2 on 2018-11-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_auto_20181101_1539"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="river",
            name="cities",
        ),
        migrations.AddField(
            model_name="river",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="rivers_in_location", to="locations.Location"
            ),
        ),
    ]
