# Generated by Django 2.1.2 on 2019-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_auto_20181101_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="river",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="watchpoint",
            name="name",
            field=models.TextField(),
        ),
    ]
