# Generated by Django 2.1.2 on 2019-08-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "locations",
            "0008_historicalcity_historicallocation_historicalriver_historicalwatchpoint",
        )
    ]

    operations = [
        migrations.RemoveField(model_name="historicalwatchpoint", name="city"),
        migrations.RemoveField(model_name="historicalwatchpoint", name="company"),
        migrations.RemoveField(model_name="historicalwatchpoint", name="history_user"),
        migrations.RemoveField(model_name="historicalwatchpoint", name="location"),
        migrations.RemoveField(model_name="historicalwatchpoint", name="river"),
        migrations.RemoveField(model_name="watchpoint", name="city"),
        migrations.RemoveField(model_name="watchpoint", name="company"),
        migrations.RemoveField(model_name="watchpoint", name="location"),
        migrations.RemoveField(model_name="watchpoint", name="river"),
        migrations.DeleteModel(name="HistoricalWatchPoint"),
        migrations.DeleteModel(name="WatchPoint"),
    ]
