# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0009_auto_20190809_1341"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcity",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical city",
                "verbose_name_plural": "historical citys",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallocation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical location",
                "verbose_name_plural": "historical locations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalriver",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical river",
                "verbose_name_plural": "historical rivers",
            },
        ),
        migrations.AlterField(
            model_name="historicalcity",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicallocation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalriver",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
