# Generated by Django 2.1.2 on 2019-03-07 23:14

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0011_auto_20190307_1137"),
    ]

    operations = [
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "direction",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Norte"),
                            (2, "Sul"),
                            (3, "Leste"),
                            (4, "Oeste"),
                            (5, "Ambos"),
                            (6, "Não se aplica"),
                        ],
                    ),
                ),
                ("marks", django.contrib.postgres.fields.jsonb.JSONField()),
                ("uf", models.CharField(blank=True, max_length=50)),
                (
                    "path",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, dim=3, null=True, srid=4326
                    ),
                ),
                ("length", models.FloatField(blank=True, null=True)),
                (
                    "company",
                    models.ManyToManyField(
                        related_name="company_roads", to="companies.Company"
                    ),
                ),
            ],
        ),
    ]
