# Generated by Django 2.1.2 on 2019-08-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="road",
            name="direction",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Norte"),
                    (1, "Sul"),
                    (2, "Leste"),
                    (3, "Oeste"),
                    (4, "Ambos"),
                    (5, "Não se aplica"),
                ],
            ),
        ),
    ]
