# Generated by Django 2.1.2 on 2020-07-15 00:05

from django.db import migrations, models
from tqdm import tqdm


def forwards_func(apps, schema_editor):
    Road = apps.get_model("roads", "Road")

    db_alias = schema_editor.connection.alias

    existing_roads = Road.objects.using(db_alias).all()

    for road in tqdm(existing_roads):
        if all(["index" in mark for mark in road.marks.values()]):
            road.all_marks_have_indexes = True
            road.save()


class Migration(migrations.Migration):

    dependencies = [("roads", "0004_auto_20200320_0848")]

    operations = [
        migrations.AddField(
            model_name="historicalroad",
            name="all_marks_have_indexes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="road",
            name="all_marks_have_indexes",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
    ]
