# Generated by Django 2.1.2 on 2020-07-28 12:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roads", "0005_auto_20200714_2105"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalroad",
            name="lot_logic",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="lot_logic",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
