# Generated by Django 2.1.2 on 2020-12-02 15:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roads", "0006_auto_20200728_0908"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalroad",
            name="lane_type_logic",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="road",
            name="lane_type_logic",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
