# Generated by Django 2.2.23 on 2022-04-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roads", "0007_auto_20201202_1226"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalroad",
            name="manual_road",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="road",
            name="manual_road",
            field=models.BooleanField(default=False),
        ),
    ]
