# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roads", "0008_auto_20220407_1805"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalroad",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical road",
                "verbose_name_plural": "historical roads",
            },
        ),
        migrations.AlterField(
            model_name="historicalroad",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalroad",
            name="id",
            field=models.IntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalroad",
            name="lane_type_logic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalroad",
            name="lot_logic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalroad",
            name="marks",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="historicalroad",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="road",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="road",
            name="lane_type_logic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="road",
            name="lot_logic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="road",
            name="marks",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="road",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
