# Generated by Django 3.2.25 on 2025-12-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roads", "0009_auto_20250227_1243"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalroad",
            name="is_default_segment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="road",
            name="is_default_segment",
            field=models.BooleanField(default=False),
        ),
    ]
