# Generated by Django 3.2.25 on 2026-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roads", "0010_auto_20250227_1243"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalroad",
            name="city_logic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="road",
            name="city_logic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
