# Generated by Django 2.1.2 on 2018-10-24 14:08

from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                upload_to="avatars/",
            ),
        ),
    ]
