# Generated by Django 2.1.2 on 2018-10-25 13:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def add_user_configuration(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.all().update(configuration={"send_email_notifications": True})


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="configuration",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(add_user_configuration, migrations.RunPython.noop),
    ]
