# Generated by Django 2.1.2 on 2019-01-08 14:58

from django.db import migrations, models

import helpers.validators.brazilian_documents


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[helpers.validators.brazilian_documents.validate_CPF],
            ),
        ),
    ]
