# Generated by Django 2.1.2 on 2019-01-15 17:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_auto_20190108_1258"),
        ("users", "0004_auto_20190108_1258"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationUser",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(null=True)),
                ("occupation", models.TextField(null=True)),
                ("role", models.TextField(null=True)),
                ("firm", models.TextField(null=True)),
                ("council_name", models.TextField(blank=True)),
                ("council_number", models.IntegerField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("cellphone", models.TextField(null=True)),
                ("technician", models.BooleanField(default=False)),
                ("companies", models.ManyToManyField(to="companies.Company")),
            ],
        ),
    ]
