# Generated by Django 2.1.2 on 2019-01-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_registrationuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationuser",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="registrationuser",
            name="last_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="registrationuser",
            name="password",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="registrationuser",
            name="username",
            field=models.TextField(null=True),
        ),
    ]
