# Generated by Django 2.1.2 on 2019-01-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20190122_1535"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationuser",
            old_name="council_name",
            new_name="board_registration",
        ),
        migrations.RemoveField(
            model_name="registrationuser",
            name="council_number",
        ),
    ]
