# Generated by Django 2.1.2 on 2019-01-25 18:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_auto_20190123_1724"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationuser",
            name="board_registration",
        ),
        migrations.RemoveField(
            model_name="registrationuser",
            name="cellphone",
        ),
        migrations.RemoveField(
            model_name="registrationuser",
            name="firm",
        ),
        migrations.RemoveField(
            model_name="registrationuser",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="registrationuser",
            name="role",
        ),
        migrations.RemoveField(
            model_name="registrationuser",
            name="technician",
        ),
        migrations.AddField(
            model_name="registrationuser",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
