# Generated by Django 2.1.2 on 2019-01-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20190125_1659"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationuser",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="registrationuser",
            name="username",
            field=models.TextField(null=True, unique=True),
        ),
    ]
