# Generated by Django 2.1.2 on 2019-01-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20190125_1853"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationuser",
            name="companies",
            field=models.ManyToManyField(
                related_name="registration_companies", to="companies.Company"
            ),
        ),
    ]
