# Generated by Django 2.1.2 on 2019-02-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scarface", "0004_auto_20151217_1131"),
        ("users", "0011_auto_20190130_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="push_devices",
            field=models.ManyToManyField(
                related_name="device_users", to="scarface.Device"
            ),
        ),
    ]
