# Generated by Django 2.1.2 on 2019-06-17 13:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0013_historicalregistrationuser_historicaluser")]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="jwt_secret",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="user",
            name="jwt_secret",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
