# Generated by Django 2.1.2 on 2019-06-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20190617_1012"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="jwt_secret",
        ),
        migrations.RemoveField(
            model_name="user",
            name="jwt_secret",
        ),
    ]
