# Generated by Django 2.1.2 on 2019-06-26 03:30

from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_auto_20190626_0030"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="jwt_secret",
            field=models.CharField(
                default=apps.users.models.default_jwt_secret, max_length=50
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="jwt_secret",
            field=models.CharField(
                default=apps.users.models.default_jwt_secret, max_length=50
            ),
        ),
    ]
