# Generated by Django 2.1.2 on 2019-06-26 03:30

from django.db import migrations, models

import apps.users.models


def set_jwt(apps, schema_editor):
    User = apps.get_model("users", "User")
    for row in User.objects.all():
        row.jwt_secret = "c2343f09d-08J-8-98M-((__M--8j-8j-vçlkxcxlknv__))"
        row.save(update_fields=["jwt_secret"])


class Migration(migrations.Migration):

    dependencies = [("users", "0016_auto_20190626_0030")]

    operations = [migrations.RunPython(set_jwt, reverse_code=migrations.RunPython.noop)]
