# Generated by Django 2.1.2 on 2019-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_set_default_jwt"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="saml_idp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="saml_nameid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="saml_idp",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="saml_nameid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
