# Generated by Django 2.1.2 on 2019-10-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0023_auto_20191004_1331"),
        ("users", "0018_auto_20190827_1430"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="company_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.CompanyGroup",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_users",
                to="companies.CompanyGroup",
            ),
        ),
    ]
