# Generated by Django 2.1.2 on 2020-05-19 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0023_auto_20200504_1818")]

    operations = [
        migrations.RemoveField(model_name="historicalsupervisor", name="company"),
        migrations.RemoveField(model_name="historicalsupervisor", name="history_user"),
        migrations.RemoveField(model_name="historicalsupervisor", name="user"),
        migrations.RemoveField(model_name="supervisor", name="company"),
        migrations.RemoveField(model_name="supervisor", name="user"),
        migrations.AddField(
            model_name="historicaluser",
            name="is_supervisor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_supervisor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervisor_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="HistoricalSupervisor"),
        migrations.DeleteModel(name="Supervisor"),
    ]
