# Generated by Django 2.1.2 on 2020-07-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0024_auto_20200518_2133")]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="auth_error",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="auth_error",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
