# Generated by Django 2.1.2 on 2020-08-22 15:17

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_auto_20200708_0014"),
    ]

    operations = [UnaccentExtension()]
