# Generated by Django 2.1.2 on 2020-09-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_auto_20200822_1217"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="has_accepted_tos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="has_accepted_tos",
            field=models.BooleanField(default=False),
        ),
    ]
