# Generated by Django 2.2.28 on 2022-09-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0054_auto_20220711_1147"),
        ("users", "0028_historicalusernotification_usernotification"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usernotification",
            unique_together={("company", "user", "notification", "notification_type")},
        ),
    ]
