# Generated by Django 2.2.28 on 2022-09-23 18:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_auto_20220908_0831"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalusernotification",
            name="debounce_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalusernotification",
            name="last_notified",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="debounce_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="last_notified",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
