# Generated by Django 2.2.28 on 2022-09-23 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_auto_20220923_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalusernotification",
            name="last_checked",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="last_checked",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
