# Generated by Django 2.2.28 on 2023-01-24 14:37

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_auto_20220923_1559"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalusernotification",
            name="preferred_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalusernotification",
            name="time_interval",
            field=models.DurationField(
                choices=[
                    ("IMMEDIATE", datetime.timedelta(0)),
                    ("TENMIN", datetime.timedelta(seconds=600)),
                    ("HALFHOUR", datetime.timedelta(seconds=1800)),
                    ("HOUR", datetime.timedelta(seconds=3600)),
                    ("DAY", datetime.timedelta(days=1)),
                    ("WEEK", datetime.timedelta(days=7)),
                    ("MONTH", datetime.timedelta(days=28)),
                ],
                default=datetime.timedelta(0),
            ),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="preferred_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="time_interval",
            field=models.DurationField(
                choices=[
                    ("IMMEDIATE", datetime.timedelta(0)),
                    ("TENMIN", datetime.timedelta(seconds=600)),
                    ("HALFHOUR", datetime.timedelta(seconds=1800)),
                    ("HOUR", datetime.timedelta(seconds=3600)),
                    ("DAY", datetime.timedelta(days=1)),
                    ("WEEK", datetime.timedelta(days=7)),
                    ("MONTH", datetime.timedelta(days=28)),
                ],
                default=datetime.timedelta(0),
            ),
        ),
    ]
