# Generated by Django 2.2.28 on 2023-01-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0054_auto_20220711_1147"),
        ("users", "0032_auto_20230124_1137"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usernotification",
            unique_together={
                (
                    "company",
                    "user",
                    "notification",
                    "notification_type",
                    "time_interval",
                )
            },
        ),
    ]
