# Generated by Django 2.2.28 on 2023-01-31 14:04

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_auto_20230124_1157"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalusernotification",
            name="time_interval",
            field=models.DurationField(
                choices=[
                    (datetime.timedelta(0), "IMMEDIATE"),
                    (datetime.timedelta(seconds=600), "TENMIN"),
                    (datetime.timedelta(seconds=1800), "HALFHOUR"),
                    (datetime.timedelta(seconds=3600), "HOUR"),
                    (datetime.timedelta(days=1), "DAY"),
                    (datetime.timedelta(days=7), "WEEK"),
                    (datetime.timedelta(days=28), "MONTH"),
                ],
                default=datetime.timedelta(0),
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="time_interval",
            field=models.DurationField(
                choices=[
                    (datetime.timedelta(0), "IMMEDIATE"),
                    (datetime.timedelta(seconds=600), "TENMIN"),
                    (datetime.timedelta(seconds=1800), "HALFHOUR"),
                    (datetime.timedelta(seconds=3600), "HOUR"),
                    (datetime.timedelta(days=1), "DAY"),
                    (datetime.timedelta(days=7), "WEEK"),
                    (datetime.timedelta(days=28), "MONTH"),
                ],
                default=datetime.timedelta(0),
            ),
        ),
    ]
