# Generated by Django 2.2.28 on 2023-01-31 14:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_auto_20230131_1104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalusernotification",
            name="debounce_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="debounce_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        ),
    ]
