# Generated by Django 2.2.28 on 2023-05-12 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0037_auto_20230331_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
