# Generated by Django 2.2.28 on 2023-08-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0057_merge_20230601_1835"),
        ("users", "0038_auto_20230512_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="companies",
            field=models.ManyToManyField(
                related_name="user_notifications", to="companies.Company"
            ),
        ),
    ]
