# Generated by Django 2.2.28 on 2023-08-09 14:17

from typing import Iterable

from django.contrib.gis.db.backends.postgis.schema import PostGISSchemaEditor
from django.db import migrations
from django.db.migrations.state import StateApps
from tqdm import tqdm

from apps.users.models import UserNotification as UserNotificationType


def get_user_notifications(
    apps: StateApps, schema_editor: PostGISSchemaEditor
) -> Iterable[UserNotificationType]:
    """
    Helper to fetch all UserNotification instances that are going to be used
    on these migrations.

    Args:
        apps (StateApps): Django app manager
        schema_editor (PostGISSchemaEditor): Database schema manager

    Returns:
        Iterable[UserNotificationType]: All the fetched UserNotification instances
    """

    db_alias = schema_editor.connection.alias
    UserNotification = apps.get_model("users", "UserNotification")
    user_notifications: Iterable[UserNotificationType] = UserNotification.objects.using(
        db_alias
    ).all()

    return user_notifications


def fill_companies_field(apps: StateApps, schema_editor: PostGISSchemaEditor):
    """
    Add the `UserNotification.company` to the M2M field `UserNotification.companies`.

    Args:
        apps (StateApps): Django app manager
        schema_editor (PostGISSchemaEditor): Database schema manager
    """

    user_notifications = get_user_notifications(apps, schema_editor)

    for user_notification in tqdm(user_notifications):
        company = user_notification.company
        user_notification.companies.add(company)


def reverse_fill_companies_field(apps: StateApps, schema_editor: PostGISSchemaEditor):
    """
    Reverse the fill_companies_field migration by clearing the
    `UserNotification.companies` fields.

    Args:
        apps (StateApps): Django app manager
        schema_editor (PostGISSchemaEditor): Database schema manager
    """

    user_notifications = get_user_notifications(apps, schema_editor)

    for user_notification in tqdm(user_notifications):
        user_notification.companies.clear()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_usernotification_companies"),
    ]

    operations = [
        migrations.RunPython(
            fill_companies_field, reverse_code=reverse_fill_companies_field
        )
    ]
