# Generated by Django 2.2.28 on 2023-08-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_auto_20230809_1201"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usernotification",
            options={"ordering": ["notification"]},
        ),
        migrations.RemoveField(
            model_name="historicalusernotification",
            name="company",
        ),
        migrations.AlterUniqueTogether(
            name="usernotification",
            unique_together={
                ("user", "notification", "notification_type", "time_interval")
            },
        ),
        migrations.RemoveField(
            model_name="usernotification",
            name="company",
        ),
    ]
