# Generated by Django 2.2.28 on 2023-08-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_auto_20230809_1153"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalusernotification",
            name="in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="in_progress",
            field=models.BooleanField(default=False),
        ),
    ]
