# Generated by Django 2.2.28 on 2024-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_auto_20230824_0841"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalUserNotification",
        ),
    ]
