# Generated by Django 3.2.25 on 2025-05-23 13:35
import logging

from django.db import migrations, models


def clean_orphaned_device_relations(apps, schema_editor):
    """
    Remove relacionamentos órfãos na tabela users_user_push_devices
    que referenciam devices não existentes em notifications_device.
    """
    with schema_editor.connection.cursor() as cursor:
        # Conta quantos relacionamentos órfãos existem
        cursor.execute(
            """
            SELECT COUNT(*) 
            FROM users_user_push_devices uupd
            WHERE NOT EXISTS (
                SELECT 1 FROM notifications_device nd 
                WHERE nd.id = uupd.device_id
            );
        """
        )
        orphaned_count = cursor.fetchone()[0]
        logging.info(
            f"Encontrados {orphaned_count} relacionamentos órfãos para remover"
        )

        if orphaned_count > 0:
            # Remove relacionamentos órfãos
            cursor.execute(
                """
                DELETE FROM users_user_push_devices 
                WHERE device_id NOT IN (
                    SELECT id FROM notifications_device
                );
            """
            )
            logging.info(f"Removidos {orphaned_count} relacionamentos órfãos")


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_copy_device_data"),
        ("users", "0045_auto_20250227_1243"),
    ]

    operations = [
        migrations.RunPython(
            clean_orphaned_device_relations, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="user",
            name="push_devices",
            field=models.ManyToManyField(
                related_name="device_users", to="notifications.Device"
            ),
        ),
    ]
