# Generated by Django 3.2.25 on 2025-05-23 14:27

from django.db import migrations


def copy_push_relations(apps, schema_editor):
    User = apps.get_model("users", "User")
    NewDevice = apps.get_model("notifications", "Device")

    old_to_new = {d.id: d for d in NewDevice.objects.all()}

    for user in User.objects.all():
        for old_device in user.push_devices.through.objects.filter(user_id=user.uuid):
            new_device = old_to_new.get(old_device.device_id)
            if new_device:
                user.push_devices.add(new_device)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0046_alter_user_push_devices"),
    ]

    operations = [
        migrations.RunPython(
            copy_push_relations, reverse_code=migrations.RunPython.noop
        ),
    ]
