# Generated by Django 3.2.25 on 2025-09-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0047_copy_user_push_devices"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="legacy_uuid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="legacy_uuid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
