# Generated by Django 3.2.25 on 2025-08-06 21:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0073_auto_20250516_1459"),
        ("users", "0047_copy_user_push_devices"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSignature",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("md5", models.TextField(blank=True)),
                (
                    "upload",
                    models.FileField(
                        storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_signatures",
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "company")},
            },
        ),
    ]
