# Generated by Django 3.2.25 on 2025-10-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_auto_20250923_1934"),
        ("users", "0048_usersignature"),
    ]

    operations = []
