# Generated by Django 3.2.25 on 2025-05-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scarface", "0007_delete_useless_models"),
        ("zas", "0010_alter_zasarea_push_devices"),
        ("users", "0047_copy_user_push_devices"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Device",
        ),
        migrations.DeleteModel(
            name="PushMessage",
        ),
    ]
