SURVEY_IN_PROGRESS = "SURVEY_IN_PROGRESS"
SURVEY_DONE = "SURVEY_DONE"
SURVEY_APPROVED = "SURVEY_APPROVED"


APPROVAL_STATUS_CHOICES = [
    (SURVEY_IN_PROGRESS, SURVEY_IN_PROGRESS),
    (SURVEY_DONE, SURVEY_DONE),
    (SURVEY_APPROVED, SURVEY_APPROVED),
]
