# Generated by Django 2.1.1 on 2018-09-21 13:17

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_userincompany_permissions"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccurrenceRecord",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(blank=True, max_length=50)),
                ("occurrence_kind", models.CharField(blank=True, max_length=60)),
                ("uf_code", models.IntegerField(blank=True, null=True)),
                ("place_on_dam", models.CharField(blank=True, max_length=50)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("distance_from_dam", models.IntegerField(default=0)),
                ("origin", models.CharField(blank=True, max_length=50)),
                ("origin_media", models.CharField(blank=True, max_length=50)),
                (
                    "informer",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "form_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.City",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.Company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OccurrenceType",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("occurrence_kind", models.CharField(blank=True, max_length=60)),
                (
                    "form_fields",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.Company",
                    ),
                ),
            ],
        ),
    ]
