# Generated by Django 2.1.1 on 2018-09-21 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0001_initial"),
        ("occurrence_records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencerecord",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.Location",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="occurrence_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="occurrence_records.OccurrenceType",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="river",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.River",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="occurrencetype",
            unique_together={("name", "company")},
        ),
    ]
