# Generated by Django 2.1.1 on 2018-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0002_auto_20180921_1017"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencerecord",
            name="editable",
            field=models.BooleanField(default=True),
        ),
    ]
