# Generated by Django 2.1.2 on 2018-11-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0003_occurrencerecord_editable"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencerecord",
            name="reviews",
            field=models.IntegerField(default=0),
        ),
    ]
