# Generated by Django 2.1.2 on 2019-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0004_occurrencerecord_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencerecord",
            name="number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="occurrence_kind",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="origin",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="origin_media",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="place_on_dam",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="occurrencetype",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="occurrencetype",
            name="occurrence_kind",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
