# Generated by Django 2.1.2 on 2019-02-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_merge_20190209_2010"),
        ("occurrence_records", "0005_auto_20190108_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencetype",
            name="companies",
            field=models.ManyToManyField(
                related_name="occurrence_type_companies", to="companies.Company"
            ),
        ),
        migrations.AlterField(
            model_name="occurrencetype",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrence_type_company",
                to="companies.Company",
            ),
        ),
    ]
