# Generated by Django 2.1.2 on 2019-02-12 16:58

from django.db import migrations, models


def make_many_companies(apps, schema_editor):
    OccurrenceType = apps.get_model("occurrence_records", "OccurrenceType")
    for occurrencetype in OccurrenceType.objects.all():
        occurrencetype.companies.add(occurrencetype.company)


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0006_auto_20190212_1456"),
    ]

    operations = [migrations.RunPython(make_many_companies)]
