# Generated by Django 2.1.2 on 2019-02-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0007_auto_20190212_1458"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="occurrencetype",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="occurrencetype",
            name="company",
        ),
    ]
