# Generated by Django 2.1.2 on 2019-02-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0008_auto_20190212_1517"),
    ]

    operations = [
        migrations.RenameField(
            model_name="occurrencetype",
            old_name="companies",
            new_name="company",
        ),
    ]
