# Generated by Django 2.1.2 on 2019-02-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0009_auto_20190212_1546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencerecord",
            name="occurrence_kind",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
