# Generated by Django 2.1.2 on 2019-02-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "occurrence_records",
            "0011_historicaloccurrencerecord_historicaloccurrencetype",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaloccurrencerecord",
            name="occurrence_kind",
        ),
        migrations.RemoveField(
            model_name="occurrencerecord",
            name="occurrence_kind",
        ),
    ]
