# Generated by Django 2.1.2 on 2019-02-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_historicalcompany_historicalfirm_historicaluserincompany"),
        ("occurrence_records", "0012_auto_20190218_1448"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencetype",
            name="firms",
            field=models.ManyToManyField(
                related_name="occurrence_type_firms", to="companies.Firm"
            ),
        ),
    ]
