# Generated by Django 2.1.2 on 2019-04-03 17:58

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import helpers.fields


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_auto_20190312_1938"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("occurrence_records", "0013_occurrencetype_firms"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalOccurrenceTypeSpecs",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "color",
                    helpers.fields.ColorField(default="#FF0000", max_length=18),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical occurrence type specs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OccurrenceTypeSpecs",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "color",
                    helpers.fields.ColorField(default="#FF0000", max_length=18),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_specs",
                        to="companies.Company",
                    ),
                ),
                (
                    "occurrence_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrencetype_specs",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="companies",
            field=models.ManyToManyField(
                related_name="occurrence_type_companies_new",
                through="occurrence_records.OccurrenceTypeSpecs",
                to="companies.Company",
            ),
        ),
    ]
