# Generated by Django 2.1.2 on 2019-04-03 17:59

from __future__ import unicode_literals

from django.db import migrations, models


def put_through_in_m2m(apps, schema_editor):
    OccurrenceTypeSpecs = apps.get_model("occurrence_records", "OccurrenceTypeSpecs")
    OccurrenceType = apps.get_model("occurrence_records", "OccurrenceType")

    for occurrencetype in OccurrenceType.objects.all():
        for company in occurrencetype.company.all():
            OccurrenceTypeSpecs.objects.create(
                occurrence_type=occurrencetype, company=company, color="#FF0000"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0014_auto_20190403_1458"),
    ]

    operations = [
        migrations.RunPython(put_through_in_m2m),
    ]
