# Generated by Django 2.1.2 on 2019-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0015_auto_20190403_1459"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrencetype",
            name="company",
        ),
        migrations.AlterField(
            model_name="occurrencetype",
            name="companies",
            field=models.ManyToManyField(
                related_name="occurrence_type_companies",
                through="occurrence_records.OccurrenceTypeSpecs",
                to="companies.Company",
            ),
        ),
    ]
