# Generated by Django 2.1.2 on 2019-04-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0016_auto_20190403_1512"),
    ]

    operations = [
        migrations.RenameField(
            model_name="occurrencetype",
            old_name="companies",
            new_name="company",
        ),
    ]
