# Generated by Django 2.1.2 on 2019-05-10 16:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0017_auto_20190403_1521")]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="goal_formula",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="goal_formula",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
    ]
