# Generated by Django 2.1.2 on 2019-05-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0021_auto_20190508_2116"),
        ("occurrence_records", "0018_auto_20190510_1340"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="occurrencetypespecs",
            unique_together={("company", "occurrence_type")},
        )
    ]
