# Generated by Django 2.1.2 on 2019-07-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0020_file_historicalfile")]

    operations = [
        migrations.RemoveField(model_name="file", name="content_type"),
        migrations.RemoveField(model_name="file", name="created_by"),
        migrations.RemoveField(model_name="historicalfile", name="content_type"),
        migrations.RemoveField(model_name="historicalfile", name="created_by"),
        migrations.RemoveField(model_name="historicalfile", name="history_user"),
        migrations.DeleteModel(name="File"),
        migrations.DeleteModel(name="HistoricalFile"),
    ]
