# Generated by Django 2.1.2 on 2019-07-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0047_auto_20190625_1201"),
        ("companies", "0022_auto_20190514_2005"),
        ("occurrence_records", "0021_auto_20190717_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.Firm",
            ),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="parent_action",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.ServiceOrderAction",
            ),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="service_orders",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.ServiceOrder",
            ),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firm_records",
                to="companies.Firm",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="parent_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_records",
                to="service_orders.ServiceOrderAction",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="service_orders",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrence_records",
                to="service_orders.ServiceOrder",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_records",
                to="service_orders.ServiceOrderActionStatus",
            ),
        ),
    ]
