# Generated by Django 2.1.2 on 2019-07-22 18:49
from __future__ import unicode_literals

from django.db import migrations


def populate_firm_and_service_order_and_status(apps, schema_editor):
    """
    Populate service_order field in OccurrenceRecord
    using old one-to-one field in ServiceOrder

    Populate firm field in OccurrenceRecord
    using the firm from first procedure of the first action

    This also will populate status field in OccurrenceRecord
    using the last status of the first action
    """
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    ServiceOrderAction = apps.get_model("service_orders", "ServiceOrderAction")
    db_alias = schema_editor.connection.alias
    for record in OccurrenceRecord.objects.using(db_alias).all():
        try:
            first_action = (
                ServiceOrderAction.objects.using(db_alias)
                .filter(service_order__occurrence_record=record, first_action=True)
                .first()
            )
        except Exception:
            continue

        record.service_orders = first_action.service_order
        first_procedure = first_action.procedures.all().order_by("created_at").first()

        if first_procedure:
            record.firm = first_procedure.firm
            record.status = first_procedure.service_order_action_status
        else:
            print("Not filling Firm in OccurrenceRecord {}".format(record.number))
        record.save()


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0022_auto_20190719_1451")]

    operations = [
        migrations.RunPython(
            populate_firm_and_service_order_and_status,
            reverse_code=migrations.RunPython.noop,
        )
    ]
