# Generated by Django 2.1.2 on 2019-07-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0023_populate_firm_os_status"),
        ("service_orders", "0048_auto_20190722_1618"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaloccurrencerecord",
            old_name="service_orders",
            new_name="service_order",
        ),
        migrations.RenameField(
            model_name="occurrencerecord",
            old_name="service_orders",
            new_name="service_order",
        ),
    ]
