# Generated by Django 2.1.2 on 2019-08-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0025_auto_20190722_1620")]

    operations = [
        migrations.AlterField(
            model_name="historicaloccurrencerecord",
            name="history_change_reason",
            field=models.TextField(null=True),
        )
    ]
