# Generated by Django 2.1.2 on 2019-07-19 17:51
from __future__ import unicode_literals

import re
import uuid
from datetime import datetime

from django.db import migrations


def snake_case(name):
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def create_histories(apps, schema_editor):
    """
    Create history entries for each OccurrenceRecord,
    each history will have the status of each procedure of first action
    """
    HistoricalOccurrenceRecord = apps.get_model(
        "occurrence_records", "HistoricalOccurrenceRecord"
    )
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    OccurrenceType = apps.get_model("occurrence_records", "OccurrenceType")
    ServiceOrderAction = apps.get_model("service_orders", "ServiceOrderAction")
    ServiceOrderActionStatus = apps.get_model(
        "service_orders", "ServiceOrderActionStatus"
    )
    Location = apps.get_model("locations", "Location")
    City = apps.get_model("locations", "City")
    River = apps.get_model("locations", "River")
    Firm = apps.get_model("companies", "Firm")
    User = apps.get_model("users", "User")
    db_alias = schema_editor.connection.alias

    HistoricalOccurrenceRecord.objects.using(db_alias).delete()

    for record in OccurrenceRecord.objects.using(db_alias).all():
        try:
            first_action = ServiceOrderAction.objects.using(db_alias).get(
                service_order__occurrence_record=record, first_action=True
            )
        except:
            print("Skipping history creation for {}".format(record.number))
            continue

        procs = (
            first_action.procedures.exclude(form_data__type="OccurrenceRecordCreated")
            .exclude(form_data__type="ServiceOrderActionCreated")
            .order_by("-created_at")
        )

        hists = [
            (
                procs[index - 1].form_data["data"]
                if index != 0 and procs[index - 1].form_data
                else None,
                HistoricalOccurrenceRecord(
                    **{
                        field.attname: getattr(record, field.attname)
                        for field in record._meta.fields
                        if field.attname
                        not in [
                            "history_date",
                            "history_user",
                            "history_change_reason",
                            "history_type",
                            "updated_at",
                            "firm",
                            "status",
                        ]
                    },
                    history_date=getattr(proc, "created_at", datetime.now()),
                    history_user=getattr(proc, "created_by", None),
                    history_change_reason=proc.to_do,
                    history_type="~",
                    updated_at=getattr(proc, "created_at", datetime.now()),
                    firm=Firm.objects.using(db_alias).get(uuid=proc.firm.uuid)
                    if proc.firm
                    else None,
                    status=ServiceOrderActionStatus.objects.using(db_alias).get(
                        uuid=proc.service_order_action_status.uuid
                    )
                    if proc.service_order_action_status
                    else None,
                    responsible=User.objects.using(db_alias).get(
                        uuid=proc.responsible.uuid
                    )
                    if proc.responsible
                    else None,
                ),
            )
            for index, proc in enumerate(procs)
        ]

        try:
            proc = first_action.procedures.get(
                form_data__type="OccurrenceRecordCreated"
            )
        except:
            continue

        hists.append(
            (
                procs.last().form_data["data"]
                if procs.last() and procs.last().form_data
                else None,
                HistoricalOccurrenceRecord(
                    **{
                        field.attname: getattr(
                            hists[-1][1] if hists else record, field.attname
                        )
                        for field in record._meta.fields
                        if field.attname
                        not in [
                            "history_date",
                            "history_user",
                            "history_change_reason",
                            "history_type",
                            "updated_at",
                            "firm",
                            "status",
                        ]
                    },
                    history_date=getattr(proc, "created_at", datetime.now()),
                    history_user=getattr(proc, "created_by", None),
                    history_change_reason=getattr(proc, "to_do", ""),
                    history_type="+",
                    updated_at=getattr(proc, "created_at", datetime.now()),
                    firm=Firm.objects.using(db_alias).get(uuid=proc.firm.uuid)
                    if proc.firm
                    else None,
                    status=ServiceOrderActionStatus.objects.using(db_alias).get(
                        uuid=proc.service_order_action_status.uuid
                    )
                    if proc.service_order_action_status
                    else None,
                    responsible=User.objects.using(db_alias).get(
                        uuid=proc.responsible.uuid
                    )
                    if proc.responsible
                    else None,
                ),
            )
        )

        for index, hist in enumerate(hists):
            if hist[0]:
                for field in hist[0]:
                    if field["field_name"] == "location":
                        value = Location.objects.using(db_alias).get(
                            uuid=field["old_value"]
                        )
                    elif field["field_name"] == "city":
                        value = City.objects.using(db_alias).get(
                            uuid=field["old_value"]
                        )
                    elif field["field_name"] == "river":
                        value = River.objects.using(db_alias).get(
                            uuid=field["old_value"]
                        )
                    elif field["field_name"] == "occurrenceType":
                        value = OccurrenceType.objects.using(db_alias).get(
                            uuid=field["old_value"]
                        )
                    elif field["field_name"] == "point":
                        if isinstance(value, str):
                            value = None
                        else:
                            value = field["old_value"]
                    else:
                        if field["old_value"] == "true":
                            print("setting {} to True".format(field["field_name"]))
                            value = True
                        elif field["old_value"] == "false":
                            print("setting {} to False".format(field["field_name"]))
                            value = False
                        else:
                            value = field["old_value"]

                    for a in range(index, len(hists)):
                        setattr(hists[a][1], snake_case(field["field_name"]), value)

        HistoricalOccurrenceRecord.objects.using(db_alias).bulk_create(
            [a[1] for a in hists]
        )

        # I have no idea why, but I had to set these again, otherwise
        # they don't get saved into the history objects
        for hist in hists:
            object = HistoricalOccurrenceRecord.objects.using(db_alias).get(
                history_id=hist[1].history_id
            )
            object.status = hist[1].status
            object.firm = hist[1].firm
            object.responsible = hist[1].responsible
            object.save()

        # Remove service_order relationship if it hasn't been opened yet
        # In this case, those service_orders will be deleted later
        for hist in (
            HistoricalOccurrenceRecord.objects.using(db_alias)
            .all()
            .select_related("service_order")
        ):
            if hist.service_order and hist.service_order.number == "":
                hist.service_order = None
                hist.save()


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0026_auto_20190829_1636")]

    operations = [
        migrations.RunPython(create_histories, reverse_code=migrations.RunPython.noop)
    ]
