# Generated by Django 2.1.2 on 2019-07-19 17:51
from __future__ import unicode_literals

import re
import uuid
from datetime import datetime

from django.db import migrations


def copy_additional_documents(apps, schema_editor):
    """
    Create an OccurrenceRecord for each existing AdditionalDocument
    """
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    HistoricalOccurrenceRecord = apps.get_model(
        "occurrence_records", "HistoricalOccurrenceRecord"
    )
    AdditionalDocument = apps.get_model("service_orders", "AdditionalDocument")
    ServiceOrderActionStatusSpecs = apps.get_model(
        "service_orders", "ServiceOrderActionStatusSpecs"
    )

    db_alias = schema_editor.connection.alias

    first_status = ()

    documents = AdditionalDocument.objects.using(db_alias).all()

    records = [
        OccurrenceRecord(
            datetime=document.created_at,
            number=document.number,
            company=document.action.service_order.company,
            editable=True,
            created_by=document.created_by,
            occurrence_type=document.occurrence_type,
            form_data=document.form_data or {},
            created_at=document.created_at,
            updated_at=document.updated_at,
            reviews=0,
            status=ServiceOrderActionStatusSpecs.objects.using(db_alias)
            .get(company=document.action.service_order.company, order=1)
            .status,
            service_order=document.action.service_order,
            parent_action=document.action,
            firm=document.created_by.user_firms.first(),
            responsible=document.created_by,
        )
        for document in documents
    ]

    OccurrenceRecord.objects.using(db_alias).bulk_create(records)

    historical_records = [
        HistoricalOccurrenceRecord(
            **{
                field.attname: getattr(record, field.attname)
                for field in record._meta.fields
            },
            history_date=getattr(record, "created_at", datetime.now()),
            history_user=getattr(record, "created_by", None),
            history_change_reason="",
            history_type="+",
        )
        for record in records
    ]

    HistoricalOccurrenceRecord.objects.using(db_alias).bulk_create(historical_records)


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0027_occurrence_record_history")]

    operations = [
        migrations.RunPython(
            copy_additional_documents, reverse_code=migrations.RunPython.noop
        )
    ]
