# Generated by Django 2.1.2 on 2019-08-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0002_auto_20190809_1341"),
        ("occurrence_records", "0028_copy_additional_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="monitoring_point",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="monitorings.MonitoringPoint",
            ),
        ),
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="monitoring_plan",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="monitorings.MonitoringPlan",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="monitoring_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="points_records",
                to="monitorings.MonitoringPoint",
            ),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="monitoring_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrence_types_plan",
                to="monitorings.MonitoringPlan",
            ),
        ),
    ]
