# Generated by Django 2.1.2 on 2019-08-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0029_auto_20190809_1341")]

    operations = [
        migrations.AlterField(
            model_name="historicaloccurrencerecord",
            name="distance_from_dam",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="distance_from_dam",
            field=models.FloatField(default=0),
        ),
    ]
