# Generated by Django 2.1.2 on 2019-09-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0031_auto_20190826_2018")]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                default="4b3e18b8-304c-433b-905d-12aa98b53ba5",
                on_delete=models.deletion.DO_NOTHING,
                related_name="historicaloccurrencerecord",
                to="occurrence_records.OccurrenceRecord",
            ),
            preserve_default=False,
        )
    ]
