# Generated by Django 2.1.2 on 2019-09-13 13:23

from django.db import migrations


def copy_value_to_related_name(apps, schema_editor):
    HistoricalOccurrenceRecord = apps.get_model(
        "occurrence_records", "HistoricalOccurrenceRecord"
    )
    db_alias = schema_editor.connection.alias
    from django.db.models import F

    HistoricalOccurrenceRecord.objects.using(db_alias).all().update(
        history_relation=F("uuid")
    )


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0032_auto_20190913_1023")]

    operations = [
        migrations.RunPython(copy_value_to_related_name, migrations.RunPython.noop)
    ]
