# Generated by Django 2.1.2 on 2019-10-03 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0022_auto_20190514_2005"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "occurrence_records",
            "0033_historicaloccurrencerecord_history_relation",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencerecord",
            name="watcher_firms",
            field=models.ManyToManyField(
                blank=True,
                related_name="watcher_firms_records",
                to="companies.Firm",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="watcher_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="watcher_users_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
