# Generated by Django 2.1.2 on 2019-10-23 00:29

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0034_auto_20191003_1348"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="properties",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="properties",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list
            ),
        ),
    ]
