# Generated by Django 2.1.2 on 2019-09-13 13:23

from django.contrib.gis.geos import GeometryCollection
from django.db import migrations


def copy_point_to_geometry(apps, schema_editor):
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    db_alias = schema_editor.connection.alias

    occurrence_records = OccurrenceRecord.objects.using(db_alias).all()
    for record in occurrence_records:
        if record.point:
            record.geometry = GeometryCollection(record.point)
            record.properties = [{}]
            record.save()


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0035_auto_20191022_2129")]

    operations = [
        migrations.RunPython(copy_point_to_geometry, migrations.RunPython.noop)
    ]
