# Generated by Django 2.1.2 on 2019-11-05 16:08

from django.db import migrations


def create_watcher_models(apps, schema_editor):
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    OccurrenceRecordWatcher = apps.get_model(
        "occurrence_records", "OccurrenceRecordWatcher"
    )
    db_alias = schema_editor.connection.alias

    occurrence_records = OccurrenceRecord.objects.using(db_alias).all()
    for record in occurrence_records:
        if record.watcher_users.exists():
            for user in record.watcher_users.all():
                OccurrenceRecordWatcher.objects.create(
                    occurrence_record=record, user=user, created_by=user
                )
        if record.watcher_firms.exists():
            for firm in record.watcher_firms.all():
                OccurrenceRecordWatcher.objects.create(
                    occurrence_record=record, firm=firm
                )


class Migration(migrations.Migration):

    dependencies = [
        (
            "occurrence_records",
            "0037_historicaloccurrencerecordwatcher_occurrencerecordwatcher",
        )
    ]

    operations = [
        migrations.RunPython(create_watcher_models, migrations.RunPython.noop)
    ]
