# Generated by Django 2.1.2 on 2019-11-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0038_auto_20191105_1308")]

    operations = [
        migrations.RemoveField(model_name="occurrencerecord", name="watcher_firms"),
        migrations.RemoveField(model_name="occurrencerecord", name="watcher_users"),
    ]
