# Generated by Django 2.1.2 on 2019-11-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0039_auto_20191105_1311")]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecordwatcher",
            name="status_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="occurrencerecordwatcher",
            name="status_email",
            field=models.BooleanField(default=True),
        ),
    ]
