# Generated by Django 2.1.2 on 2019-12-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0004_auto_20191118_1921"),
        ("occurrence_records", "0040_auto_20191107_1235"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="approval_flows.ApprovalStep",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_records",
                to="approval_flows.ApprovalStep",
            ),
        ),
    ]
