# Generated by Django 2.1.2 on 2020-01-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0041_auto_20191204_1608"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="other_reference",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="other_reference",
            field=models.TextField(blank=True),
        ),
    ]
