# Generated by Django 2.1.2 on 2020-01-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0042_auto_20200122_2018"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="deadline",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="deadline",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
