# Generated by Django 2.1.2 on 2020-01-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0043_auto_20200123_2207")]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="keywords",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="keywords",
            field=models.TextField(default="", null=True),
        ),
    ]
