# Generated by Django 2.1.2 on 2020-01-30 19:08

from django.db import migrations
from django_bulk_update.helper import bulk_update

from helpers.apps.record_filter import create_keywords


def fill_keywords(apps, schema_editor):
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    db_alias = schema_editor.connection.alias

    objs = []
    records = OccurrenceRecord.objects.using(db_alias).all()
    for record in records:
        record.keywords = create_keywords(record.form_data, record.occurrence_type)
        objs.append(record)
    bulk_update(objs)


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0044_auto_20200130_1608")]

    operations = [migrations.RunPython(fill_keywords, migrations.RunPython.noop)]
