# Generated by Django 2.1.2 on 2020-03-18 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0007_auto_20200311_0918"),
        ("occurrence_records", "0045_auto_20200130_1608"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="active_tile_layer",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="maps.TileLayer",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="active_shape_files",
            field=models.ManyToManyField(
                blank=True,
                related_name="shape_file_records",
                to="maps.ShapeFile",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="active_tile_layer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tyle_layer_records",
                to="maps.TileLayer",
            ),
        ),
    ]
