# Generated by Django 2.1.2 on 2020-06-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0046_auto_20200318_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="geometry_hash",
            field=models.TextField(blank=True, null=True),
        ),
    ]
