# Generated by Django 2.1.2 on 2020-04-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0046_auto_20200318_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="last_version",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="occurrence_records.OccurrenceType",
            ),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="last_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actual_version",
                to="occurrence_records.OccurrenceType",
            ),
        ),
    ]
