# Generated by Django 2.1.2 on 2020-06-16 16:04
import hashlib

from django.db import migrations
from tqdm import tqdm


def add_geometry_changes_to_history(apps, schema_editor):
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    HistoricalOccurrenceRecord = apps.get_model(
        "occurrence_records", "HistoricalOccurrenceRecord"
    )
    db_alias = schema_editor.connection.alias

    occurrence_records = OccurrenceRecord.objects.using(db_alias).all()
    for record in tqdm(occurrence_records):
        history = HistoricalOccurrenceRecord.objects.filter(uuid=record.uuid).order_by(
            "-history_date"
        )
        for hist_record in history:
            geometry_hash_str = hist_record.geometry.__str__()
            hist_record.geometry_hash = hashlib.md5(
                geometry_hash_str.encode()
            ).hexdigest()
            hist_record.geometry = None
            hist_record.save()


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0047_historicaloccurrencerecord_geometry_hash"),
    ]

    operations = [
        migrations.RunPython(add_geometry_changes_to_history, migrations.RunPython.noop)
    ]
