# Generated by Django 2.1.2 on 2020-04-12 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0047_auto_20200407_1318")]

    operations = [
        migrations.RenameField(
            model_name="historicaloccurrencetype",
            old_name="last_version",
            new_name="previous_version",
        ),
        migrations.RemoveField(model_name="occurrencetype", name="last_version"),
        migrations.AddField(
            model_name="occurrencetype",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_version",
                to="occurrence_records.OccurrenceType",
            ),
        ),
    ]
