# Generated by Django 2.1.2 on 2020-05-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0048_auto_20200412_1837"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencerecord",
            name="occurrence_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="type_records",
                to="occurrence_records.OccurrenceType",
            ),
        ),
    ]
