# Generated by Django 2.1.2 on 2020-06-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0049_auto_20200508_0807"),
        ("occurrence_records", "0048_auto_20200616_1304"),
    ]

    operations = []
