# Generated by Django 2.1.2 on 2020-09-13 17:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0050_merge_20200617_1713"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="arcgis_ids",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="arcgis_ids",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
