# Generated by Django 2.1.2 on 2020-10-30 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0051_auto_20200913_1436"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencerecord",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.City",
            ),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.Location",
            ),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="river",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.River",
            ),
        ),
    ]
