# Generated by Django 2.1.2 on 2021-02-19 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0052_auto_20201030_0924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencerecord",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
