# Generated by Django 2.1.2 on 2021-03-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0021_auto_20210311_1645"),
        ("occurrence_records", "0053_auto_20210219_0733"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencerecord",
            name="search_tags",
            field=models.ManyToManyField(
                blank=True, related_name="occurrence_records", to="templates.SearchTag"
            ),
        ),
    ]
