# Generated by Django 2.1.2 on 2021-04-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0054_occurrencerecord_search_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="search_tag_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="search_tag_description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
