# Generated by Django 2.1.2 on 2021-05-07 10:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0055_auto_20210409_0928"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="involved_parts",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="involved_parts",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
    ]
