# Generated by Django 2.1.2 on 2021-05-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_orders", "0092_auto_20210219_1548"),
        ("occurrence_records", "0056_auto_20210507_0719"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencerecord",
            name="service_orders",
            field=models.ManyToManyField(
                blank=True,
                related_name="so_records",
                to="service_orders.ServiceOrder",
            ),
        ),
    ]
