# Generated by Django 2.1.2 on 2021-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0056_auto_20210507_0719"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="is_oae",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="is_oae",
            field=models.BooleanField(default=False),
        ),
    ]
