# Generated by Django 2.1.2 on 2021-05-26 12:52
from django.db import migrations
from tqdm import tqdm


def fill_service_orders_field(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    records = OccurrenceRecord.objects.using(db_alias).filter(
        service_order__isnull=False
    )

    for record in tqdm(records):
        if record.service_order is not None:
            record.service_orders.add(record.service_order)


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0057_occurrencerecord_service_orders"),
    ]

    operations = [
        migrations.RunPython(
            fill_service_orders_field, reverse_code=migrations.RunPython.noop
        )
    ]
