# Generated by Django 2.1.2 on 2021-05-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0058_auto_20210526_0952"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaloccurrencerecord",
            name="service_order",
        ),
        migrations.RemoveField(
            model_name="occurrencerecord",
            name="service_order",
        ),
    ]
