# Generated by Django 2.1.2 on 2021-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0059_auto_20210526_0959"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
