# Generated by Django 2.1.2 on 2021-05-28 12:45
from functools import reduce
from operator import __or__ as OR

from django.db import migrations
from django.db.models import Q
from django_bulk_update.helper import bulk_update
from tqdm import tqdm


def fill_is_approved_field(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    ApprovalStep = apps.get_model("approval_flows", "ApprovalStep")
    records = (
        OccurrenceRecord.objects.using(db_alias).all().select_related("approval_step")
    )

    not_approved_names = [
        "registro indeferido",
        "registro em elaboração",
        "necessita revisão",
        "aguardando homologação",
    ]

    not_approved_filters = [Q(name__icontains=a) for a in not_approved_names]

    not_approved_steps = ApprovalStep.objects.filter(reduce(OR, not_approved_filters))

    updated_records = []
    for record in tqdm(records):
        if record.approval_step not in not_approved_steps:
            record.is_approved = True
            updated_records.append(record)

    bulk_update(updated_records, batch_size=2000, update_fields=["is_approved"])


def reset_is_approved_field(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    records = OccurrenceRecord.objects.using(db_alias).all()

    updated_records = []
    for record in tqdm(records):
        record.is_approved = False
        updated_records.append(record)

    bulk_update(updated_records, batch_size=2000, update_fields=["is_approved"])


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0060_auto_20210527_0920"),
    ]

    operations = [
        migrations.RunPython(
            fill_is_approved_field, reverse_code=reset_is_approved_field
        )
    ]
