# Generated by Django 2.2.23 on 2021-06-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0061_auto_20210528_0945"),
        ("occurrence_records", "0057_occurrencetype_is_oae"),
    ]

    operations = []
