# Generated by Django 2.2.23 on 2021-06-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0062_merge_20210607_0728"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="territorial_administration",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="territorial_administration",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
