# Generated by Django 2.2.23 on 2021-09-14 17:39

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0032_auto_20210707_0733"),
        ("occurrence_records", "0063_auto_20210610_2157"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="form_metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="operational_control",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="monitorings.OperationalControl",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="form_metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="operational_control",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="op_control_records",
                to="monitorings.OperationalControl",
            ),
        ),
    ]
