# Generated by Django 2.2.23 on 2021-09-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0064_auto_20210914_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="involved_parts_keywords",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencetypespecs",
            name="has_no_flow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaloccurrencetypespecs",
            name="is_not_listed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaloccurrencetypespecs",
            name="is_not_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="involved_parts_keywords",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="occurrencetypespecs",
            name="has_no_flow",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="occurrencetypespecs",
            name="is_not_listed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="occurrencetypespecs",
            name="is_not_notified",
            field=models.BooleanField(default=False),
        ),
    ]
