# Generated by Django 2.2.23 on 2021-09-24 18:30

from django.db import migrations
from django_bulk_update.helper import bulk_update
from tqdm import tqdm

from helpers.apps.record_filter import create_involved_parts_keywords


def fill_involved_parts_keywords(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")

    objs = []
    records = OccurrenceRecord.objects.using(db_alias).exclude(involved_parts=[])
    for record in tqdm(records):
        record.involved_parts_keywords = create_involved_parts_keywords(
            record.company, record.involved_parts
        )
        objs.append(record)
    bulk_update(objs, batch_size=2000, update_fields=["involved_parts_keywords"])


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0065_auto_20210924_1336"),
    ]

    operations = [
        migrations.RunPython(
            fill_involved_parts_keywords, reverse_code=migrations.RunPython.noop
        )
    ]
