# Generated by Django 2.2.23 on 2021-09-24 19:10
import copy

from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from tqdm import tqdm

from apps.service_orders.const import status_types


def create_occurrence_records(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    # Required models
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    SearchTag = apps.get_model("templates", "SearchTag")
    OperationalControlRecord = apps.get_model("monitorings", "OperationalControlRecord")
    Procedure = apps.get_model("service_orders", "Procedure")
    ServiceOrderActionStatusSpecs = apps.get_model(
        "service_orders", "ServiceOrderActionStatusSpecs"
    )
    MaterialUsage = apps.get_model("monitorings", "MaterialUsage")
    File = apps.get_model("files", "File")
    # Required history models
    HistoricalOccurrenceRecord = apps.get_model(
        "occurrence_records", "HistoricalOccurrenceRecord"
    )
    HistoricalOperationalControlRecord = apps.get_model(
        "monitorings", "HistoricalOperationalControlRecord"
    )
    # Required ContentTypes
    try:
        occ_record_content_type = ContentType.objects.get(
            app_label="occurrence_records", model="occurrencerecord"
        )
        op_record_content_type = ContentType.objects.get(
            app_label="monitorings", model="operationalcontrolrecord"
        )
    except Exception:
        print("Not running migration from OperationalControlRecord to OccurrenceRecord")
        return

    # Get all OperationalControlRecords and iterate over them
    operational_records = OperationalControlRecord.objects.using(db_alias).all()
    for op_record in tqdm(operational_records):
        # OccurrenceRecord
        # copy operational record
        obj_dict = copy.deepcopy(op_record.__dict__)
        if "_state" in obj_dict:
            del obj_dict["_state"]
        # add company
        company_id = op_record.operational_control.firm.company_id
        obj_dict["company_id"] = company_id
        obj_dict["editable"] = True
        obj_dict["is_approved"] = True
        # add firm
        if not op_record.firm:
            try:
                obj_dict["firm_id"] = (
                    op_record.created_by.user_firms.filter(company_id=company_id)
                    .first()
                    .pk
                )
            except Exception:
                pass
        # add final status
        try:
            status_id = (
                ServiceOrderActionStatusSpecs.objects.using(db_alias)
                .filter(
                    company_id=company_id,
                    status__name__icontains="registro deferido",
                    status__kind=status_types.OCCURRENCE_RECORD_STATUS,
                )[0]
                .status_id
            )
            obj_dict["status_id"] = status_id
        except Exception:
            pass

        # create occurrence_record
        occ_record = OccurrenceRecord.objects.create(**obj_dict)
        # add operational search_tag
        try:
            operational_search_tag_id = (
                SearchTag.objects.using(db_alias)
                .filter(
                    company_id=company_id,
                    level=1,
                    name__icontains="operacional",
                )
                .first()
                .pk
            )
            occ_record.search_tags.add(operational_search_tag_id)
        except Exception:
            pass

        # update created_at and uptaded_at fields because they are
        # auto_now fields and we need them to be equals with op_record
        occ_record.created_at = op_record.created_at
        occ_record.updated_at = op_record.updated_at

        # Procedures
        # save all procedures in occurrence_record form_data
        procedure_objects = []
        op_procedures = (
            Procedure.objects.using(db_alias)
            .filter(operational_control_records=op_record)
            .distinct()
        )
        for procedure in op_procedures:
            service_order = procedure.action.service_order
            procedure_objects.append(
                {
                    "uuid": str(procedure.pk),
                    "service_order": {"id": str(service_order.pk)},
                    "service_order_action": {"id": str(procedure.action.pk)},
                }
            )
            # add record to procedure
            procedure.occurrence_records.add(occ_record)
            # add service_order to record
            occ_record.service_orders.add(service_order)
        if procedure_objects:
            occ_record.form_data["include_procedures"] = True
            occ_record.form_data["objects_created"] = True
            occ_record.form_data["procedure_objects"] = procedure_objects

        # save record
        occ_record.save()

        # Files
        op_files = (
            File.objects.using(db_alias)
            .filter(
                content_type_id=op_record_content_type.pk,
                object_id=op_record.pk,
            )
            .distinct()
        )
        for op_file in op_files:
            op_file.content_type_id = occ_record_content_type.pk
            op_file.object_id = occ_record.pk
            op_file.save()

        # MaterialUsage
        op_usages = (
            MaterialUsage.objects.using(db_alias)
            .filter(operational_control_record=op_record)
            .distinct()
        )
        for usage in op_usages:
            usage.occurrence_record = occ_record
            usage.save()

        # History
        # First delete history from occ_record
        HistoricalOccurrenceRecord.objects.using(db_alias).filter(
            uuid=occ_record.pk
        ).delete()

        op_history = (
            HistoricalOperationalControlRecord.objects.using(db_alias)
            .filter(uuid=op_record.pk)
            .distinct()
        )
        for history in op_history:
            history_dict = copy.deepcopy(history.__dict__)
            if "_state" in history_dict:
                del history_dict["_state"]
            history_dict["company_id"] = occ_record.company_id
            history_dict["history_relation_id"] = occ_record.pk
            history_dict["geometry"] = None
            HistoricalOccurrenceRecord.objects.create(**history_dict)


def delete_occurrence_records(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    # Required models
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    MaterialUsage = apps.get_model("monitorings", "MaterialUsage")
    File = apps.get_model("files", "File")
    # Required history models
    HistoricalOccurrenceRecord = apps.get_model(
        "occurrence_records", "HistoricalOccurrenceRecord"
    )
    # Required ContentTypes
    occ_record_content_type = ContentType.objects.get(id=19)
    op_record_content_type = ContentType.objects.get(id=144)

    records = OccurrenceRecord.objects.using(db_alias).filter(
        operational_control__isnull=False
    )
    # Change all Files
    op_files = (
        File.objects.using(db_alias)
        .filter(content_type_id=occ_record_content_type.pk, object_id__in=records)
        .distinct()
    )
    for op_file in tqdm(op_files):
        op_file.content_type_id = op_record_content_type.pk
        op_file.save()

    # Delete all records
    records.delete()

    # Delete all histories
    HistoricalOccurrenceRecord.objects.using(db_alias).filter(
        operational_control__isnull=False
    ).delete()

    # Change all MaterialUsage
    occ_usages = (
        MaterialUsage.objects.using(db_alias)
        .filter(occurrence_record__isnull=False)
        .distinct()
    )
    for usage in tqdm(occ_usages):
        usage.occurrence_record = None
        usage.save()


class Migration(migrations.Migration):

    dependencies = [("occurrence_records", "0066_auto_20210924_1530")]

    operations = [
        migrations.RunPython(
            create_occurrence_records, reverse_code=migrations.RunPython.noop
        )
    ]
