# Generated by Django 2.2.23 on 2021-10-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0067_auto_20210924_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaloccurrencerecord",
            name="origin",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencerecord",
            name="origin_media",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="origin",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="origin_media",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
