# Generated by Django 2.2.23 on 2022-02-15 12:51

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0037_auto_20220202_1631"),
        ("occurrence_records", "0068_auto_20211008_0746"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="monitoring_plan",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="monitorings.MonitoringPlan",
            ),
        ),
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="repetition",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="monitoring_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitoring_records",
                to="monitorings.MonitoringPlan",
            ),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="repetition",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
