# Generated by Django 2.2.23 on 2022-04-13 14:00

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("permissions", "0008_auto_20200902_1646"),
        ("companies", "0053_merge_20220210_0019"),
        ("occurrence_records", "0068_auto_20211008_0746"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordPanel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "panel_type",
                    models.CharField(
                        choices=[("LIST", "LIST"), ("KANBAN", "KANBAN")],
                        max_length=6,
                    ),
                ),
                (
                    "conditions",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "list_columns",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "list_order_by",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "kanban_columns",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "kanban_group_by",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_record_panels",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_record_panels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editor_firms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="record_panels_editor",
                        to="companies.Firm",
                    ),
                ),
                (
                    "editor_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="record_panels_editor",
                        to="permissions.UserPermission",
                    ),
                ),
                (
                    "editor_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="record_panels_editor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "viewer_firms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="record_panels_viewer",
                        to="companies.Firm",
                    ),
                ),
                (
                    "viewer_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="record_panels_viewer",
                        to="permissions.UserPermission",
                    ),
                ),
                (
                    "viewer_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="record_panels_viewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["company"]},
        )
    ]
