# Generated by Django 2.2.23 on 2022-03-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorings", "0038_historicalmonitoringcollect_monitoringcollect"),
        ("occurrence_records", "0069_auto_20220215_0951"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencerecord",
            name="monitoring_points",
            field=models.ManyToManyField(
                blank=True,
                related_name="points_records",
                to="monitorings.MonitoringPoint",
            ),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="monitoring_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="point_records",
                to="monitorings.MonitoringPoint",
            ),
        ),
    ]
