# Generated by Django 2.2.23 on 2022-04-18 18:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("occurrence_records", "0069_recordpanel"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordPanelShowList",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_show_lists",
                        to="occurrence_records.RecordPanel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_show_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["panel__company"],
                "unique_together": {("panel", "user")},
            },
        ),
        migrations.AddField(
            model_name="recordpanel",
            name="show_in_list_users",
            field=models.ManyToManyField(
                blank=True,
                through="occurrence_records.RecordPanelShowList",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
