# Generated by Django 2.2.23 on 2022-05-12 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
        ("occurrence_records", "0070_auto_20220418_1509"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="integration_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.IntegrationRun",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="integration_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="integrations.IntegrationRun",
            ),
        ),
    ]
