# Generated by Django 2.2.23 on 2022-03-08 12:40

from django.db import migrations
from tqdm import tqdm


def fill_monitoring_points_field(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")
    records = OccurrenceRecord.objects.using(db_alias).filter(
        monitoring_point__isnull=False
    )

    for record in tqdm(records):
        if record.monitoring_point is not None:
            record.monitoring_points.add(record.monitoring_point)


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0070_auto_20220308_0939"),
    ]

    operations = [
        migrations.RunPython(
            fill_monitoring_points_field, reverse_code=migrations.RunPython.noop
        )
    ]
