# Generated by Django 2.2.23 on 2022-07-07 15:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0053_merge_20220210_0019"),
        ("occurrence_records", "0071_dashboard_historicaldashboard"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dashboard",
            new_name="CustomDashboard",
        ),
        migrations.RenameModel(
            old_name="HistoricalDashboard",
            new_name="HistoricalCustomDashboard",
        ),
        migrations.AlterModelOptions(
            name="historicalcustomdashboard",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical custom dashboard",
            },
        ),
    ]
