# Generated by Django 2.2.23 on 2022-03-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0071_auto_20220308_0940"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaloccurrencerecord",
            name="monitoring_point",
        ),
        migrations.RemoveField(
            model_name="occurrencerecord",
            name="monitoring_point",
        ),
    ]
