# Generated by Django 2.2.23 on 2022-07-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0072_auto_20220308_0942"),
        ("occurrence_records", "0073_dataseries_historicaldataseries"),
    ]

    operations = []
