# Generated by Django 2.2.28 on 2022-09-05 16:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0073_dataseries_historicaldataseries"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataseries",
            name="json_logic",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="dataseries",
            name="kind",
            field=models.CharField(
                choices=[("SERIES", "SERIES"), ("LOGIC", "LOGIC")],
                default="SERIES",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="historicaldataseries",
            name="json_logic",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldataseries",
            name="kind",
            field=models.CharField(
                choices=[("SERIES", "SERIES"), ("LOGIC", "LOGIC")],
                default="SERIES",
                max_length=6,
            ),
        ),
    ]
