# Generated by Django 2.2.28 on 2022-09-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0073_dataseries_historicaldataseries"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="validation_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="validation_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
