# Generated by Django 2.2.28 on 2022-10-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0054_auto_20220711_1147"),
        ("occurrence_records", "0074_auto_20220920_1141"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordpanel",
            name="editor_subcompanies",
            field=models.ManyToManyField(
                blank=True,
                related_name="record_panels_editor",
                to="companies.SubCompany",
            ),
        ),
        migrations.AddField(
            model_name="recordpanel",
            name="viewer_subcompanies",
            field=models.ManyToManyField(
                blank=True,
                related_name="record_panels_viewer",
                to="companies.SubCompany",
            ),
        ),
    ]
