# Generated by Django 2.2.23 on 2022-10-27 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0074_auto_20220920_1141"),
        ("occurrence_records", "0074_auto_20220905_1345"),
    ]

    operations = []
