# Generated by Django 2.2.23 on 2022-11-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0075_merge_20221027_1904"),
        ("occurrence_records", "0074_merge_20220726_1514"),
    ]

    operations = []
