# Generated by Django 2.2.28 on 2022-10-17 11:56

import django.db.models.deletion
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models


def auto_fill_content_type(app, schema_editor):
    default_content_type = ContentType.objects.get(
        app_label="occurrence_records", model="occurrencerecord"
    )
    model_class = app.get_model("occurrence_records", "recordpanel")
    model_class.objects.all().update(content_type=default_content_type)


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("occurrence_records", "0075_auto_20221010_1546"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordpanel",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(
                        ("app_label", "occurrence_records"),
                        ("model", "occurrencerecord"),
                    ),
                    models.Q(("app_label", "reportings"), ("model", "reporting")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.RunPython(auto_fill_content_type),
    ]
