# Generated by Django 2.2.28 on 2022-11-04 12:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("occurrence_records", "0075_merge_20221027_1904"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordpanel",
            name="color",
            field=models.CharField(default="#005dffb3", max_length=100),
        ),
        migrations.AddField(
            model_name="recordpanel",
            name="icon",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="recordpanel",
            name="icon_size",
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name="recordpanel",
            name="show_in_list_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="show_list_record_panels",
                through="occurrence_records.RecordPanelShowList",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RecordPanelShowWebMap",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_show_web_maps",
                        to="occurrence_records.RecordPanel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_show_web_maps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["panel__company"],
                "unique_together": {("panel", "user")},
            },
        ),
        migrations.CreateModel(
            name="RecordPanelShowMobileMap",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_show_mobile_maps",
                        to="occurrence_records.RecordPanel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_show_mobile_maps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["panel__company"],
                "unique_together": {("panel", "user")},
            },
        ),
        migrations.AddField(
            model_name="recordpanel",
            name="show_in_mobile_map",
            field=models.ManyToManyField(
                blank=True,
                related_name="show_mobile_map_record_panels",
                through="occurrence_records.RecordPanelShowMobileMap",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recordpanel",
            name="show_in_web_map",
            field=models.ManyToManyField(
                blank=True,
                related_name="show_web_map_record_panels",
                through="occurrence_records.RecordPanelShowWebMap",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
