# Generated by Django 2.2.28 on 2022-11-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0076_auto_20221104_0959"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recordpanel",
            old_name="show_in_mobile_map",
            new_name="show_in_mobile_map_users",
        ),
        migrations.RenameField(
            model_name="recordpanel",
            old_name="show_in_web_map",
            new_name="show_in_web_map_users",
        ),
    ]
