# Generated by Django 2.2.28 on 2022-11-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0077_auto_20221104_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordpanel",
            name="icon",
            field=models.TextField(blank=True, null=True),
        ),
    ]
