# Generated by Django 2.2.23 on 2022-11-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0076_merge_20221111_1348"),
        ("occurrence_records", "0071_auto_20220512_0106"),
        ("occurrence_records", "0078_auto_20221108_0911"),
    ]

    operations = []
