# Generated by Django 2.2.23 on 2022-12-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0076_recordpanel_content_type"),
        ("occurrence_records", "0079_merge_20221121_0956"),
    ]

    operations = []
