# Generated by Django 2.2.28 on 2023-05-04 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("occurrence_records", "0080_merge_20221205_1921"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recordpanel",
            name="show_in_mobile_map_users",
        ),
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="color",
            field=models.CharField(
                blank=True, default="#005dffb3", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="icon",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="icon_size",
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="show_in_app_map",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="show_in_web_map",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="color",
            field=models.CharField(
                blank=True, default="#005dffb3", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="icon",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="icon_size",
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="show_in_app_map",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="show_in_web_map",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recordpanel",
            name="show_in_app_map_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="show_app_map_record_panels",
                through="occurrence_records.RecordPanelShowMobileMap",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
