# Generated by Django 2.2.28 on 2023-05-16 13:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0081_auto_20230504_1257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdashboard",
            name="plot_descriptions",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomdashboard",
            name="plot_descriptions",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
    ]
