# Generated by Django 2.2.28 on 2023-09-13 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0082_auto_20230516_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="main_linked_record",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="main_linked_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_link_records",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="other_linked_records",
            field=models.ManyToManyField(
                blank=True,
                related_name="_occurrencerecord_other_linked_records_+",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
    ]
