# Generated by Django 2.2.28 on 2023-05-16 14:07

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0009_auto_20190809_1341"),
        ("occurrence_records", "0082_auto_20230516_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdashboard",
            name="cities",
            field=models.ManyToManyField(
                blank=True, related_name="city_custom_dashboards", to="locations.City"
            ),
        ),
        migrations.AddField(
            model_name="customdashboard",
            name="hidro_basins",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
        migrations.AddField(
            model_name="customdashboard",
            name="sih_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOURLY", "HOURLY"),
                    ("DAILY", "DAILY"),
                    ("MONTHLY", "MONTHLY"),
                ],
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customdashboard",
            name="sih_monitoring_parameters",
            field=models.ManyToManyField(
                blank=True,
                related_name="occurrence_record_sih_monitoring_parameters",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="dataseries",
            name="sih_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOURLY", "HOURLY"),
                    ("DAILY", "DAILY"),
                    ("MONTHLY", "MONTHLY"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="dataseries",
            name="sih_monitoring_parameter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrence_record_sih_parameters",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomdashboard",
            name="hidro_basins",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomdashboard",
            name="sih_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOURLY", "HOURLY"),
                    ("DAILY", "DAILY"),
                    ("MONTHLY", "MONTHLY"),
                ],
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaldataseries",
            name="sih_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOURLY", "HOURLY"),
                    ("DAILY", "DAILY"),
                    ("MONTHLY", "MONTHLY"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaldataseries",
            name="sih_monitoring_parameter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AlterField(
            model_name="dataseries",
            name="kind",
            field=models.CharField(
                choices=[("SERIES", "SERIES"), ("LOGIC", "LOGIC"), ("SIH", "SIH")],
                default="SERIES",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldataseries",
            name="kind",
            field=models.CharField(
                choices=[("SERIES", "SERIES"), ("LOGIC", "LOGIC"), ("SIH", "SIH")],
                default="SERIES",
                max_length=6,
            ),
        ),
    ]
