# Generated by Django 2.2.28 on 2023-06-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0049_create_menus"),
        ("occurrence_records", "0082_auto_20230516_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordpanel",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_record_panels",
                to="reportings.RecordMenu",
            ),
        ),
        migrations.AddField(
            model_name="recordpanel",
            name="system_default",
            field=models.BooleanField(default=False),
        ),
    ]
