# Generated by Django 2.2.28 on 2023-07-04 06:01

from django.db import migrations
from django.db.models import Q

from apps.companies.const.app_types import ENERGY


def create_panel_menus(apps, schema_editor):
    content_type_model = apps.get_model("contenttypes", "ContentType")
    content_type = content_type_model.objects.get(
        app_label="reportings", model="reporting"
    )
    record_panel_model = apps.get_model("occurrence_records", "recordpanel")
    company_model = apps.get_model("companies", "company")
    companies = (
        company_model.objects.all()
        .exclude(Q(mobile_app_override=ENERGY) | Q(company_group__mobile_app=ENERGY))
        .distinct()
    )

    record_panel_entries = []
    for company in companies:
        menus = company.recordmenu_set.filter(
            Q(system_default=False) & Q(name="Apontamentos")
        ).distinct()
        for menu in menus:
            record_panel_entries.append(
                record_panel_model(
                    name="Todos",
                    panel_type="LIST",
                    conditions=dict(),
                    list_columns=None,
                    company=company,
                    content_type=content_type,
                    system_default=True,
                    menu=menu,
                )
            )
    record_panel_model.objects.bulk_create(record_panel_entries)


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0051_fill_reportings_menus"),
        ("occurrence_records", "0083_auto_20230627_1146"),
    ]

    operations = [migrations.RunPython(create_panel_menus)]
