# Generated by Django 2.2.28 on 2023-05-17 17:30

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0056_auto_20230505_1201"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0009_auto_20190809_1341"),
        ("occurrence_records", "0083_auto_20230516_1107"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableDataSeries",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SERIES", "SERIES"),
                            ("LOGIC", "LOGIC"),
                            ("SIH", "SIH"),
                        ],
                        default="SERIES",
                        max_length=6,
                    ),
                ),
                ("field_name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sih_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOURLY", "HOURLY"),
                            ("DAILY", "DAILY"),
                            ("MONTHLY", "MONTHLY"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_table_data_series",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_table_data_series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occurrence_record_table_data_series",
                        to="occurrence_records.OccurrenceRecord",
                    ),
                ),
                (
                    "sih_monitoring_parameter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occurrence_record_sih_parameters_table_data_series",
                        to="occurrence_records.OccurrenceRecord",
                    ),
                ),
            ],
            options={
                "ordering": ["company"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTableDataSeries",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SERIES", "SERIES"),
                            ("LOGIC", "LOGIC"),
                            ("SIH", "SIH"),
                        ],
                        default="SERIES",
                        max_length=6,
                    ),
                ),
                ("field_name", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "sih_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOURLY", "HOURLY"),
                            ("DAILY", "DAILY"),
                            ("MONTHLY", "MONTHLY"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument_record",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="occurrence_records.OccurrenceRecord",
                    ),
                ),
                (
                    "sih_monitoring_parameter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="occurrence_records.OccurrenceRecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical table data series",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCustomTable",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("start_period", models.DateTimeField(blank=True, editable=False)),
                ("end_period", models.DateTimeField(blank=True, editable=False)),
                (
                    "table_type",
                    models.CharField(
                        choices=[
                            ("ANALYSIS", "ANALYSIS"),
                            ("COMPARISON", "COMPARISON"),
                        ],
                        default="ANALYSIS",
                        max_length=10,
                    ),
                ),
                (
                    "columns_break",
                    models.CharField(
                        choices=[("DAY", "DAY"), ("MONTH", "MONTH"), ("YEAR", "YEAR")],
                        default="DAY",
                        max_length=10,
                    ),
                ),
                (
                    "line_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOURLY", "HOURLY"),
                            ("DAILY", "DAILY"),
                            ("MONTHLY", "MONTHLY"),
                        ],
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "hidro_basins",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "additional_columns",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "additional_lines",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "table_descriptions",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical custom table",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CustomTable",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_period", models.DateTimeField(auto_now_add=True)),
                ("end_period", models.DateTimeField(auto_now_add=True)),
                (
                    "table_type",
                    models.CharField(
                        choices=[
                            ("ANALYSIS", "ANALYSIS"),
                            ("COMPARISON", "COMPARISON"),
                        ],
                        default="ANALYSIS",
                        max_length=10,
                    ),
                ),
                (
                    "columns_break",
                    models.CharField(
                        choices=[("DAY", "DAY"), ("MONTH", "MONTH"), ("YEAR", "YEAR")],
                        default="DAY",
                        max_length=10,
                    ),
                ),
                (
                    "line_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOURLY", "HOURLY"),
                            ("DAILY", "DAILY"),
                            ("MONTHLY", "MONTHLY"),
                        ],
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "hidro_basins",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "additional_columns",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "additional_lines",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=list, null=True
                    ),
                ),
                (
                    "table_descriptions",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "can_be_edited_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_tables_editor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "can_be_viewed_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_tables_viewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cities",
                    models.ManyToManyField(
                        blank=True, related_name="custom_tables", to="locations.City"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_tables",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument_records",
                    models.ManyToManyField(
                        blank=True,
                        related_name="occurrence_record_tables",
                        to="occurrence_records.OccurrenceRecord",
                    ),
                ),
                (
                    "sih_monitoring_parameters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tables_sih_monitoring_parameters",
                        to="occurrence_records.OccurrenceRecord",
                    ),
                ),
            ],
            options={
                "ordering": ["company"],
            },
        ),
    ]
