# Generated by Django 2.2.28 on 2023-06-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("occurrence_records", "0084_auto_20230613_0649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataseries",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SERIES", "SERIES"),
                    ("LOGIC", "LOGIC"),
                    ("SIH", "SIH"),
                    ("SIH_LAST_VALUE", "SIH_LAST_VALUE"),
                ],
                default="SERIES",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="historicaldataseries",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SERIES", "SERIES"),
                    ("LOGIC", "LOGIC"),
                    ("SIH", "SIH"),
                    ("SIH_LAST_VALUE", "SIH_LAST_VALUE"),
                ],
                default="SERIES",
                max_length=14,
            ),
        ),
    ]
