# Generated by Django 2.2.28 on 2023-05-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "occurrence_records",
            "0084_customtable_historicalcustomtable_historicaltabledataseries_tabledataseries",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customtable",
            name="table_data_series",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_tables",
                to="occurrence_records.TableDataSeries",
            ),
        ),
    ]
