# Generated by Django 2.2.28 on 2023-05-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0085_customtable_table_data_series"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtable",
            name="sih_monitoring_parameters",
        ),
        migrations.AlterField(
            model_name="customtable",
            name="end_period",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="customtable",
            name="start_period",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="historicalcustomtable",
            name="end_period",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="historicalcustomtable",
            name="start_period",
            field=models.DateField(),
        ),
    ]
