# Generated by Django 2.2.28 on 2023-06-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0085_auto_20230613_1408"),
        ("occurrence_records", "0086_auto_20230530_1938"),
    ]

    operations = []
