# Generated by Django 2.2.28 on 2023-07-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0087_merge_20230629_1126"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltabledataseries",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SERIES", "SERIES"),
                    ("LOGIC", "LOGIC"),
                    ("SIH", "SIH"),
                    ("SIH_LAST_VALUE", "SIH_LAST_VALUE"),
                ],
                default="SERIES",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="tabledataseries",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SERIES", "SERIES"),
                    ("LOGIC", "LOGIC"),
                    ("SIH", "SIH"),
                    ("SIH_LAST_VALUE", "SIH_LAST_VALUE"),
                ],
                default="SERIES",
                max_length=6,
            ),
        ),
    ]
