# Generated by Django 2.2.28 on 2023-12-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0083_auto_20230913_0913"),
        ("occurrence_records", "0088_auto_20230719_1105"),
    ]

    operations = []
