# Generated by Django 2.2.28 on 2023-12-19 15:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0088_auto_20230719_1105"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdashboard",
            name="end_date_hydrological_parameters",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customdashboard",
            name="hydrological_parameters",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="customdashboard",
            name="monitoring_points",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="customdashboard",
            name="start_date_hydrological_parameters",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomdashboard",
            name="end_date_hydrological_parameters",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomdashboard",
            name="hydrological_parameters",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="historicalcustomdashboard",
            name="monitoring_points",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="historicalcustomdashboard",
            name="start_date_hydrological_parameters",
            field=models.DateField(blank=True, null=True),
        ),
    ]
