# Generated by Django 2.2.28 on 2024-03-15 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0089_auto_20231219_1230"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customdashboard",
            name="hydrological_parameters",
        ),
        migrations.RemoveField(
            model_name="customdashboard",
            name="monitoring_points",
        ),
        migrations.RemoveField(
            model_name="historicalcustomdashboard",
            name="hydrological_parameters",
        ),
        migrations.RemoveField(
            model_name="historicalcustomdashboard",
            name="monitoring_points",
        ),
        migrations.AddField(
            model_name="customdashboard",
            name="sih_monitoring_points",
            field=models.ManyToManyField(
                blank=True,
                related_name="occurrence_record_sih_monitoring_points_dashboards",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="customtable",
            name="sih_monitoring_points",
            field=models.ManyToManyField(
                blank=True,
                related_name="occurrence_record_sih_monitoring_points_record_tables",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="dataseries",
            name="sih_monitoring_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrence_record_sih_monitoring_point_data_series",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="historicaldataseries",
            name="sih_monitoring_point",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="historicaltabledataseries",
            name="sih_monitoring_point",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
        migrations.AddField(
            model_name="tabledataseries",
            name="sih_monitoring_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrence_record_sih_monitoring_point_table_data_series",
                to="occurrence_records.OccurrenceRecord",
            ),
        ),
    ]
