# Generated by Django 2.2.28 on 2024-04-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0090_auto_20240315_1402"),
        ("occurrence_records", "0089_merge_20231211_0942"),
    ]

    operations = []
