# Generated by Django 2.2.28 on 2024-05-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0091_merge_20240422_1356"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="kind",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="kind_tag_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="record",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="record_tag",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="record_tag_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="subject",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="subject_tag_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="type",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="type_tag",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="historicaloccurrencerecord",
            name="type_tag_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="kind",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="kind_tag_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="record",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="record_tag",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="record_tag_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="subject",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="subject_tag_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="type",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="type_tag",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="occurrencerecord",
            name="type_tag_id",
            field=models.TextField(null=True),
        ),
    ]
