# Generated by Django 2.2.28 on 2024-06-04 18:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0091_merge_20240422_1356"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaloccurrencetype",
            name="custom_map_table",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="occurrencetype",
            name="custom_map_table",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
