# Generated by Django 2.2.28 on 2024-06-06 19:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0093_fill_custom_map_table_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaloccurrencetype",
            name="custom_map_table",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list
            ),
        ),
        migrations.AlterField(
            model_name="occurrencetype",
            name="custom_map_table",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list
            ),
        ),
    ]
