# Generated by Django 2.2.28 on 2024-07-03 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("occurrence_records", "0093_fill_search_tags_fields"),
        ("occurrence_records", "0092_change_road_to_road_name_in_record_panel"),
    ]

    operations = []
