# Generated by Django 2.2.28 on 2024-07-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0094_merge_20240703_1534"),
        ("occurrence_records", "0084_create_panel_menus"),
    ]

    operations = []
