# Generated by Django 2.2.28 on 2024-08-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0094_merge_20240703_1534"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaloccurrencetype",
            name="show_in_app_map",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="occurrencetype",
            name="show_in_app_map",
            field=models.BooleanField(default=True),
        ),
    ]
