# Generated by Django 2.2.28 on 2024-09-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0096_recordpanelshowlist_new_to_user"),
        ("occurrence_records", "0094_auto_20240606_1639"),
    ]

    operations = []
