# Generated by Django 2.2.28 on 2024-09-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0097_merge_20240913_1628"),
        ("occurrence_records", "0095_auto_20240806_1405"),
    ]

    operations = []
