# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0099_historicalrecordpanelshowlist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalcustomdashboard",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical custom dashboard",
                "verbose_name_plural": "historical custom dashboards",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcustomtable",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical custom table",
                "verbose_name_plural": "historical custom tables",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldataseries",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical data series",
                "verbose_name_plural": "historical data seriess",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaloccurrencerecord",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical occurrence record",
                "verbose_name_plural": "historical occurrence records",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaloccurrencerecordwatcher",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical occurrence record watcher",
                "verbose_name_plural": "historical occurrence record watchers",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaloccurrencetype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical occurrence type",
                "verbose_name_plural": "historical occurrence types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaloccurrencetypespecs",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical occurrence type specs",
                "verbose_name_plural": "historical occurrence type specss",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrecordpanelshowlist",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical record panel show list",
                "verbose_name_plural": "historical record panel show lists",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaltabledataseries",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical table data series",
                "verbose_name_plural": "historical table data seriess",
            },
        ),
        migrations.AlterField(
            model_name="customdashboard",
            name="hidro_basins",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="customdashboard",
            name="operational_positions",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="customdashboard",
            name="plot_descriptions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="customtable",
            name="additional_columns",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="customtable",
            name="additional_lines",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="customtable",
            name="hidro_basins",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="customtable",
            name="table_descriptions",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="dataseries",
            name="json_logic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomdashboard",
            name="hidro_basins",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomdashboard",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomdashboard",
            name="operational_positions",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomdashboard",
            name="plot_descriptions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomtable",
            name="additional_columns",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomtable",
            name="additional_lines",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomtable",
            name="hidro_basins",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomtable",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomtable",
            name="table_descriptions",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldataseries",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaldataseries",
            name="json_logic",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencerecord",
            name="arcgis_ids",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencerecord",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencerecord",
            name="form_metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencerecord",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencerecord",
            name="informer",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencerecord",
            name="involved_parts",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencerecord",
            name="properties",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencerecordwatcher",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencetype",
            name="custom_map_table",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencetype",
            name="form_fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencetype",
            name="goal_formula",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencetype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencetype",
            name="repetition",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaloccurrencetypespecs",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalrecordpanelshowlist",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltabledataseries",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaltabledataseries",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SERIES", "SERIES"),
                    ("LOGIC", "LOGIC"),
                    ("SIH", "SIH"),
                    ("SIH_LAST_VALUE", "SIH_LAST_VALUE"),
                ],
                default="SERIES",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="arcgis_ids",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="form_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="form_metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="informer",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="involved_parts",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="occurrencerecord",
            name="properties",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="occurrencetype",
            name="custom_map_table",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="occurrencetype",
            name="form_fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="occurrencetype",
            name="goal_formula",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="occurrencetype",
            name="repetition",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="recordpanel",
            name="conditions",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="recordpanel",
            name="kanban_columns",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="recordpanel",
            name="kanban_group_by",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="recordpanel",
            name="list_columns",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="recordpanel",
            name="list_order_by",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="tabledataseries",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SERIES", "SERIES"),
                    ("LOGIC", "LOGIC"),
                    ("SIH", "SIH"),
                    ("SIH_LAST_VALUE", "SIH_LAST_VALUE"),
                ],
                default="SERIES",
                max_length=14,
            ),
        ),
    ]
