# Generated by Django 3.2.25 on 2025-07-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0100_auto_20250227_1243"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customtable",
            old_name="end_period",
            new_name="_end_period",
        ),
        migrations.RenameField(
            model_name="customtable",
            old_name="start_period",
            new_name="_start_period",
        ),
        migrations.RenameField(
            model_name="historicalcustomtable",
            old_name="end_period",
            new_name="_end_period",
        ),
        migrations.RenameField(
            model_name="historicalcustomtable",
            old_name="start_period",
            new_name="_start_period",
        ),
    ]
