# Generated by Django 3.2.25 on 2025-07-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occurrence_records", "0101_auto_20250724_1839"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtable",
            name="dynamic_period_in_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomtable",
            name="dynamic_period_in_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customtable",
            name="_end_period",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customtable",
            name="_start_period",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomtable",
            name="_end_period",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcustomtable",
            name="_start_period",
            field=models.DateField(blank=True, null=True),
        ),
    ]
