# Generated by Django 2.1.1 on 2018-10-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workplan",
            name="procedures",
            field=models.ManyToManyField(
                limit_choices_to={"procedure_next": None},
                related_name="work_plans",
                to="service_orders.Procedure",
            ),
        ),
    ]
