# Generated by Django 2.1.2 on 2019-03-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0004_historicaljob_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
