# Generated by Django 2.1.2 on 2020-05-26 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0033_auto_20200521_0005"),
        ("work_plans", "0005_auto_20190328_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="watcher_firms",
            field=models.ManyToManyField(
                blank=True,
                related_name="watcher_firm_jobs",
                to="companies.Firm",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="watcher_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="watcher_user_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
