# Generated by Django 2.1.2 on 2020-05-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0005_auto_20190328_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="last_notification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="last_notification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
