# Generated by Django 2.1.2 on 2020-06-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0006_auto_20200528_1653"),
        ("work_plans", "0006_auto_20200526_1550"),
    ]

    operations = []
