# Generated by Django 2.1.2 on 2020-07-02 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0007_merge_20200601_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
