# Generated by Django 2.1.2 on 2020-07-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("work_plans", "0008_auto_20200702_0944")]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
