# Generated by Django 2.1.2 on 2020-08-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0009_auto_20200723_1024"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
