# Generated by Django 2.1.2 on 2021-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0010_auto_20200811_1126"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="executed_reportings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="progress",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="reporting_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="executed_reportings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="progress",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="reporting_count",
            field=models.IntegerField(default=0),
        ),
    ]
