# Generated by Django 2.1.2 on 2021-05-10 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0039_auto_20210506_0900"),
        ("work_plans", "0012_calculate_job_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="inspection",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="reportings.Reporting",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="inspection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inspection_jobs",
                to="reportings.Reporting",
            ),
        ),
    ]
