# Generated by Django 2.2.28 on 2023-01-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0054_auto_20220711_1147"),
        ("work_plans", "0014_auto_20210514_0130"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="watcher_subcompanies",
            field=models.ManyToManyField(
                blank=True,
                related_name="watcher_subcompanies_jobs",
                to="companies.SubCompany",
            ),
        ),
    ]
