# Generated by Django 2.2.23 on 2023-06-12 19:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0015_job_watcher_subcompanies"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeViewManager",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notice", models.CharField(max_length=30)),
                ("views_quantity_limit", models.IntegerField(default=0)),
            ],
        ),
    ]
