# Generated by Django 2.2.23 on 2023-07-06 18:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0057_merge_20230601_1835"),
        ("work_plans", "0017_create_notice_view_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNoticeView",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("views_quantity_limit", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_user_notice_views",
                        to="companies.Company",
                    ),
                ),
                (
                    "notice_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_views",
                        to="work_plans.NoticeViewManager",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notice_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
