# Generated by Django 2.2.23 on 2023-07-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0018_usernoticeview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usernoticeview",
            old_name="notice_view",
            new_name="notice_view_manager",
        ),
        migrations.RenameField(
            model_name="usernoticeview",
            old_name="views_quantity_limit",
            new_name="views_quantity",
        ),
    ]
