# Generated by Django 2.2.28 on 2023-09-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0019_auto_20230706_1750"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="processing_async_creation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="processing_async_creation",
            field=models.BooleanField(default=False),
        ),
    ]
