# Generated by Django 2.2.28 on 2023-10-16 11:29

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0050_auto_20230901_1441"),
        (
            "service_orders",
            "0100_historicalpendingproceduresexport_pendingproceduresexport",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0059_merge_20230918_1024"),
        ("occurrence_records", "0082_auto_20230516_1044"),
        ("work_plans", "0020_auto_20230925_0958"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob",
            name="processing_async_creation",
        ),
        migrations.RemoveField(
            model_name="job",
            name="processing_async_creation",
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="creating_batches",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="creating_batches",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="JobAsyncBatch",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("in_progress", models.BooleanField(default=False)),
                (
                    "batch_type",
                    models.CharField(
                        choices=[("FILTERED", "FILTERED"), ("MANUAL", "MANUAL")],
                        max_length=100,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_jobasyncbatchs",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_jobasyncbatchs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "in_job_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_job_status_async_batches",
                        to="service_orders.ServiceOrderActionStatus",
                    ),
                ),
                (
                    "inventories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="inventory_async_batches",
                        to="reportings.Reporting",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_async_batches",
                        to="work_plans.Job",
                    ),
                ),
                (
                    "occurrence_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="occurrence_type_async_batches",
                        to="occurrence_records.OccurrenceType",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalJobAsyncBatch",
            fields=[
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_change_reason", models.TextField(null=True)),
                ("in_progress", models.BooleanField(default=False)),
                (
                    "batch_type",
                    models.CharField(
                        choices=[("FILTERED", "FILTERED"), ("MANUAL", "MANUAL")],
                        max_length=100,
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history_historicaljobasyncbatchs",
                        to="work_plans.JobAsyncBatch",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "in_job_status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="service_orders.ServiceOrderActionStatus",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="work_plans.Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical job async batch",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
