# Generated by Django 2.2.28 on 2023-10-19 12:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0021_auto_20231016_0829"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="pending_inventory_to_reporting_id",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="pending_inventory_to_reporting_id",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        ),
    ]
