# Generated by Django 2.2.28 on 2023-10-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0022_auto_20231019_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="total_inventory_batches",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="total_reporting_in_reporting_batches",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="total_inventory_batches",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="total_reporting_in_reporting_batches",
            field=models.IntegerField(default=0),
        ),
    ]
