# Generated by Django 2.2.28 on 2023-10-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0023_auto_20231019_1641"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob",
            name="pending_inventory_to_reporting_id",
        ),
    ]
