# Generated by Django 2.2.28 on 2023-10-26 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_flows", "0014_auto_20220829_1118"),
        ("work_plans", "0024_remove_historicaljob_pending_inventory_to_reporting_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobasyncbatch",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="approval_flows.ApprovalStep",
            ),
        ),
        migrations.AddField(
            model_name="jobasyncbatch",
            name="approval_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approval_step_async_batches",
                to="approval_flows.ApprovalStep",
            ),
        ),
    ]
