# Generated by Django 2.2.28 on 2023-12-06 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0025_auto_20231026_1026"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobasyncbatch",
            name="found_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="jobasyncbatch",
            name="found_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
