# Generated by Django 2.2.28 on 2024-08-29 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportings", "0057_merge_20240724_1005"),
        ("work_plans", "0026_auto_20231206_1632"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobasyncbatch",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="reportings.RecordMenu",
            ),
        ),
        migrations.AddField(
            model_name="jobasyncbatch",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu_async_batches",
                to="reportings.RecordMenu",
            ),
        ),
    ]
