# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0027_auto_20240829_0900"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaljob",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical job",
                "verbose_name_plural": "historical jobs",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaljobasyncbatch",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical job async batch",
                "verbose_name_plural": "historical job async batchs",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalworkplan",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical work plan",
                "verbose_name_plural": "historical work plans",
            },
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="historicaljobasyncbatch",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalworkplan",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalworkplan",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="pending_inventory_to_reporting_id",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="workplan",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
