# Generated by Django 3.2.25 on 2025-06-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0028_auto_20250227_1243"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workplan",
            name="company",
        ),
        migrations.RemoveField(
            model_name="workplan",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="workplan",
            name="procedures",
        ),
        migrations.RemoveField(
            model_name="workplan",
            name="worker",
        ),
        migrations.DeleteModel(
            name="HistoricalWorkPlan",
        ),
        migrations.DeleteModel(
            name="WorkPlan",
        ),
    ]
