# Generated by Django 3.2.25 on 2026-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_plans", "0029_auto_20250610_1223"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="has_auto_allocated_reportings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="is_automatic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="has_auto_allocated_reportings",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="is_automatic",
            field=models.BooleanField(default=False),
        ),
    ]
