# Generated by Django 2.1.1 on 2018-09-21 13:17

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("HOMOLOGATOR", "HOMOLOGATOR"),
                            ("COORDINATOR", "COORDINATOR"),
                            ("MANAGER", "MANAGER"),
                            ("COLLABORATOR", "COLLABORATOR"),
                            ("SUPPLIER", "SUPPLIER"),
                            ("IT_ADMINISTRATOR", "IT_ADMINISTRATOR"),
                        ],
                        default="COLLABORATOR",
                        max_length=30,
                    ),
                ),
                (
                    "permissions",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.Company",
                    ),
                ),
            ],
        ),
    ]
