# Generated by Django 2.1.2 on 2019-01-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpermission",
            name="name",
            field=models.CharField(
                choices=[
                    ("HOMOLOGATOR", "HOMOLOGATOR"),
                    ("COORDINATOR", "COORDINATOR"),
                    ("MANAGER", "MANAGER"),
                    ("COLLABORATOR", "COLLABORATOR"),
                    ("SUPPLIER", "SUPPLIER"),
                    ("IT_ADMINISTRATOR", "IT_ADMINISTRATOR"),
                ],
                default="COLLABORATOR",
                max_length=100,
            ),
        ),
    ]
