# Generated by Django 2.1.2 on 2019-02-25 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_historicalcompany_historicalfirm_historicaluserincompany"),
        ("permissions", "0003_historicaluserpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermission",
            name="companies",
            field=models.ManyToManyField(
                related_name="permission_companies", to="companies.Company"
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permission_company",
                to="companies.Company",
            ),
        ),
    ]
