# Generated by Django 2.1.2 on 2019-02-25 21:34

from django.db import migrations, models


def make_many_companies(apps, schema_editor):
    UserPermission = apps.get_model("permissions", "UserPermission")
    for permission in UserPermission.objects.all():
        permission.companies.add(permission.company)


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0004_auto_20190225_1834"),
    ]

    operations = [migrations.RunPython(make_many_companies)]
