# Generated by Django 2.1.2 on 2019-02-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0005_auto_20190225_1834"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluserpermission",
            name="company",
        ),
        migrations.RemoveField(
            model_name="userpermission",
            name="company",
        ),
    ]
