# Generated by Django 2.1.2 on 2019-10-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0006_auto_20190225_1839"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserpermission",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
