# Generated by Django 2.1.2 on 2020-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("permissions", "0007_auto_20191015_1714")]

    operations = [
        migrations.AddField(
            model_name="historicaluserpermission",
            name="is_inactive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="is_inactive",
            field=models.BooleanField(default=False),
        ),
    ]
