# Generated by Django 2.2.28 on 2024-10-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0008_auto_20200902_1646"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserpermission",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
