# Generated by Django 2.2.28 on 2024-08-27 14:46

from django.db import migrations
from django_bulk_update.helper import bulk_update
from tqdm import tqdm

from helpers.strings import dict_to_upper_camel_case


def add_can_download_permissions(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    UserPermission = apps.get_model("permissions", "UserPermission")

    user_permissions = UserPermission.objects.using(db_alias).all()
    updated_perms = []
    for perm in tqdm(user_permissions):
        permissions = dict_to_upper_camel_case(perm.permissions)

        if "Reporting" in permissions:
            permissions["Reporting"].update({"can_download": True})
        if "QualityAssay" in permissions:
            permissions["QualityAssay"].update({"can_download": True})
        if "Inventory" in permissions:
            permissions["Inventory"].update({"can_download": True})
        if "Construction" in permissions:
            permissions["Construction"].update({"can_download": True})
        if "Measurement" in permissions:
            permissions["Measurement"].update({"can_download": True})
        if "CustomizationMenu" in permissions:
            permissions["CustomizationMenu"].update({"can_download": True})
        if "Dashboard2" in permissions:
            permissions["Dashboard2"].update({"can_download": True})
        if "OaeSchedule" in permissions:
            permissions["OaeSchedule"].update({"can_download": True})
        if "Contract" in permissions:
            permissions["Contract"].update({"can_download": True})

        perm.permissions = permissions
        updated_perms.append(perm)

    bulk_update(updated_perms, batch_size=250, update_fields=["permissions"])


def reverse_add_can_download_permissions(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    UserPermission = apps.get_model("permissions", "UserPermission")

    user_permissions = UserPermission.objects.using(db_alias).all()
    updated_perms = []
    for perm in tqdm(user_permissions):
        permissions = dict_to_upper_camel_case(perm.permissions)

        if "Reporting" in permissions:
            permissions["Reporting"].pop("can_download", None)
        if "QualityAssay" in permissions:
            permissions["QualityAssay"].pop("can_download", None)
        if "Inventory" in permissions:
            permissions["Inventory"].pop("can_download", None)
        if "Construction" in permissions:
            permissions["Construction"].pop("can_download", None)
        if "Measurement" in permissions:
            permissions["Measurement"].pop("can_download", None)
        if "CustomizationMenu" in permissions:
            permissions["CustomizationMenu"].pop("can_download", None)
        if "Dashboard2" in permissions:
            permissions["Dashboard2"].pop("can_download", None)
        if "OaeSchedule" in permissions:
            permissions["OaeSchedule"].pop("can_download", None)

        perm.permissions = permissions
        updated_perms.append(perm)

    bulk_update(updated_perms, batch_size=250, update_fields=["permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0008_auto_20200902_1646"),
    ]

    operations = [
        migrations.RunPython(
            add_can_download_permissions,
            reverse_code=reverse_add_can_download_permissions,
        )
    ]
