# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0009_auto_20241003_1507"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaluserpermission",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical user permission",
                "verbose_name_plural": "historical user permissions",
            },
        ),
        migrations.AlterField(
            model_name="historicaluserpermission",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaluserpermission",
            name="permissions",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="permissions",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
