# Generated by Django 3.2.25 on 2025-05-29 12:09

from django.db import migrations
from django_bulk_update.helper import bulk_update


def rename_queuedpush_to_pushnotification(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    UserPermission = apps.get_model("permissions", "UserPermission")

    user_permission_qs = UserPermission.objects.using(db_alias).only(
        "uuid", "permissions"
    )
    permissions_to_update = []

    for permission in user_permission_qs:
        perms = permission.permissions or {}

        old_key = next(
            (
                key
                for key in perms.keys()
                if key.replace("_", "").lower() == "queuedpush"
            ),
            None,
        )

        if old_key:
            perms["PushNotification"] = perms.pop(old_key)
            permission.permissions = perms
            permissions_to_update.append(permission)

    if permissions_to_update:
        bulk_update(
            permissions_to_update, update_fields=["permissions"], using=db_alias
        )


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0010_auto_20250227_1243"),
        ("scarface", "0008_auto_20250527_1605"),
        ("users", "0046_alter_user_push_devices"),
    ]

    operations = [
        migrations.RunPython(rename_queuedpush_to_pushnotification),
    ]
