# Generated by Django 3.2.25 on 2025-08-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0009_auto_20240827_1146"),
        ("permissions", "0011_rename_queuedpush_to_pushnotification"),
    ]

    operations = []
