# Generated by Django 3.2.25 on 2025-10-06 21:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0075_merge_0074_auto_20250604_1735_0074_auto_20250909_1951"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormsIARequest",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("occurrence_kind", models.CharField(max_length=200)),
                ("name", models.TextField()),
                ("input_text", models.TextField()),
                ("request_id", models.CharField(blank=True, max_length=255, null=True)),
                ("output_json", models.JSONField(blank=True, default=dict, null=True)),
                ("done", models.BooleanField(default=False)),
                ("error", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms_ia_requests",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_forms_ia_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
