# Generated by Django 2.1.2 on 2019-07-18 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("files", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
