# Generated by Django 2.1.2 on 2019-07-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    ProcedureFile = apps.get_model("service_orders", "ProcedureFile")
    File = apps.get_model("files", "File")
    HistoricalFile = apps.get_model("files", "HistoricalFile")
    ContentType = apps.get_model("contenttypes", "ContentType")
    OccurrenceRecord = apps.get_model("occurrence_records", "OccurrenceRecord")

    db_alias = schema_editor.connection.alias

    first_action_files = ProcedureFile.objects.using(db_alias).filter(
        procedure__action__first_action=True
    )

    occurrence_record_content_type = ContentType.objects.get_for_model(OccurrenceRecord)

    for file in first_action_files:
        new_file = File(
            description=file.description,
            upload=file.upload,
            uploaded_at=file.uploaded_at,
            created_by=file.created_by,
        )
        new_file.object_id = file.procedure.action.service_order.occurrence_record.uuid
        new_file.content_type = occurrence_record_content_type
        new_file.save()
        new_hist = HistoricalFile(
            history_date=file.uploaded_at,
            history_user=file.created_by,
            history_change_reason="",
            history_type="+",
            **{
                field.attname: getattr(new_file, field.attname)
                for field in new_file._meta.fields
            }
        )
        new_hist.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0002_auto_20190717_2143"),
        ("service_orders", "0047_auto_20190625_1201"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop)
    ]
