# Generated by Django 2.1.2 on 2020-01-14 18:11

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def copy_field(apps, schema_editor):
    File = apps.get_model("files", "File")
    File.objects.all().update(datetime=F("uploaded_at"))
    HistoricalFile = apps.get_model("files", "HistoricalFile")
    HistoricalFile.objects.all().update(datetime=F("uploaded_at"))


class Migration(migrations.Migration):

    dependencies = [("files", "0003_copy_first_action_files")]

    operations = [
        migrations.AddField(
            model_name="file",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="historicalfile",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(copy_field, reverse_code=migrations.RunPython.noop),
    ]
