# Generated by Django 2.1.2 on 2020-04-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("files", "0004_auto_20200114_1511")]

    operations = [
        migrations.AddField(
            model_name="file", name="md5", field=models.TextField(blank=True)
        ),
        migrations.AddField(
            model_name="historicalfile",
            name="md5",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="history_change_reason",
            field=models.TextField(null=True),
        ),
    ]
