# Generated by Django 2.2.23 on 2021-07-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("files", "0006_fill_md5_from_aws_s3")]

    operations = [
        migrations.AddField(
            model_name="file",
            name="kind",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="historicalfile",
            name="kind",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
