# Generated by Django 2.2.23 on 2021-10-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_auto_20210709_2144"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="url",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="historicalfile",
            name="url",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
