# Generated by Django 2.2.23 on 2021-10-13 23:38

from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0008_auto_20211013_0929"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="upload",
            field=models.FileField(
                blank=True,
                null=True,
                storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="upload",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
