# Generated by Django 2.2.28 on 2024-04-30 19:59

import uuid

from django.db import migrations, models

import RoadLabsAPI.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0010_filedownload_historicalfiledownload"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericFile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=RoadLabsAPI.storage_backends.PrivateMediaStorage(),
                        upload_to="",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
