# Generated by Django 2.2.28 on 2024-05-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0064_merge_20240430_1604"),
        ("files", "0010_filedownload_historicalfiledownload"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_files",
                to="companies.Company",
            ),
        ),
        migrations.AddField(
            model_name="historicalfile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="companies.Company",
            ),
        ),
    ]
