# Generated by Django 2.2.28 on 2024-07-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0011_genericfile"),
        ("files", "0012_auto_20240607_0910"),
    ]

    operations = []
