# Generated by Django 2.2.28 on 2024-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0013_merge_20240725_1121"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalFileDownload",
        ),
    ]
