# Generated by Django 3.2.25 on 2025-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0014_delete_historicalfiledownload"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalfile",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical file",
                "verbose_name_plural": "historical files",
            },
        ),
        migrations.AlterField(
            model_name="historicalfile",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
