# Generated by Django 3.2.25 on 2025-05-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("device_id", models.CharField(max_length=255)),
                ("push_token", models.CharField(max_length=512)),
            ],
        ),
    ]
