# Generated by Django 3.2.25 on 2025-05-23 19:27
import logging

from django.db import migrations


def move_queuedpush_data_with_raw_sql(apps, schema_editor):
    """
    Copia dados da tabela email_handler_queuedpush para notifications_pushnotification
    usando SQL bruto, fazendo join com scarface_pushmessage para obter os campos.
    Exclui os campos receiver_arn, content_type_id e object_id.
    Processa em lotes para tabelas grandes.
    """
    BATCH_SIZE = 1000

    with schema_editor.connection.cursor() as cursor:
        # Primeiro, vamos contar quantos registros temos
        cursor.execute(
            """
            SELECT COUNT(*) 
            FROM email_handler_queuedpush qp
            INNER JOIN scarface_pushmessage pm ON qp.pushmessage_ptr_id = pm.id
            WHERE NOT EXISTS (
                SELECT 1 FROM notifications_pushnotification np 
                WHERE np.id = qp.pushmessage_ptr_id
            );
        """
        )
        total_records = cursor.fetchone()[0]
        logging.info(f"Total de registros para migrar: {total_records}")

        if total_records == 0:
            logging.info("Nenhum registro para migrar")
            return

        # Processa os dados principais em lotes
        offset = 0
        migrated_count = 0

        while offset < total_records:
            cursor.execute(
                """
                INSERT INTO notifications_pushnotification (
                    id, message, extra_payload, sound, company_id, cleared, 
                    in_progress, sent, created_at, updated_at, has_new_content, 
                    context_id, context, badge_count, message_type
                )
                SELECT 
                    qp.pushmessage_ptr_id as id,
                    pm.message,
                    pm.extra_payload,
                    pm.sound,
                    qp.company_id,
                    qp.cleared,
                    qp.in_progress,
                    qp.sent,
                    qp.created_at,
                    qp.updated_at,
                    pm.has_new_content,
                    pm.context_id,
                    pm.context,
                    pm.badge_count,
                    pm.message_type
                FROM email_handler_queuedpush qp
                INNER JOIN scarface_pushmessage pm ON qp.pushmessage_ptr_id = pm.id
                WHERE NOT EXISTS (
                    SELECT 1 FROM notifications_pushnotification np 
                    WHERE np.id = qp.pushmessage_ptr_id
                )
                ORDER BY qp.pushmessage_ptr_id
                LIMIT %s OFFSET %s;
            """,
                [BATCH_SIZE, offset],
            )

            rows_affected = cursor.rowcount
            migrated_count += rows_affected
            offset += BATCH_SIZE

            logging.info(
                f"Migrados {migrated_count}/{total_records} registros principais"
            )

            # Se não houve mais registros, para o loop
            if rows_affected == 0:
                break

        # Agora processa a tabela de relacionamento many-to-many em lotes
        cursor.execute(
            """
            SELECT COUNT(*) 
            FROM email_handler_queuedpush_devices qpd
            INNER JOIN notifications_pushnotification np ON np.id = qpd.queuedpush_id
            WHERE NOT EXISTS (
                SELECT 1 FROM notifications_pushnotification_devices npd
                WHERE npd.pushnotification_id = qpd.queuedpush_id 
                AND npd.device_id = qpd.device_id
            );
        """
        )
        total_devices = cursor.fetchone()[0]
        logging.info(f"Total de relacionamentos device para migrar: {total_devices}")

        if total_devices > 0:
            offset = 0
            migrated_devices = 0

            while offset < total_devices:
                cursor.execute(
                    """
                    INSERT INTO notifications_pushnotification_devices (
                        pushnotification_id, device_id
                    )
                    SELECT 
                        qpd.queuedpush_id as pushnotification_id,
                        qpd.device_id
                    FROM email_handler_queuedpush_devices qpd
                    INNER JOIN notifications_pushnotification np ON np.id = qpd.queuedpush_id
                    WHERE NOT EXISTS (
                        SELECT 1 FROM notifications_pushnotification_devices npd
                        WHERE npd.pushnotification_id = qpd.queuedpush_id 
                        AND npd.device_id = qpd.device_id
                    )
                    ORDER BY qpd.queuedpush_id, qpd.device_id
                    LIMIT %s OFFSET %s;
                """,
                    [BATCH_SIZE, offset],
                )

                rows_affected = cursor.rowcount
                migrated_devices += rows_affected
                offset += BATCH_SIZE

                logging.info(
                    f"Migrados {migrated_devices}/{total_devices} relacionamentos device"
                )

                # Se não houve mais registros, para o loop
                if rows_affected == 0:
                    break

        logging.info(
            f"Migração concluída: {migrated_count} registros principais e {migrated_devices} relacionamentos device"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_auto_20250523_1626"),
        ("email_handler", "0030_auto_20250227_1243"),
    ]

    operations = [
        migrations.RunPython(move_queuedpush_data_with_raw_sql),
    ]
