# Generated by Django 3.2.25 on 2025-05-23 19:28
import logging

from django.db import migrations


def move_userpush_data_with_raw_sql(apps, schema_editor):
    """
    Copia dados da tabela email_handler_userpush para notifications_userpush
    usando SQL bruto. Processa em lotes para tabelas grandes.
    """
    BATCH_SIZE = 1000

    with schema_editor.connection.cursor() as cursor:
        # Primeiro, vamos contar quantos registros temos
        cursor.execute(
            """
            SELECT COUNT(*) 
            FROM email_handler_userpush eup
            WHERE eup.push_message_id IS NOT NULL
            AND EXISTS (
                SELECT 1 FROM notifications_pushnotification np 
                WHERE np.id = eup.push_message_id
            )
            AND NOT EXISTS (
                SELECT 1 FROM notifications_userpush nup 
                WHERE nup.uuid = eup.uuid
            );
        """
        )
        total_records = cursor.fetchone()[0]
        logging.info(f"Total de registros UserPush para migrar: {total_records}")

        if total_records == 0:
            logging.info("Nenhum registro UserPush para migrar")
            return

        # Processa os dados em lotes
        offset = 0
        migrated_count = 0

        while offset < total_records:
            cursor.execute(
                """
                INSERT INTO notifications_userpush (
                    uuid, user_id, push_message_id, read
                )
                SELECT 
                    eup.uuid,
                    eup.user_id,
                    eup.push_message_id,
                    eup.read
                FROM email_handler_userpush eup
                WHERE eup.push_message_id IS NOT NULL
                AND EXISTS (
                    SELECT 1 FROM notifications_pushnotification np 
                    WHERE np.id = eup.push_message_id
                )
                AND NOT EXISTS (
                    SELECT 1 FROM notifications_userpush nup 
                    WHERE nup.uuid = eup.uuid
                )
                ORDER BY eup.uuid
                LIMIT %s OFFSET %s;
            """,
                [BATCH_SIZE, offset],
            )

            rows_affected = cursor.rowcount
            migrated_count += rows_affected
            offset += BATCH_SIZE

            logging.info(
                f"Migrados {migrated_count}/{total_records} registros UserPush"
            )

            # Se não houve mais registros, para o loop
            if rows_affected == 0:
                break

        logging.info(
            f"Migração UserPush concluída: {migrated_count} registros migrados"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_migrate_push_notifications_data"),
        ("email_handler", "0030_auto_20250227_1243"),
    ]

    operations = [
        migrations.RunPython(move_userpush_data_with_raw_sql),
    ]
