# Generated by Django 3.2.25 on 2025-09-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_reset_sequences_after_data_copy"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpushnotification",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pushnotification",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
